In [2]:
import pandas as pd
gene_reference = pd.read_csv('gene2pubtator3', sep='\t', header=None)
gene_reference.columns = ['PMID', 'EntityType', 'GeneID', 'MentionText', 'Source']
print('Gene Pubtator3 set loaded!')

# Grab PMIDs from Pubtator3 using Reference Set
# gene_hits = gene_reference[gene_reference['MentionText'].str.contains(term, na=False)].reset_index(drop=True)

/var/folders/5t/sfw5tjx56m10xb861_pd3wfm0000gq/T/ipykernel_38338/1736516257.py:2: DtypeWarning: Columns (2,3) have mixed types. Specify dtype option on import or set low_memory=False.
  gene_reference = pd.read_csv('gene2pubtator3', sep='\t', header=None)

Gene Pubtator3 set loaded!

In [3]:
gene_reference

,PMID,EntityType,GeneID,MentionText,Source
0,40591000,Gene,1084,CEA|carcinoembryonic antigen,PubTator3
1,40591000,Gene,94025,carbohydrate antigen 125|CA125,PubTator3
2,40486000,Gene,3630,C-peptide,PubTator3
3,40510000,Gene,1401,C-reactive protein,PubTator3
4,40510000,Gene,3569,interleukin-6,PubTator3
...,...,...,...,...,...
72410431,35739999,Gene,22166,Trx,PubTator3
72410432,35739999,Gene,8075,PCS,PubTator3
72410433,35739999,Gene,114757,cytoglobin,PubTator3
72410434,35739999,Gene,232223,TGR|thioredoxin-glutathione reductase,PubTator3
72410435,35739999,Gene,79747,androglobin,PubTator3

In [5]:
gene_reference['PMID'].nunique()

9048478

In [8]:
gene_hits = gene_reference[gene_reference['GeneID']=='21'].reset_index(drop=True)
gene_hits

,PMID,EntityType,GeneID,MentionText,Source
0,38803436,Gene,21,ABCA3,PubTator3
1,39197438,Gene,21,ABC-3,PubTator3
2,39829677,Gene,21,ABC3,PubTator3
3,31455000,Gene,21,ABCA3|ATP-binding cassette subfamily A member 3,PubTator3
4,32272001,Gene,21,ABCA3,PubTator3
...,...,...,...,...,...
1468,32684997,Gene,21,ABCA3,PubTator3
1469,28327998,Gene,21,ABC 3,PubTator3
1470,31563998,Gene,21,ABCA3,PubTator3
1471,16449999,Gene,21,ABCA3,PubTator3
1472,35095999,Gene,21,ABCA3,PubTator3

In [ ]:
gene_hits.loc[gene_hits['MentionText'].str.contains('LBM180', na=False)]

,PMID,EntityType,GeneID,MentionText,Source
880,11940594,Gene,21,ABCA3|LBM180,PubTator3|generifs_basic|MESH|gene2pubmed