# **Automatic Alternate Abbreviation Annotation:** Analyzing results of LLM predictions

This notebook analyzes LLM predictions from the Alternate Abbreviation annotation workflow by loading previously stored LLM runs and computing performance, coverage, and system-level metrics. It also generates evaluation datasets to support troubleshooting and review of model predictions. For more information on Alternate Abbreviations and the overall workflow, see [README](alternate_abbreviation_README).

In [123]:
import pickle
from dataclasses import replace
from pathlib import Path

import polars as pl
from alt_abbrev_llm_functions import *

## Load stored runs from alt_abbrev_llm_1_run_samples notebook

In [124]:
ALT_ABBREV_ROOT = Path.cwd().resolve()
ALT_ABBREV_OUTPUT_PATH = ALT_ABBREV_ROOT / "output"

In [125]:
path = Path(
    ALT_ABBREV_OUTPUT_PATH
    / "llm_runs"
    / "stored_runs_alt_abbrev_annotation_manually_annotated_df_pv1_t0p0_agg3.pkl"
)

with path.open("rb") as f:
    data = pickle.load(f)

all_runs = data["runs"]

## Summary of runs

In [126]:
sample_names = set()

unique_runs = {
    (
        run["temperature"],
        run["run_idx"],
    )
    for run in all_runs
}
print(f"Total number of runs stored: {len(all_runs)}")
print(f"Unique runs: {unique_runs}")

Total number of runs stored: 3
Unique runs: {(0.0, 1), (0.0, 2), (0.0, 0)}

## Format runs for analysis

In [127]:
if isinstance(all_runs, dict):
    all_runs = all_runs["runs"]

rows = []

for run in all_runs:
    for i, r in enumerate(run["results"]):
        rows.append(
            {
                "row": i,
                "run": run["run_idx"],
                "temp": run["temperature"],
                "llm": r["llm_annotation"],
                "gt": r["gt"],
            }
        )

df_runs = pl.DataFrame(rows).with_columns(
    [
        pl.col("llm").cast(pl.Boolean),
        pl.col("gt").cast(pl.Boolean),
    ]
)

In [128]:
results_by_run = {}

for temp, run_idx in unique_runs:
    run_df = df_runs.filter((pl.col("temp") == temp) & (pl.col("run") == run_idx))

    run_result = analyze_results(run_df)
    run_result = replace(
    run_result,
    temperature=temp,
    run_idx=run_idx,
)

    results_by_run[(temp, run_idx)] = run_result

## Analysis between runs

In [129]:
all_results = [
    {
        "temperature": run.temperature,
        "run_idx": run.run_idx,
        "llm_accuracy": run.llm_accuracy,
        "llm_coverage": run.llm_coverage,
        "system_accuracy": run.system_accuracy,
    }
    for run in results_by_run.values()
]

results_df = pl.DataFrame(all_results)
print(results_df)

shape: (3, 5)
┌─────────────┬─────────┬──────────────┬──────────────┬─────────────────┐
│ temperature ┆ run_idx ┆ llm_accuracy ┆ llm_coverage ┆ system_accuracy │
│ ---         ┆ ---     ┆ ---          ┆ ---          ┆ ---             │
│ f64         ┆ i64     ┆ f64          ┆ f64          ┆ f64             │
╞═════════════╪═════════╪══════════════╪══════════════╪═════════════════╡
│ 0.0         ┆ 1       ┆ 0.886364     ┆ 0.435644     ┆ 0.950495        │
│ 0.0         ┆ 2       ┆ 0.895455     ┆ 0.435644     ┆ 0.954455        │
│ 0.0         ┆ 0       ┆ 0.895455     ┆ 0.435644     ┆ 0.954455        │
└─────────────┴─────────┴──────────────┴──────────────┴─────────────────┘

## Analysis of a single run

In [138]:
run_00_2 = results_by_run[(0.0, 2)]
print(f"LLM Coverage: {run_00_2.llm_coverage}")
print(run_00_2.llm_metrics)
print(run_00_2.llm_accuracy)
print(run_00_2.system_metrics)
print(run_00_2.system_accuracy)

LLM Coverage: 0.43564356435643564
shape: (1, 8)
┌─────────────────┬───────────┬──────────┬──────────┬─────┬─────┬─────┬─────┐
│ evaluation_type ┆ precision ┆ recall   ┆ f1       ┆ TP  ┆ FP  ┆ TN  ┆ FN  │
│ ---             ┆ ---       ┆ ---      ┆ ---      ┆ --- ┆ --- ┆ --- ┆ --- │
│ str             ┆ f64       ┆ f64      ┆ f64      ┆ i64 ┆ i64 ┆ i64 ┆ i64 │
╞═════════════════╪═══════════╪══════════╪══════════╪═════╪═════╪═════╪═════╡
│ conditional_llm ┆ 0.789474  ┆ 0.895522 ┆ 0.839161 ┆ 60  ┆ 16  ┆ 137 ┆ 7   │
└─────────────────┴───────────┴──────────┴──────────┴─────┴─────┴─────┴─────┘
0.8954545454545455
shape: (1, 8)
┌─────────────────┬───────────┬──────────┬──────────┬─────┬─────┬─────┬─────┐
│ evaluation_type ┆ precision ┆ recall   ┆ f1       ┆ TP  ┆ FP  ┆ TN  ┆ FN  │
│ ---             ┆ ---       ┆ ---      ┆ ---      ┆ --- ┆ --- ┆ --- ┆ --- │
│ str             ┆ f64       ┆ f64      ┆ f64      ┆ i64 ┆ i64 ┆ i64 ┆ i64 │
╞═════════════════╪═══════════╪══════════╪══════════╪═════╪═════╪═════╪═════╡
│ system_level    ┆ 0.789474  ┆ 0.895522 ┆ 0.839161 ┆ 60  ┆ 16  ┆ 422 ┆ 7   │
└─────────────────┴───────────┴──────────┴──────────┴─────┴─────┴─────┴─────┘
0.9544554455445544

In [139]:
df = pl.read_parquet(path.with_suffix(".parquet"))

## Evaluation df for troubleshooting and idea generation

In [140]:
eval_df = build_eval_df(
    df,
    all_runs,
    temperature=0.0,
    run_idx=1,
)
eval_df

shape: (505, 14)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬─────────┬───────────┐
│ HGNC_ID    ┆ ENSG_ID   ┆ NCBI_ID   ┆ captured_ ┆ … ┆ matched_r ┆ temperatu ┆ run_idx ┆ llm_corre │
│ ---        ┆ ---       ┆ ---       ┆ status    ┆   ┆ ule       ┆ re        ┆ ---     ┆ ct        │
│ str        ┆ str       ┆ str       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ i64     ┆ ---       │
│            ┆           ┆           ┆ bool      ┆   ┆ str       ┆ f64       ┆         ┆ bool      │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═════════╪═══════════╡
│ HGNC:12406 ┆ ENSG00000 ┆ GENE      ┆ false     ┆ … ┆ low_lcs_s ┆ 0.0       ┆ 1       ┆ null      │
│            ┆ 166402    ┆ ID:7275   ┆           ┆   ┆ imilarity ┆           ┆         ┆           │
│ HGNC:6631  ┆ ENSG00000 ┆ GENE      ┆ false     ┆ … ┆ extra_cha ┆ 0.0       ┆ 1       ┆ null      │
│            ┆ 074695    ┆ ID:3998   ┆           ┆   ┆ racters   ┆           ┆         ┆           │
│ HGNC:9911  ┆ ENSG00000 ┆ GENE      ┆ false     ┆ … ┆ null      ┆ 0.0       ┆ 1       ┆ true      │
│            ┆ 216835    ┆ ID:3186   ┆           ┆   ┆           ┆           ┆         ┆           │
│ HGNC:3795  ┆ ENSG00000 ┆ GENE      ┆ false     ┆ … ┆ null      ┆ 0.0       ┆ 1       ┆ true      │
│            ┆ 110203    ┆ ID:2352   ┆           ┆   ┆           ┆           ┆         ┆           │
│ HGNC:13919 ┆ ENSG00000 ┆ GENE      ┆ false     ┆ … ┆ extra_cha ┆ 0.0       ┆ 1       ┆ null      │
│            ┆ 234651,   ┆ ID:7917   ┆           ┆   ┆ racters   ┆           ┆         ┆           │
│            ┆ ENSG00000 ┆           ┆           ┆   ┆           ┆           ┆         ┆           │
│            ┆ 0961…     ┆           ┆           ┆   ┆           ┆           ┆         ┆           │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …       ┆ …         │
│ HGNC:29334 ┆ ENSG00000 ┆ GENE      ┆ false     ┆ … ┆ null      ┆ 0.0       ┆ 1       ┆ true      │
│            ┆ 159733    ┆ ID:57732  ┆           ┆   ┆           ┆           ┆         ┆           │
│ HGNC:43475 ┆ ENSG00000 ┆ GENE ID:1 ┆ true      ┆ … ┆ null      ┆ 0.0       ┆ 1       ┆ true      │
│            ┆ 284092    ┆ 00847081  ┆           ┆   ┆           ┆           ┆         ┆           │
│ HGNC:22423 ┆ ENSG00000 ┆ GENE      ┆ true      ┆ … ┆ extra_cha ┆ 0.0       ┆ 1       ┆ null      │
│            ┆ 146858    ┆ ID:92092  ┆           ┆   ┆ racters   ┆           ┆         ┆           │
│ HGNC:13848 ┆ ENSG00000 ┆ GENE      ┆ true      ┆ … ┆ extra_cha ┆ 0.0       ┆ 1       ┆ null      │
│            ┆ 089335    ┆ ID:55900  ┆           ┆   ┆ racters   ┆           ┆         ┆           │
│ HGNC:43469 ┆ ENSG00000 ┆ GENE ID:1 ┆ true      ┆ … ┆ conflict_ ┆ 0.0       ┆ 1       ┆ null      │
│            ┆ 265859    ┆ 00847040  ┆           ┆   ┆ category  ┆           ┆         ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴─────────┴───────────┘

In [141]:
wrong_llm_df = eval_df.filter(~pl.col("llm_correct"))
wrong_llm_df

shape: (25, 14)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬─────────┬───────────┐
│ HGNC_ID    ┆ ENSG_ID   ┆ NCBI_ID   ┆ captured_ ┆ … ┆ matched_r ┆ temperatu ┆ run_idx ┆ llm_corre │
│ ---        ┆ ---       ┆ ---       ┆ status    ┆   ┆ ule       ┆ re        ┆ ---     ┆ ct        │
│ str        ┆ str       ┆ str       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ i64     ┆ ---       │
│            ┆           ┆           ┆ bool      ┆   ┆ str       ┆ f64       ┆         ┆ bool      │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═════════╪═══════════╡
│ HGNC:24086 ┆ ENSG00000 ┆ GENE      ┆ false     ┆ … ┆ null      ┆ 0.0       ┆ 1       ┆ false     │
│            ┆ 148584    ┆ ID:29974  ┆           ┆   ┆           ┆           ┆         ┆           │
│ HGNC:19    ┆ ENSG00000 ┆ GENE      ┆ false     ┆ … ┆ null      ┆ 0.0       ┆ 1       ┆ false     │
│            ┆ 129673    ┆ ID:15     ┆           ┆   ┆           ┆           ┆         ┆           │
│ HGNC:9309  ┆ ENSG00000 ┆ GENE      ┆ false     ┆ … ┆ null      ┆ 0.0       ┆ 1       ┆ false     │
│            ┆ 066027    ┆ ID:5525   ┆           ┆   ┆           ┆           ┆         ┆           │
│ HGNC:10924 ┆ ENSG00000 ┆ GENE      ┆ false     ┆ … ┆ null      ┆ 0.0       ┆ 1       ┆ false     │
│            ┆ 141526    ┆ ID:9123   ┆           ┆   ┆           ┆           ┆         ┆           │
│ HGNC:978   ┆ ENSG00000 ┆ GENE      ┆ false     ┆ … ┆ null      ┆ 0.0       ┆ 1       ┆ false     │
│            ┆ 107949    ┆ ID:56647  ┆           ┆   ┆           ┆           ┆         ┆           │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …       ┆ …         │
│ HGNC:11599 ┆ ENSG00000 ┆ GENE      ┆ false     ┆ … ┆ null      ┆ 0.0       ┆ 1       ┆ false     │
│            ┆ 073861    ┆ ID:30009  ┆           ┆   ┆           ┆           ┆         ┆           │
│ HGNC:2314  ┆ ENSG00000 ┆ GENE      ┆ false     ┆ … ┆ null      ┆ 0.0       ┆ 1       ┆ false     │
│            ┆ 214078    ┆ ID:8904   ┆           ┆   ┆           ┆           ┆         ┆           │
│ HGNC:5686  ┆ ENSG00000 ┆ GENE      ┆ false     ┆ … ┆ null      ┆ 0.0       ┆ 1       ┆ false     │
│            ┆ 254329    ┆ ID:28361  ┆           ┆   ┆           ┆           ┆         ┆           │
│ HGNC:1126  ┆ null      ┆ GENE      ┆ false     ┆ … ┆ null      ┆ 0.0       ┆ 1       ┆ false     │
│            ┆           ┆ ID:690    ┆           ┆   ┆           ┆           ┆         ┆           │
│ HGNC:17546 ┆ ENSG00000 ┆ GENE      ┆ true      ┆ … ┆ null      ┆ 0.0       ┆ 1       ┆ false     │
│            ┆ 140044    ┆ ID:122953 ┆           ┆   ┆           ┆           ┆         ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴─────────┴───────────┘