### Import

In [122]:
import pandas as pd
import numpy as np
import re
from datetime import datetime

In [123]:
# def create_ap_collision_df(mini_xxxx_df: pd.DataFrame, source: str) -> pd.DataFrame:
#     """ CASE SENSITIVE COLLISIONS
#     Create a df of alias-primary collision symbols 

#     :param mini_xxxx_df: Processed df of gene records
#     :param source: Representation of the source of the gene records
#     :param split_on_character: Character that is used to seperate alias symbols in the mini_xxxx_df
#     :return: A df of genes that share an alias with another gene
#     """

#     #Remove placeholder gene records (those with no primary gene symbol)
#     mini_xxxx_df = mini_xxxx_df.dropna(subset=["gene_symbol"])

#     #mini_xxx_df
#     ## no LOC genes (only present in NCBI)
#     ## no records with no primary symbols (only present in ENSG)
#     ## each alias on a separate row
#     #Convert the df into a csv and save
#     mini_xxxx_df.to_csv(f'../output/mini_{source.lower()}_df.csv', index=True) 

#     #Make a new df where the alias symbols are merged together for each record
#     merged_alias_xxxx_df = (
#         mini_xxxx_df
#         .copy()
#         .fillna("")
#         .groupby(f"{source}_ID", dropna=False)
#         .agg(lambda col: ",".join(sorted(set(map(str, col)))))
#         .reset_index()
#     )

#     #merged_alias_xxxx_df
#     ##merging aliases associated with the same record (same gene record identifier) into a list
#     #Convert the df into a csv and save
#     merged_alias_xxxx_df.to_csv(f'../output/merged_alias_{source}_df.csv', index=True) 

#     #Make a set of the primary gene symbols
#     xxxx_gene_symbol_set = set(mini_xxxx_df["gene_symbol"])

#     subset_genes_xxxx_df = mini_xxxx_df.copy()

#     #Remove alias symbols that are an exact match to their respective primary gene symbol
#     subset_genes_xxxx_df['alias_symbol'] = subset_genes_xxxx_df.apply(lambda row: np.nan if row['alias_symbol'] == row['gene_symbol'] else row['alias_symbol'], axis=1)

#     #subset_genes_xxxx_df
#     ## no aliases that match the primary gene symbol
#     ## each alias on a separate row
#     #Convert the df into a csv and save
#     subset_genes_xxxx_df.to_csv(f'../output/subset_genes_{source}_df.csv', index=True) 

#     #Create df with genes that have an alias that can be found as another gene's primary gene symbol
#     ap_collision_xxxx_df = subset_genes_xxxx_df.copy()
#     ap_collision_xxxx_df = ap_collision_xxxx_df.dropna(subset=["alias_symbol"])

#     #makes list of aliases into a set
#     ap_collision_xxxx_df.loc[:, "alias_symbol"] = ap_collision_xxxx_df["alias_symbol"].apply(lambda x: {x})

#     ap_collision_xxxx_df.loc[:, "collision"] = ap_collision_xxxx_df["alias_symbol"].apply(
#         lambda x: x & xxxx_gene_symbol_set
#     )
#     ap_collision_xxxx_df = ap_collision_xxxx_df[ap_collision_xxxx_df["collision"].apply(lambda x: len(x) > 0)]
#     #changes back the set of aliases to a list, and make the set of collisions to a list
#     ap_collision_xxxx_df['collision'] = ap_collision_xxxx_df['collision'].apply(
#         lambda x: ', '.join(map(str, x)) if isinstance(x, set) else x
#     )
#     ap_collision_xxxx_df = ap_collision_xxxx_df.sort_values("collision")

#     #Add a source tag for future merging efforts
#     ap_collision_xxxx_df["source"] = str(source.upper())

#     #ap_collision_xxxx_df
#     ## only the gene records with an alias that matches another gene record's primary gene symbol
#     ## each alias on a separate row
#     #Convert the df into a csv
#     ap_collision_xxxx_df.to_csv(f'../output/single_alias_ap_collision_{source.lower()}_df.csv', index=True)

#     #Create a secondary collision df that merges the alias symbols for each record
#     columns_map = {
#         'ENSG': ['NCBI_ID', 'HGNC_ID'],
#         'HGNC': ['NCBI_ID', 'ENSG_ID'],
#         'NCBI': ['HGNC_ID', 'ENSG_ID']
#     }

#     cols_of_interest = columns_map.get(source, [])

#     merged_alias_ap_collision_xxxx_df = ap_collision_xxxx_df.drop(columns=cols_of_interest + ['alias_symbol'])

#     merged_alias_ap_collision_xxxx_df = pd.merge(
#         merged_alias_ap_collision_xxxx_df,
#         merged_alias_xxxx_df[[f"{source}_ID"] + cols_of_interest + ['alias_symbol']],
#         on=[f"{source}_ID"],
#         how="left"
#     )
#     merged_alias_ap_collision_xxxx_df = merged_alias_ap_collision_xxxx_df.drop_duplicates(subset=[f"{source}_ID"])

#     #Test to make sure all collisions are in the alias list for the record
#     test_ap_collision_xxxx_df = merged_alias_ap_collision_xxxx_df.copy()
#     test_ap_collision_xxxx_df['alias_symbol'] = test_ap_collision_xxxx_df['alias_symbol'].apply(lambda x: x if isinstance(x, list) else [x])
#     test_ap_collision_xxxx_df['collision_in_alias'] = test_ap_collision_xxxx_df.apply(lambda row: row['collision'] in test_ap_collision_xxxx_df['alias_symbol'].values, axis=1)
#     true_count = test_ap_collision_xxxx_df['collision_in_alias'].sum()

#     if true_count == 0:
#         #merged_alias_ap_collision_xxxx_df
#         ## only the gene records with an alias that matches another gene record's primary gene symbol
#         ## merging aliases associated with the same record (same gene record identifier) into a list
#         #Convert the df into a csv and save
#         merged_alias_ap_collision_xxxx_df.to_csv(f'../output/merged_alias_ap_collision_{source.lower()}_df.csv', index=True)
#         print("All collisions are present in gene alias lists.")
#     else:
#         print("Some collisions are not present in gene alias lists.")

#     return mini_xxxx_df.head()

In [124]:
def create_ap_collision_df(mini_xxxx_df: pd.DataFrame, source: str) -> pd.DataFrame:
    """ CASE INSENSITIVE COLLISIONS
    Create a df of alias-primary collision symbols 

    :param mini_xxxx_df: Processed df of gene records
    :param source: Representation of the source of the gene records
    :param split_on_character: Character that is used to seperate alias symbols in the mini_xxxx_df
    :return: A df of genes that share an alias with another gene
    """

    #Remove placeholder gene records (those with no primary gene symbol)
    mini_xxxx_df = mini_xxxx_df.dropna(subset=["gene_symbol"])

    #mini_xxx_df
    ## no LOC genes (only present in NCBI)
    ## no records with no primary symbols (only present in ENSG)
    ## each alias on a separate row
    #Convert the df into a csv and save
    mini_xxxx_df.to_csv(f'../output/mini_{source.lower()}_df.csv', index=True) 

    #Make a new df where the alias symbols are merged together for each record
    merged_alias_xxxx_df = (
        mini_xxxx_df
        .copy()
        .fillna("")
        .groupby(f"{source}_ID", dropna=False)
        .agg(lambda col: ",".join(sorted(set(map(str, col)))))
        .reset_index()
    )

    #merged_alias_xxxx_df
    ##merging aliases associated with the same record (same gene record identifier) into a list
    #Convert the df into a csv and save
    merged_alias_xxxx_df.to_csv(f'../output/merged_alias_{source}_df.csv', index=True) 

    #Make a set of the primary gene symbols
    xxxx_gene_symbol_set = set(mini_xxxx_df["gene_symbol"])
    uppercased_xxxx_gene_symbol_set = {s.upper() for s in xxxx_gene_symbol_set}

    
    subset_genes_xxxx_df = mini_xxxx_df.copy()

    #Remove alias symbols that are an exact match to their respective primary gene symbol
    subset_genes_xxxx_df["alias_symbol_upper"] = subset_genes_xxxx_df["alias_symbol"].str.upper()
    subset_genes_xxxx_df["gene_symbol_upper"] = subset_genes_xxxx_df["gene_symbol"].str.upper()
    subset_genes_xxxx_df['alias_symbol'] = subset_genes_xxxx_df.apply(lambda row: np.nan if row['alias_symbol_upper'] == row['gene_symbol_upper'] else row['alias_symbol'], axis=1)
    subset_genes_xxxx_df = subset_genes_xxxx_df.drop(["alias_symbol_upper","gene_symbol_upper"], axis=1)

    #subset_genes_xxxx_df
    ## no aliases that match the primary gene symbol
    ## each alias on a separate row
    #Convert the df into a csv and save
    subset_genes_xxxx_df.to_csv(f'../output/subset_genes_{source}_df.csv', index=True) 

    #Create df with genes that have an alias that can be found as another gene's primary gene symbol
    ap_collision_xxxx_df = subset_genes_xxxx_df.copy()
    ap_collision_xxxx_df = ap_collision_xxxx_df.dropna(subset=["alias_symbol"])
    ap_collision_xxxx_df["alias_symbol_upper"] = ap_collision_xxxx_df["alias_symbol"].str.upper()

    #makes list of aliases into a set
    ap_collision_xxxx_df.loc[:, "alias_symbol_upper"] = ap_collision_xxxx_df["alias_symbol_upper"].apply(lambda x: {x})

    ap_collision_xxxx_df.loc[:, "collision"] = ap_collision_xxxx_df["alias_symbol_upper"].apply(
        lambda x: x & uppercased_xxxx_gene_symbol_set
    )
    ap_collision_xxxx_df = ap_collision_xxxx_df.drop("alias_symbol_upper", axis=1)
    ap_collision_xxxx_df = ap_collision_xxxx_df[ap_collision_xxxx_df["collision"].apply(lambda x: len(x) > 0)]
    #changes back the set of aliases to a list, and make the set of collisions to a list
    ap_collision_xxxx_df['collision'] = ap_collision_xxxx_df['collision'].apply(
        lambda x: ', '.join(map(str, x)) if isinstance(x, set) else x
    )
    ap_collision_xxxx_df = ap_collision_xxxx_df.sort_values("collision")

    #Add a source tag for future merging efforts
    ap_collision_xxxx_df["source"] = str(source.upper())

    #ap_collision_xxxx_df
    ## only the gene records with an alias that matches another gene record's primary gene symbol
    ## each alias on a separate row
    #Convert the df into a csv
    ap_collision_xxxx_df.to_csv(f'../output/single_alias_ap_collision_{source.lower()}_df.csv', index=True)

    #Create a secondary collision df that merges the alias symbols for each record
    columns_map = {
        'ENSG': ['NCBI_ID', 'HGNC_ID'],
        'HGNC': ['NCBI_ID', 'ENSG_ID'],
        'NCBI': ['HGNC_ID', 'ENSG_ID']
    }

    cols_of_interest = columns_map.get(source, [])

    merged_alias_ap_collision_xxxx_df = ap_collision_xxxx_df.drop(columns=cols_of_interest + ['alias_symbol'])

    merged_alias_ap_collision_xxxx_df = pd.merge(
        merged_alias_ap_collision_xxxx_df,
        merged_alias_xxxx_df[[f"{source}_ID"] + cols_of_interest + ['alias_symbol']],
        on=[f"{source}_ID"],
        how="left"
    )
    merged_alias_ap_collision_xxxx_df = merged_alias_ap_collision_xxxx_df.drop_duplicates(subset=[f"{source}_ID"])

    #Test to make sure all collisions are in the alias list for the record
    test_ap_collision_xxxx_df = merged_alias_ap_collision_xxxx_df.copy()
    test_ap_collision_xxxx_df["alias_symbol_upper"] = test_ap_collision_xxxx_df["alias_symbol"].str.upper()   
    test_ap_collision_xxxx_df['alias_symbol_upper'] = test_ap_collision_xxxx_df['alias_symbol_upper'].apply(lambda x: x if isinstance(x, list) else [x])
    test_ap_collision_xxxx_df['collision_in_alias'] = test_ap_collision_xxxx_df.apply(lambda row: row['collision'] in test_ap_collision_xxxx_df['alias_symbol_upper'].values, axis=1)
    true_count = test_ap_collision_xxxx_df['collision_in_alias'].sum()
    test_ap_collision_xxxx_df = test_ap_collision_xxxx_df.drop("alias_symbol_upper", axis=1)

    if true_count == 0:
        #merged_alias_ap_collision_xxxx_df
        ## only the gene records with an alias that matches another gene record's primary gene symbol
        ## merging aliases associated with the same record (same gene record identifier) into a list
        #Convert the df into a csv and save
        merged_alias_ap_collision_xxxx_df.to_csv(f'../output/merged_alias_ap_collision_{source.lower()}_df.csv', index=True)
        print("All collisions are present in gene alias lists.")
    else:
        print("Some collisions are not present in gene alias lists.")

    return mini_xxxx_df.head()

# Ensembl

In [125]:
raw_ensg_df = pd.read_csv("../output/raw_ensg_df.csv")
raw_ensg_df

                ENSG_ID        NCBI_ID     HGNC_ID alias_symbol gene_symbol
0       ENSG00000210049            NaN   HGNC:7481         MTTF       MT-TF
1       ENSG00000210049            NaN   HGNC:7481         TRNF       MT-TF
2       ENSG00000211459            NaN   HGNC:7470          12S     MT-RNR1
3       ENSG00000211459            NaN   HGNC:7470       MOTS-C     MT-RNR1
4       ENSG00000211459            NaN   HGNC:7470       MTRNR1     MT-RNR1
...                 ...            ...         ...          ...         ...
133060  ENSG00000229388            NaN  HGNC:52502    LINC01715    TAF12-DT
133061  ENSG00000289291            NaN         NaN          NaN         NaN
133062  ENSG00000274978  GENE ID:26824  HGNC:10108      RNU11-1       RNU11
133063  ENSG00000274978  GENE ID:26824  HGNC:10108          U11       RNU11
133064  ENSG00000296488            NaN         NaN          NaN         NaN

[133065 rows x 5 columns]

how many gene records for the Ensembl data set before any kind of cleaning?

In [126]:
total_raw_gene_record_set_ensg = set(raw_ensg_df['ENSG_ID'])
total_raw_gene_record_count_ensg = len(total_raw_gene_record_set_ensg)
total_raw_gene_record_count_ensg

86364

how many gene records have no primary gene symbol?

In [127]:
raw_no_primary_symbol_record_count_ensg = (
    raw_ensg_df[raw_ensg_df["gene_symbol"].isna()]
    .dropna(subset=["ENSG_ID"])
    ["ENSG_ID"]
    .nunique()
)
raw_no_primary_symbol_record_count_ensg

37963

how many gene records that have a primary gene symbol that is a LOC placeholder?

In [128]:
raw_loc_record_count_ensg = (
    raw_ensg_df[raw_ensg_df["gene_symbol"].str.startswith('LOC', na=False)&
    ~raw_ensg_df['gene_symbol']
    .str.contains('-', na=False)]
    .dropna(subset=["ENSG_ID"])
    ["ENSG_ID"]
    .nunique()
)
raw_loc_record_count_ensg

0

how many records with an @ symbol in the primary gene symbol?

In [129]:
at_symbol_records_ensg_df = raw_ensg_df[raw_ensg_df['gene_symbol'].str.contains('@', na=False)]
len(set(at_symbol_records_ensg_df["ENSG_ID"]))

0

In [130]:
create_ap_collision_df(raw_ensg_df, "ENSG")

All collisions are present in gene alias lists.

           ENSG_ID NCBI_ID    HGNC_ID alias_symbol gene_symbol
0  ENSG00000210049     NaN  HGNC:7481         MTTF       MT-TF
1  ENSG00000210049     NaN  HGNC:7481         TRNF       MT-TF
2  ENSG00000211459     NaN  HGNC:7470          12S     MT-RNR1
3  ENSG00000211459     NaN  HGNC:7470       MOTS-C     MT-RNR1
4  ENSG00000211459     NaN  HGNC:7470       MTRNR1     MT-RNR1

In [131]:
mini_ensg_df = pd.read_csv(
    "../output/mini_ensg_df.csv", index_col=[0])

In [132]:
subset_genes_ensg_df = pd.read_csv(
    "../output/subset_genes_ensg_df.csv", index_col=[0])
subset_genes_ensg_df

                ENSG_ID        NCBI_ID     HGNC_ID alias_symbol gene_symbol
0       ENSG00000210049            NaN   HGNC:7481         MTTF       MT-TF
1       ENSG00000210049            NaN   HGNC:7481         TRNF       MT-TF
2       ENSG00000211459            NaN   HGNC:7470          12S     MT-RNR1
3       ENSG00000211459            NaN   HGNC:7470       MOTS-C     MT-RNR1
4       ENSG00000211459            NaN   HGNC:7470       MTRNR1     MT-RNR1
...                 ...            ...         ...          ...         ...
133058  ENSG00000197989  GENE ID:85028  HGNC:30062    LINC00100      SNHG12
133059  ENSG00000197989  GENE ID:85028  HGNC:30062     PNAS-123      SNHG12
133060  ENSG00000229388            NaN  HGNC:52502    LINC01715    TAF12-DT
133062  ENSG00000274978  GENE ID:26824  HGNC:10108      RNU11-1       RNU11
133063  ENSG00000274978  GENE ID:26824  HGNC:10108          U11       RNU11

[95024 rows x 5 columns]

In [133]:
ap_collision_ensg_df = pd.read_csv(
    "../output/single_alias_ap_collision_ensg_df.csv", index_col=[0])
ap_collision_ensg_df

,ENSG_ID,NCBI_ID,HGNC_ID,alias_symbol,gene_symbol,collision,source
24761,ENSG00000283293,GENE ID:125050,HGNC:10037,7SK,RN7SK,7SK,ENSG
37365,ENSG00000057252,GENE ID:6646,HGNC:11177,ACAT1,SOAT1,ACAT1,ENSG
17666,ENSG00000167780,GENE ID:8435,HGNC:11178,ACAT2,SOAT2,ACAT2,ENSG
35063,ENSG00000004779,GENE ID:4706,HGNC:7694,ACP1,NDUFAB1,ACP1,ENSG
47647,ENSG00000220267,NaN,HGNC:141,ACTBP2,ACTBP8,ACTBP2,ENSG
...,...,...,...,...,...,...,...
53226,ENSG00000197961,GENE ID:7675,HGNC:12904,ZNF20,ZNF121,ZNF20,ENSG
35374,ENSG00000110315,GENE ID:50862,HGNC:21159,ZNF230,RNF141,ZNF230,ENSG
96229,ENSG00000188801,NaN,HGNC:14003,ZNF322,ZNF322P1,ZNF322,ENSG
81813,ENSG00000103994,GENE ID:64397,HGNC:12886,ZNF474,ZNF106,ZNF474,ENSG
14437,ENSG00000184517,GENE ID:162239,HGNC:23328,ZNF475,ZFP1,ZNF475,ENSG

In [134]:
merged_alias_ap_collision_ensg_df = pd.read_csv(
    "../output/merged_alias_ap_collision_ensg_df.csv", index_col=[0])
merged_alias_ap_collision_ensg_df

,ENSG_ID,gene_symbol,collision,source,NCBI_ID,HGNC_ID,alias_symbol
0,ENSG00000283293,RN7SK,7SK,ENSG,GENE ID:125050,HGNC:10037,7SK
1,ENSG00000057252,SOAT1,ACAT1,ENSG,GENE ID:6646,HGNC:11177,"ACAT,ACAT1,SOAT,STAT"
2,ENSG00000167780,SOAT2,ACAT2,ENSG,GENE ID:8435,HGNC:11178,ACAT2
3,ENSG00000004779,NDUFAB1,ACP1,ENSG,GENE ID:4706,HGNC:7694,"ACP,ACP1,FASN2A,SDAP"
4,ENSG00000220267,ACTBP8,ACTBP2,ENSG,NaN,HGNC:141,ACTBP2
...,...,...,...,...,...,...,...
806,ENSG00000197961,ZNF121,ZNF20,ENSG,GENE ID:7675,HGNC:12904,"D19S204,ZHC32,ZNF20"
807,ENSG00000110315,RNF141,ZNF230,ENSG,GENE ID:50862,HGNC:21159,"ZFP26,ZNF230"
808,ENSG00000188801,ZNF322P1,ZNF322,ENSG,NaN,HGNC:14003,"ZNF322,ZNF322B"
809,ENSG00000103994,ZNF106,ZNF474,ENSG,GENE ID:64397,HGNC:12886,"SH3BP3,ZFP106,ZNF474"
810,ENSG00000184517,ZFP1,ZNF475,ENSG,GENE ID:162239,HGNC:23328,"FLJ34243,ZNF475"

how many gene records are in the Ensembl database?

In [135]:
gene_record_set_ensg = set(mini_ensg_df['ENSG_ID'])
gene_record_count_ensg = len(gene_record_set_ensg)
gene_record_count_ensg

48401

how many unique primary gene symbols are in the Ensembl data set?

In [136]:
primary_symbol_set_ensg = set(mini_ensg_df['gene_symbol'])
primary_symbol_count_ensg = len(primary_symbol_set_ensg)
primary_symbol_count_ensg

41164

how many unique alias gene symbols are in the Ensembl data set?

In [137]:
alias_symbol_set_ensg = set(mini_ensg_df['alias_symbol'])
alias_symbol_count_ensg = len(alias_symbol_set_ensg)
alias_symbol_count_ensg

55413

how many unique gene symbols in total are there in the Ensembl data set??

In [138]:
total_symbol_count_ensg = pd.concat([mini_ensg_df["gene_symbol"], mini_ensg_df["alias_symbol"]]).dropna().nunique()
total_symbol_count_ensg

95941

how many gene records have no alias symbols?

In [139]:
no_alias_symbol_record_count_ensg = (
    mini_ensg_df[mini_ensg_df["alias_symbol"].isna()]
    .dropna(subset=["ENSG_ID"])
    ["ENSG_ID"]
    .nunique()
)
no_alias_symbol_record_count_ensg

19363

In [140]:
(no_alias_symbol_record_count_ensg/gene_record_count_ensg)*100

40.00537178983905

how many gene records have a primary gene symbol that is a C#orf?

In [141]:
orf_record_set_ensg = set(
    mini_ensg_df[
        mini_ensg_df["gene_symbol"].str.contains(r'^C.*ORF', case=False, na=False) &
        ~mini_ensg_df["gene_symbol"].str.contains("-", na=False)
    ]
    .dropna(subset=["ENSG_ID"])["ENSG_ID"]
)

orf_record_count_ensg = len(orf_record_set_ensg)
orf_record_count_ensg

288

In [142]:
(orf_record_count_ensg/gene_record_count_ensg)*100

0.595029028325861

how many gene records that have a primary gene symbol that is a FAM placeholder?

In [143]:
fam_record_set_ensg = set(
    mini_ensg_df[
        mini_ensg_df["gene_symbol"].str.startswith("FAM", na=False) &
        ~mini_ensg_df["gene_symbol"].str.contains("-", na=False)
    ]
    .dropna(subset=["ENSG_ID"])["ENSG_ID"]
)

fam_record_count_ensg = len(fam_record_set_ensg)
fam_record_count_ensg

430

In [144]:
(fam_record_count_ensg/gene_record_count_ensg)*100

0.8884113964587508

In [145]:
fam_record_set_ensg_df = mini_ensg_df[mini_ensg_df['ENSG_ID'].isin(fam_record_set_ensg)].copy()
fam_record_set_ensg_df['fam_family'] = fam_record_set_ensg_df['gene_symbol'].str.extract(r'^FAM(\d+)')
unique_families_count_ensg = fam_record_set_ensg_df['fam_family'].unique()
print("Number of unique FAM families in ENSG:", len(unique_families_count_ensg))

Number of unique FAM families in ENSG: 106

how many gene records that have a primary gene symbol that is a KIAA placeholder?

In [146]:
kiaa_record_set_ensg = set(
    mini_ensg_df[
        mini_ensg_df["gene_symbol"].str.startswith("KIAA", na=False) &
        ~mini_ensg_df["gene_symbol"].str.contains("-", na=False)
    ]
    .dropna(subset=["ENSG_ID"])["ENSG_ID"]
)

kiaa_record_count_ensg = len(kiaa_record_set_ensg)
kiaa_record_count_ensg

33

In [147]:
(kiaa_record_count_ensg/gene_record_count_ensg)*100

0.06818040949567158

which gene records share a primary symbol with other gene records?

In [148]:
# groupby name and return a boolean of whether each has more than 1 unique ENSG ID
multi_primary = mini_ensg_df.groupby(["gene_symbol"]).ENSG_ID.nunique().gt(1)

num_rows = mini_ensg_df[mini_ensg_df.gene_symbol.isin(multi_primary[multi_primary].index)].shape[0]
print(num_rows)

# use loc to only see those values that have `True` in `multi_primary`:
mini_ensg_df.loc[mini_ensg_df.gene_symbol.isin(multi_primary[multi_primary].index)].sort_values(by='gene_symbol').iloc[6000:6060]

25007

                ENSG_ID         NCBI_ID     HGNC_ID alias_symbol gene_symbol
92891   ENSG00000138641    GENE ID:8916   HGNC:4876     KIAA0032       HERC3
92878   ENSG00000287542    GENE ID:8916         NaN          NaN       HERC3
52117   ENSG00000273529  GENE ID:388585  HGNC:19764      BHLHB38        HES5
14696   ENSG00000197921  GENE ID:388585  HGNC:19764      BHLHB38        HES5
4416    ENSG00000280680   GENE ID:55733  HGNC:18270       MART-2        HHAT
4421    ENSG00000280680   GENE ID:55733  HGNC:18270          SKN        HHAT
4418    ENSG00000280680   GENE ID:55733  HGNC:18270         RASP        HHAT
4417    ENSG00000280680   GENE ID:55733  HGNC:18270        MART2        HHAT
43282   ENSG00000054392   GENE ID:55733  HGNC:18270        MART2        HHAT
43285   ENSG00000054392   GENE ID:55733  HGNC:18270          SKI        HHAT
4415    ENSG00000280680   GENE ID:55733  HGNC:18270         GUP2        HHAT
4414    ENSG00000280680   GENE ID:55733  HGNC:18270     FLJ10724        HHAT
4419    ENSG00000280680   GENE ID:55733  HGNC:18270          SIT        HHAT
43284   ENSG00000054392   GENE ID:55733  HGNC:18270          SIT        HHAT
43283   ENSG00000054392   GENE ID:55733  HGNC:18270         RASP        HHAT
43281   ENSG00000054392   GENE ID:55733  HGNC:18270       MART-2        HHAT
43280   ENSG00000054392   GENE ID:55733  HGNC:18270         GUP2        HHAT
43279   ENSG00000054392   GENE ID:55733  HGNC:18270     FLJ10724        HHAT
43286   ENSG00000054392   GENE ID:55733  HGNC:18270          SKN        HHAT
4420    ENSG00000280680   GENE ID:55733  HGNC:18270          SKI        HHAT
72820   ENSG00000235657    GENE ID:3105   HGNC:4931          NaN       HLA-A
68794   ENSG00000224320    GENE ID:3105   HGNC:4931          NaN       HLA-A
66867   ENSG00000227715    GENE ID:3105   HGNC:4931          NaN       HLA-A
76339   ENSG00000231834    GENE ID:3105   HGNC:4931          NaN       HLA-A
101068  ENSG00000206503    GENE ID:3105   HGNC:4931          NaN       HLA-A
67552   ENSG00000206505    GENE ID:3105   HGNC:4931          NaN       HLA-A
79893   ENSG00000223980    GENE ID:3105   HGNC:4931          NaN       HLA-A
66597   ENSG00000229215    GENE ID:3105   HGNC:4931          NaN       HLA-A
79909   ENSG00000224608    GENE ID:3106   HGNC:4932           AS       HLA-B
71168   ENSG00000234745    GENE ID:3106   HGNC:4932           AS       HLA-B
66216   ENSG00000206450    GENE ID:3106   HGNC:4932           AS       HLA-B
70494   ENSG00000232126    GENE ID:3106   HGNC:4932           AS       HLA-B
79186   ENSG00000223532    GENE ID:3106   HGNC:4932           AS       HLA-B
81469   ENSG00000228964    GENE ID:3106   HGNC:4932           AS       HLA-B
62689   ENSG00000204525    GENE ID:3107   HGNC:4933       D6S204       HLA-C
78388   ENSG00000228299    GENE ID:3107   HGNC:4933       PSORS1       HLA-C
78387   ENSG00000228299    GENE ID:3107   HGNC:4933      HLA-JY3       HLA-C
78774   ENSG00000233841    GENE ID:3107   HGNC:4933       PSORS1       HLA-C
76516   ENSG00000206452    GENE ID:3107   HGNC:4933      HLA-JY3       HLA-C
78386   ENSG00000228299    GENE ID:3107   HGNC:4933       D6S204       HLA-C
78773   ENSG00000233841    GENE ID:3107   HGNC:4933      HLA-JY3       HLA-C
70213   ENSG00000225691    GENE ID:3107   HGNC:4933       PSORS1       HLA-C
80918   ENSG00000206435    GENE ID:3107   HGNC:4933       PSORS1       HLA-C
76515   ENSG00000206452    GENE ID:3107   HGNC:4933       D6S204       HLA-C
80917   ENSG00000206435    GENE ID:3107   HGNC:4933      HLA-JY3       HLA-C
81311   ENSG00000237022    GENE ID:3107   HGNC:4933       PSORS1       HLA-C
81310   ENSG00000237022    GENE ID:3107   HGNC:4933      HLA-JY3       HLA-C
70211   ENSG00000225691    GENE ID:3107   HGNC:4933       D6S204       HLA-C
76517   ENSG00000206452    GENE ID:3107   HGNC:4933       PSORS1       HLA-C
80916   ENSG00000206435    GENE ID:3107   HGNC:4933       D6S204       HLA-C
62691   ENSG00000204525    GENE ID:3107   HGNC:4933       PSORS1       HLA-C
70212   ENSG00000225691    GENE ID:3107   HGNC:4933      HLA-JY3       HLA-C
62690   ENSG00000204525    GENE ID:3107   HGNC:4933      HLA-JY3       HLA-C
81309   ENSG00000237022    GENE ID:3107   HGNC:4933       D6S204       HLA-C
78772   ENSG00000233841    GENE ID:3107   HGNC:4933       D6S204       HLA-C
76137   ENSG00000242685    GENE ID:3108   HGNC:4934      D6S222E     HLA-DMA
75324   ENSG00000243189    GENE ID:3108   HGNC:4934      D6S222E     HLA-DMA
83537   ENSG00000243215    GENE ID:3108   HGNC:4934      D6S222E     HLA-DMA
74916   ENSG00000243719    GENE ID:3108   HGNC:4934      D6S222E     HLA-DMA
75325   ENSG00000243189    GENE ID:3108   HGNC:4934        RING6     HLA-DMA

How many ambiguous symbols result from alias-primary collisions?

In [149]:
ap_collision_ambiguous_symbol_set_ensg = set(merged_alias_ap_collision_ensg_df["collision"])
ap_collision_ambiguous_symbol_count_ensg = len(ap_collision_ambiguous_symbol_set_ensg)
ap_collision_ambiguous_symbol_count_ensg

606

How many records have at least one alias-primary collision (alias that matches another record's primary gene symbol)?

In [150]:
ap_record_set_ensg = set(merged_alias_ap_collision_ensg_df["ENSG_ID"])
ap_record_count_ensg = len(ap_record_set_ensg)
ap_record_count_ensg

767

1. Why is the alias-gene collision set not the same length as the set of primary symbols with collisions ?
2. Why is the length of the alias-gene collison set shorter?
 - A gene record with an alias-primary collision has an alias that matches a different gene's primary gene symbol.
 - Multiple gene records can share a single alias (alias-alias collision)
 - If that shared alias is an alias-primary collision, then there will be more unique gene symbols in the set of primary symbols with collisions than the set of alias-primary collisions.

# HGNC

In [151]:
raw_hgnc_df = pd.read_csv("../output/raw_hgnc_df.csv")
raw_hgnc_df

          HGNC_ID gene_symbol alias_symbol       NCBI_ID          ENSG_ID
0        HGNC:100       ASIC1        BNaC2    GENE ID:41  ENSG00000110881
1        HGNC:100       ASIC1       hBNaC2    GENE ID:41  ENSG00000110881
2      HGNC:10000        RGS4          NaN  GENE ID:5999  ENSG00000117152
3      HGNC:10001        RGS5          NaN  GENE ID:8490  ENSG00000143248
4      HGNC:10002        RGS6          NaN  GENE ID:9628  ENSG00000182732
...           ...         ...          ...           ...              ...
66202   HGNC:9997       RGS16        RGS-r  GENE ID:6004  ENSG00000143333
66203   HGNC:9998        RGS2          NaN  GENE ID:5997  ENSG00000116741
66204   HGNC:9999        RGS3         C2PA  GENE ID:5998  ENSG00000138835
66205   HGNC:9999        RGS3     FLJ20370  GENE ID:5998  ENSG00000138835
66206   HGNC:9999        RGS3     PDZ-RGS3  GENE ID:5998  ENSG00000138835

[66207 rows x 5 columns]

how many gene records for the HGNC data set before any kind of cleaning?

In [152]:
total_raw_gene_record_set_hgnc = set(raw_hgnc_df['HGNC_ID'])
total_raw_gene_record_count_hgnc = len(total_raw_gene_record_set_hgnc)
total_raw_gene_record_count_hgnc

44235

how many gene records have no primary gene symbol?

In [153]:
raw_no_primary_symbol_record_count_hgnc = (
    raw_hgnc_df[raw_hgnc_df["gene_symbol"].isna()]
    .dropna(subset=["HGNC_ID"])
    ["HGNC_ID"]
    .nunique()
)
raw_no_primary_symbol_record_count_hgnc

0

how many gene records that have a primary gene symbol that is a LOC placeholder?

In [154]:
raw_loc_record_count_hgnc = (
    raw_hgnc_df[raw_hgnc_df["gene_symbol"].str.startswith('LOC', na=False)&
    ~raw_hgnc_df['gene_symbol']
    .str.contains('-', na=False)]
    .dropna(subset=["HGNC_ID"])
    ["HGNC_ID"]
    .nunique()
)
raw_loc_record_count_hgnc

0

how many records with an @ symbol in the primary gene symbol?

In [155]:
at_symbol_records_hgnc_df = raw_hgnc_df[raw_hgnc_df['gene_symbol'].str.contains('@', na=False)]
len(set(at_symbol_records_hgnc_df["HGNC_ID"]))

7

In [156]:
no_at_hgnc_df = raw_hgnc_df[~raw_hgnc_df['HGNC_ID'].isin(at_symbol_records_hgnc_df['HGNC_ID'])]

In [157]:
create_ap_collision_df(no_at_hgnc_df, "HGNC")

All collisions are present in gene alias lists.

      HGNC_ID gene_symbol alias_symbol       NCBI_ID          ENSG_ID
0    HGNC:100       ASIC1        BNaC2    GENE ID:41  ENSG00000110881
1    HGNC:100       ASIC1       hBNaC2    GENE ID:41  ENSG00000110881
2  HGNC:10000        RGS4          NaN  GENE ID:5999  ENSG00000117152
3  HGNC:10001        RGS5          NaN  GENE ID:8490  ENSG00000143248
4  HGNC:10002        RGS6          NaN  GENE ID:9628  ENSG00000182732

In [158]:
mini_hgnc_df = pd.read_csv(
    "../output/mini_hgnc_df.csv", index_col=[0])

In [159]:
subset_genes_hgnc_df = pd.read_csv(
    "../output/subset_genes_hgnc_df.csv", index_col=[0])
subset_genes_hgnc_df

          HGNC_ID gene_symbol alias_symbol       NCBI_ID          ENSG_ID
0        HGNC:100       ASIC1        BNaC2    GENE ID:41  ENSG00000110881
1        HGNC:100       ASIC1       hBNaC2    GENE ID:41  ENSG00000110881
2      HGNC:10000        RGS4          NaN  GENE ID:5999  ENSG00000117152
3      HGNC:10001        RGS5          NaN  GENE ID:8490  ENSG00000143248
4      HGNC:10002        RGS6          NaN  GENE ID:9628  ENSG00000182732
...           ...         ...          ...           ...              ...
66202   HGNC:9997       RGS16        RGS-r  GENE ID:6004  ENSG00000143333
66203   HGNC:9998        RGS2          NaN  GENE ID:5997  ENSG00000116741
66204   HGNC:9999        RGS3         C2PA  GENE ID:5998  ENSG00000138835
66205   HGNC:9999        RGS3     FLJ20370  GENE ID:5998  ENSG00000138835
66206   HGNC:9999        RGS3     PDZ-RGS3  GENE ID:5998  ENSG00000138835

[66199 rows x 5 columns]

In [160]:
merged_alias_ap_collision_hgnc_df = pd.read_csv(
    "../output/merged_alias_ap_collision_hgnc_df.csv", index_col=[0])
merged_alias_ap_collision_hgnc_df

,HGNC_ID,gene_symbol,collision,source,NCBI_ID,ENSG_ID,alias_symbol
0,HGNC:14947,PPP1R12C,AAVS1,HGNC,GENE ID:54776,ENSG00000125503,"AAVS1,DKFZP434D0412,MBS85,p84,p85"
1,HGNC:11177,SOAT1,ACAT1,HGNC,GENE ID:6646,ENSG00000057252,"ACAT,ACAT1"
2,HGNC:11178,SOAT2,ACAT2,HGNC,GENE ID:8435,ENSG00000167780,ACAT2
3,HGNC:1612,CCRL2,ACKR5,HGNC,GENE ID:9034,ENSG00000121797,"ACKR5,CKRX,CRAM-A,CRAM-B,HCR"
4,HGNC:7694,NDUFAB1,ACP1,HGNC,GENE ID:4706,ENSG00000004779,"ACP,ACP1,FASN2A,SDAP"
...,...,...,...,...,...,...,...
555,HGNC:3147,ECEL1,XCE,HGNC,GENE ID:9427,ENSG00000171551,"DINE,XCE"
556,HGNC:12904,ZNF121,ZNF20,HGNC,GENE ID:7675,ENSG00000197961,"ZHC32,ZNF20"
557,HGNC:21159,RNF141,ZNF230,HGNC,GENE ID:50862,ENSG00000110315,"ZFP26,ZNF230"
558,HGNC:12886,ZNF106,ZNF474,HGNC,GENE ID:64397,ENSG00000103994,"SH3BP3,ZNF474"
559,HGNC:23328,ZFP1,ZNF475,HGNC,GENE ID:162239,ENSG00000184517,"FLJ34243,ZNF475"

how many gene records are in the HGNC database?

In [161]:
gene_record_set_hgnc = set(mini_hgnc_df['HGNC_ID'])
gene_record_count_hgnc = len(gene_record_set_hgnc)
gene_record_count_hgnc

44228

how many unique primary gene symbols are in the HGNC data set?

In [162]:
primary_symbol_set_hgnc = set(mini_hgnc_df['gene_symbol'])
primary_symbol_count_hgnc = len(primary_symbol_set_hgnc)
primary_symbol_count_hgnc

44228

how many unique alias gene symbols are in the HGNC data set?

In [163]:
alias_symbol_set_hgnc = set(mini_hgnc_df['alias_symbol'])
alias_symbol_count_hgnc = len(alias_symbol_set_hgnc)
alias_symbol_count_hgnc

43072

how many unique gene symbols in total are there in the HGNC data set??

In [164]:
total_symbol_count_hgnc = len(set(mini_hgnc_df['gene_symbol']) | set(mini_hgnc_df['alias_symbol']))
total_symbol_count_hgnc

86832

how many gene records have no alias symbols?

In [165]:
no_alias_symbol_record_count_hgnc = (
    mini_hgnc_df[mini_hgnc_df["alias_symbol"].isna()]
    .dropna(subset=["HGNC_ID"])
    ["HGNC_ID"]
    .nunique()
)
no_alias_symbol_record_count_hgnc

21764

In [166]:
(no_alias_symbol_record_count_hgnc/gene_record_count_ensg)*100

44.96601309890291

how many gene records have a primary gene symbol that is a C#orf?

In [167]:
orf_record_set_hgnc = set(
    mini_hgnc_df[
        mini_hgnc_df["gene_symbol"].str.contains(r'^C.*ORF', case=False, na=False) &
        ~mini_hgnc_df["gene_symbol"].str.contains("-", na=False)
    ]
    .dropna(subset=["HGNC_ID"])["HGNC_ID"]
)

orf_record_count_hgnc = len(orf_record_set_hgnc)
orf_record_count_hgnc

246

In [168]:
(orf_record_count_hgnc/gene_record_count_ensg)*100

0.5082539616950063

how many gene records that have a primary gene symbol that is a FAM placeholder?

In [169]:
fam_record_set_hgnc = set(
    mini_hgnc_df[mini_hgnc_df["gene_symbol"].str.startswith('FAM', na=False)&
    ~mini_hgnc_df['gene_symbol']
    .str.contains('-', na=False)]
    .dropna(subset=["HGNC_ID"])
    ["HGNC_ID"]
)
fam_record_count_hgnc = len(fam_record_set_hgnc)
fam_record_count_hgnc

371

In [170]:
(fam_record_count_hgnc/gene_record_count_ensg)*100

0.7665130885725502

In [171]:
fam_record_set_hgnc_df = mini_hgnc_df[mini_hgnc_df['HGNC_ID'].isin(fam_record_set_hgnc)].copy()
fam_record_set_hgnc_df['fam_family'] = fam_record_set_hgnc_df['gene_symbol'].str.extract(r'^FAM(\d+)')
unique_families_count_hgnc = fam_record_set_hgnc_df['fam_family'].unique()
print("Number of unique FAM families in HGNC:", len(unique_families_count_hgnc))

Number of unique FAM families in HGNC: 107

how many gene records that have a primary gene symbol that is a KIAA placeholder?

In [172]:
kiaa_record_set_hgnc = set(
    mini_hgnc_df[mini_hgnc_df["gene_symbol"].str.startswith('KIAA', na=False)&
    ~mini_hgnc_df['gene_symbol']
    .str.contains('-', na=False)]
    .dropna(subset=["HGNC_ID"])
    ["HGNC_ID"]
)
kiaa_record_count_hgnc = len(kiaa_record_set_hgnc)
kiaa_record_count_hgnc

32

In [173]:
(kiaa_record_count_hgnc/gene_record_count_ensg)*100

0.06611433648065122

which gene records share a primary symbol with other gene records?

In [174]:
# groupby name and return a boolean of whether each has more than 1 unique Country
multi_primary = mini_hgnc_df.groupby(["gene_symbol"]).HGNC_ID.nunique().gt(1)

num_rows = mini_hgnc_df[mini_hgnc_df.gene_symbol.isin(multi_primary[multi_primary].index)].shape[0]
print(num_rows)

# use loc to only see those values that have `True` in `multi_country`:
multi_record_same_symbol_df = mini_hgnc_df.loc[mini_hgnc_df.gene_symbol.isin(multi_primary[multi_primary].index)].sort_values(by='gene_symbol')
multi_record_same_symbol_df.head(60)

0

Empty DataFrame
Columns: [HGNC_ID, gene_symbol, alias_symbol, NCBI_ID, ENSG_ID]
Index: []

How many ambiguous symbols result from alias-primary collisions?

In [175]:
ap_collision_ambiguous_symbol_set_hgnc = set(
    merged_alias_ap_collision_hgnc_df["collision"]
)
ap_collision_ambiguous_symbol_count_hgnc = len(ap_collision_ambiguous_symbol_set_hgnc)
ap_collision_ambiguous_symbol_count_hgnc

492

How many records have at least one alias-primary collision (alias that matches another record's primary gene symbol)?

In [176]:
ap_record_set_hgnc = set(merged_alias_ap_collision_hgnc_df["HGNC_ID"])
ap_record_count_hgnc = len(ap_record_set_hgnc)
ap_record_count_hgnc

546

# NCBI Gene

In [177]:
raw_ncbi_df = pd.read_csv("../output/raw_ncbi_df.csv")
raw_ncbi_df

,NCBI_ID,gene_symbol,alias_symbol,gene_type,HGNC_ID,ENSG_ID
0,GENE ID:1,A1BG,A1B,protein-coding,HGNC:5,ENSG00000121410
1,GENE ID:1,A1BG,ABG,protein-coding,HGNC:5,ENSG00000121410
2,GENE ID:1,A1BG,GAB,protein-coding,HGNC:5,ENSG00000121410
3,GENE ID:1,A1BG,HYST2477,protein-coding,HGNC:5,ENSG00000121410
4,GENE ID:2,A2M,A2MD,protein-coding,HGNC:7,ENSG00000175899
...,...,...,...,...,...,...
240503,GENE ID:8923215,trnD,NaN,tRNA,NaN,NaN
240504,GENE ID:8923216,trnP,NaN,tRNA,NaN,NaN
240505,GENE ID:8923217,trnA,NaN,tRNA,NaN,NaN
240506,GENE ID:8923218,COX1,NaN,protein-coding,NaN,NaN
240507,GENE ID:8923219,16S rRNA,NaN,rRNA,NaN,NaN

In [178]:
raw_ncbi_df = raw_ncbi_df.drop(["gene_type"], axis=1)

how many gene records for the NCBI data set before any kind of cleaning?

In [179]:
total_raw_gene_record_set_ncbi = set(raw_ncbi_df['NCBI_ID'])
total_raw_gene_record_count_ncbi = len(total_raw_gene_record_set_ncbi)
total_raw_gene_record_count_ncbi

193580

how many gene records have the "phenotype only" property?

In [180]:
# This file (ncbi_records_w_property_pheno_only_20250630.txt) was generated through the NCBI Gene web page by 
# searching for these parameters "phenotype only [Properties] AND "Homo sapiens"[porgn:__txid9606]"
ncbi_pheno_records_df = pd.read_csv("../input/ncbi_records_w_property_pheno_only_20250630.txt", sep="\t")

ncbi_pheno_records_df = ncbi_pheno_records_df.rename(
    columns={"GeneID": "NCBI_ID", "Symbol": "gene_symbol", "Aliases": "alias_symbol"})

ncbi_pheno_records_df["NCBI_ID"] = ncbi_pheno_records_df["NCBI_ID"].apply(
lambda x: f"GENE ID:{int(x)}" if pd.notna(x) and x == int(x) else f"GENE ID:{x}" if pd.notna(x) else x
)

In [181]:
ncbi_pheno_records_df.loc[ncbi_pheno_records_df["gene_symbol"].str.startswith('LOC', na=False)]

,tax_id,Org_name,NCBI_ID,CurrentID,Status,gene_symbol,alias_symbol,description,other_designations,map_location,chromosome,genomic_nucleotide_accession.version,start_position_on_the_genomic_accession,end_position_on_the_genomic_accession,orientation,exon_count,OMIM,Unnamed: 17
170,9606,Homo sapiens,GENE ID:7795,0,live,LOC7795,MEMO1,Methylation modifier for class I HLA,NaN,1p36.1-p35,1,NaN,NaN,NaN,NaN,NaN,601201.0,NaN
1096,9606,Homo sapiens,GENE ID:619539,0,live,LOC619539,NaN,"lentiginosis, inherited patterned",familial generalized lentiginosis,4q21.1-q22.3,4,NaN,NaN,NaN,NaN,NaN,151001.0,NaN

In [182]:
# need to drop them
no_pheno_ncbi_df = raw_ncbi_df[~raw_ncbi_df['NCBI_ID'].isin(ncbi_pheno_records_df['NCBI_ID'])]

how many gene records have no primary gene symbol?

In [183]:
raw_no_primary_symbol_record_count_ncbi = (
    raw_ncbi_df[raw_ncbi_df["gene_symbol"].isna()]
    .dropna(subset=["NCBI_ID"])
    ["NCBI_ID"]
    .nunique()
)
raw_no_primary_symbol_record_count_ncbi

0

In [184]:
(raw_no_primary_symbol_record_count_ncbi/total_raw_gene_record_count_ncbi)*100

0.0

how many gene records that have a primary gene symbol that is a LOC placeholder?

In [185]:
raw_loc_record_count_ncbi = (
    raw_ncbi_df[raw_ncbi_df["gene_symbol"].str.startswith('LOC', na=False)&
    ~raw_ncbi_df['gene_symbol']
    .str.contains('-', na=False)]
    .dropna(subset=["NCBI_ID"])
    ["NCBI_ID"]
    .nunique()
)
raw_loc_record_count_ncbi

147700

In [186]:
no_pheno_loc_ncbi_df = no_pheno_ncbi_df[~no_pheno_ncbi_df['gene_symbol'].str.startswith('LOC', na=False)]

In [187]:
len(set(no_pheno_loc_ncbi_df["NCBI_ID"]))

44712

how many gene records are sub species records: "homo sapiens ssp denisova"[Organism]

In [188]:
ncbi_denisova_records_df = pd.read_csv("../input/ncbi_denisova_20250630.txt", sep="\t")

ncbi_denisova_records_df = ncbi_denisova_records_df.rename(
    columns={"GeneID": "NCBI_ID", "Symbol": "gene_symbol", "Aliases": "alias_symbol"})

ncbi_denisova_records_df["NCBI_ID"] = ncbi_denisova_records_df["NCBI_ID"].apply(
lambda x: f"GENE ID:{int(x)}" if pd.notna(x) and x == int(x) else f"GENE ID:{x}" if pd.notna(x) else x
)

In [189]:
len(set(ncbi_denisova_records_df["NCBI_ID"]))

36

In [190]:
no_pheno_loc_denisova_ncbi_df = no_pheno_loc_ncbi_df[~no_pheno_loc_ncbi_df['NCBI_ID'].isin(ncbi_denisova_records_df['NCBI_ID'])]

In [191]:
len(set(no_pheno_loc_denisova_ncbi_df["NCBI_ID"]))

44676

Drop sub species records: "homo sapiens neanderthalensis"[Organism]

In [192]:
ncbi_neanderthalensis_records_df = pd.read_csv("../input/ncbi_neanderthalensis_20250630.txt", sep="\t")

ncbi_neanderthalensis_records_df = ncbi_neanderthalensis_records_df.rename(
    columns={"GeneID": "NCBI_ID", "Symbol": "gene_symbol", "Aliases": "alias_symbol"})

ncbi_neanderthalensis_records_df["NCBI_ID"] = ncbi_neanderthalensis_records_df["NCBI_ID"].apply(
lambda x: f"GENE ID:{int(x)}" if pd.notna(x) and x == int(x) else f"GENE ID:{x}" if pd.notna(x) else x
)

In [193]:
len(set(ncbi_neanderthalensis_records_df["NCBI_ID"]))

37

In [194]:
no_pheno_loc_denisova_neanderthalis_ncbi_df = no_pheno_loc_denisova_ncbi_df[~no_pheno_loc_denisova_ncbi_df['NCBI_ID'].isin(ncbi_neanderthalensis_records_df['NCBI_ID'])]

how many records with an @ symbol in the primary gene symbol?

In [195]:
at_symbol_records_ncbi_df = no_pheno_loc_denisova_neanderthalis_ncbi_df[no_pheno_loc_denisova_neanderthalis_ncbi_df['gene_symbol'].str.contains('@', na=False)]
len(set(at_symbol_records_ncbi_df["NCBI_ID"]))

11

In [196]:
len(set(no_pheno_loc_denisova_neanderthalis_ncbi_df["NCBI_ID"]))

44639

In [197]:
no_pheno_loc_denisova_neanderthalis_at_ncbi_df = no_pheno_loc_denisova_neanderthalis_ncbi_df[~no_pheno_loc_denisova_neanderthalis_ncbi_df['NCBI_ID'].isin(at_symbol_records_ncbi_df['NCBI_ID'])]

In [198]:
len(set(no_pheno_loc_denisova_neanderthalis_at_ncbi_df["NCBI_ID"]))

44628

In [199]:
create_ap_collision_df(no_pheno_loc_denisova_neanderthalis_at_ncbi_df, "NCBI")

All collisions are present in gene alias lists.

     NCBI_ID gene_symbol alias_symbol HGNC_ID          ENSG_ID
0  GENE ID:1        A1BG          A1B  HGNC:5  ENSG00000121410
1  GENE ID:1        A1BG          ABG  HGNC:5  ENSG00000121410
2  GENE ID:1        A1BG          GAB  HGNC:5  ENSG00000121410
3  GENE ID:1        A1BG     HYST2477  HGNC:5  ENSG00000121410
4  GENE ID:2         A2M         A2MD  HGNC:7  ENSG00000175899

In [200]:
mini_ncbi_df = pd.read_csv(
    "../output/mini_ncbi_df.csv", index_col=[0])

In [201]:
subset_genes_ncbi_df = pd.read_csv(
    "../output/subset_genes_ncbi_df.csv", index_col=[0])
subset_genes_ncbi_df

,NCBI_ID,gene_symbol,alias_symbol,HGNC_ID,ENSG_ID
0,GENE ID:1,A1BG,A1B,HGNC:5,ENSG00000121410
1,GENE ID:1,A1BG,ABG,HGNC:5,ENSG00000121410
2,GENE ID:1,A1BG,GAB,HGNC:5,ENSG00000121410
3,GENE ID:1,A1BG,HYST2477,HGNC:5,ENSG00000121410
4,GENE ID:2,A2M,A2MD,HGNC:7,ENSG00000175899
...,...,...,...,...,...
240430,GENE ID:141732005,ADCY2-AS1,NaN,HGNC:40064,NaN
240431,GENE ID:141732006,NSG2-AS1,NaN,HGNC:41074,NaN
240432,GENE ID:141732007,ST18-AS1,NaN,HGNC:58430,NaN
240433,GENE ID:141732008,MICAL2-AS1,NaN,HGNC:58437,NaN
240434,GENE ID:141732009,TRIM41-AS1,NaN,HGNC:40863,NaN

In [202]:
merged_alias_ap_collision_ncbi_df = pd.read_csv(
    "../output/merged_alias_ap_collision_ncbi_df.csv", index_col=[0])
merged_alias_ap_collision_ncbi_df

,NCBI_ID,gene_symbol,collision,source,HGNC_ID,ENSG_ID,alias_symbol
0,GENE ID:3494,IGHA2,A2M,NCBI,HGNC:5479,ENSG00000211890,A2M
1,GENE ID:54776,PPP1R12C,AAVS1,NCBI,HGNC:14947,ENSG00000125503,"AAVS1,LENG3,MBS85,p84,p85"
2,GENE ID:6646,SOAT1,ACAT1,NCBI,HGNC:11177,ENSG00000057252,"ACACT,ACAT,ACAT-1,ACAT1,SOAT,STAT"
3,GENE ID:8435,SOAT2,ACAT2,NCBI,HGNC:11178,ENSG00000167780,"ACACT2,ACAT2,ARGP2"
4,GENE ID:9034,CCRL2,ACKR5,NCBI,HGNC:1612,ENSG00000121797,"ACKR5,CKRX,CRAM,CRAM-A,CRAM-B,HCR"
...,...,...,...,...,...,...,...
2031,GENE ID:29903,CCDC106,ZNF581,NCBI,HGNC:30181,ENSG00000173581,"HSU79303,ZNF581"
2032,GENE ID:146540,ZNF785,ZNF688,NCBI,HGNC:26496,ENSG00000197162,ZNF688
2033,GENE ID:57829,ZP4,ZP1,NCBI,HGNC:15770,ENSG00000116996,"ZBP,ZP1,ZP1B,ZPB,ZPB2,Zp-4"
2035,GENE ID:55663,ZNF446,ZSCAN30,NCBI,HGNC:21036,ENSG00000083838,"ZKSCAN20,ZSCAN30,ZSCAN52"
2036,GENE ID:342357,ZKSCAN2,ZSCAN31,NCBI,HGNC:25677,ENSG00000155592,"ZNF694,ZSCAN31,ZSCAN34"

how many gene records are in the NCBI database?

In [203]:
gene_record_set_ncbi = set(mini_ncbi_df['NCBI_ID'])
gene_record_count_ncbi = len(gene_record_set_ncbi)
gene_record_count_ncbi

44628

how many unique primary gene symbols are in the NCBI data set?

In [204]:
primary_symbol_set_ncbi = set(mini_ncbi_df['gene_symbol'])
primary_symbol_count_ncbi = len(primary_symbol_set_ncbi)
primary_symbol_count_ncbi

44530

how many unique alias gene symbols are in the NCBI data set?

In [205]:
alias_symbol_set_ncbi = set(mini_ncbi_df['alias_symbol'])
alias_symbol_count_ncbi = len(alias_symbol_set_ncbi)
alias_symbol_count_ncbi

69210

how many unique gene symbols in total are there in the NCBI data set??

In [206]:
total_symbol_count_ncbi = pd.concat([mini_ncbi_df["gene_symbol"], mini_ncbi_df["alias_symbol"]]).dropna().nunique()
total_symbol_count_ncbi

112266

how many gene records have no alias symbols?

In [207]:
no_alias_symbol_record_count_ncbi = (
    mini_ncbi_df[mini_ncbi_df["alias_symbol"].isna()]
    .dropna(subset=["NCBI_ID"])
    ["NCBI_ID"]
    .nunique()
)
no_alias_symbol_record_count_ncbi

17380

In [208]:
(no_alias_symbol_record_count_ncbi/gene_record_count_ncbi)*100

38.94416061665322

how many gene records have a primary gene symbol that is a C#orf?

In [209]:
orf_record_set_ncbi = set(mini_ncbi_df[
    mini_ncbi_df['gene_symbol']
    .str.contains(r'^C.*ORF', case=False, na=False) &
    ~mini_ncbi_df['gene_symbol']
    .str.contains('-', na=False)
])
orf_record_count_ncbi = len(orf_record_set_ncbi)
orf_record_count_ncbi

5

In [210]:
(orf_record_count_ncbi/gene_record_count_ncbi)*100

0.011203728600878373

how many gene records that have a primary gene symbol that is a FAM placeholder?

In [211]:
fam_record_set_ncbi = set(
    mini_ncbi_df[mini_ncbi_df["gene_symbol"].str.startswith('FAM', na=False)&
    ~mini_ncbi_df['gene_symbol']
    .str.contains('-', na=False)]
    .dropna(subset=["NCBI_ID"])
    ["NCBI_ID"]
)
fam_record_count_ncbi = len(fam_record_set_ncbi)
fam_record_count_ncbi

371

In [212]:
(fam_record_count_ncbi/gene_record_count_ncbi)*100

0.8313166621851753

In [213]:
fam_record_set_ncbi_df = mini_ncbi_df[mini_ncbi_df['NCBI_ID'].isin(fam_record_set_ncbi)].copy()
fam_record_set_ncbi_df['fam_family'] = fam_record_set_ncbi_df['gene_symbol'].str.extract(r'^FAM(\d+)')
unique_families_count_ncbi = fam_record_set_ncbi_df['fam_family'].unique()
print("Number of unique FAM families in NCBI:", len(unique_families_count_ncbi))

Number of unique FAM families in NCBI: 107

how many gene records that have a primary gene symbol that is a KIAA placeholder?

In [214]:
kiaa_record_set_ncbi = set(
    mini_ncbi_df[mini_ncbi_df["gene_symbol"].str.startswith('KIAA', na=False)&
    ~mini_ncbi_df['gene_symbol']
    .str.contains('-', na=False)]
    .dropna(subset=["NCBI_ID"])
    ["NCBI_ID"]
)
kiaa_record_count_ncbi = len(kiaa_record_set_ncbi)
kiaa_record_count_ncbi

33

In [215]:
(kiaa_record_count_ncbi/gene_record_count_ncbi)*100

0.07394460876579727

which gene records share a primary symbol with other gene records?

In [216]:
# groupby name and return a boolean of whether each has more than 1 unique Country
multi_primary = mini_ncbi_df.groupby(["gene_symbol"]).NCBI_ID.nunique().gt(1)

num_rows = mini_ncbi_df[mini_ncbi_df.gene_symbol.isin(multi_primary[multi_primary].index)].shape[0]
print(num_rows)

# use loc to only see those values that have `True` in `multi_country`:
multi_record_same_symbol_df = mini_ncbi_df.loc[mini_ncbi_df.gene_symbol.isin(multi_primary[multi_primary].index)].sort_values(by='gene_symbol')
multi_record_same_symbol_df.head(60)

110

                  NCBI_ID gene_symbol alias_symbol     HGNC_ID ENSG_ID
13023        GENE ID:4549        RNR1       MTRNR1   HGNC:7470     NaN
17494        GENE ID:6052        RNR1          NaN  HGNC:10082     NaN
13024        GENE ID:4550        RNR2       MTRNR2   HGNC:7471     NaN
17495        GENE ID:6053        RNR2          NaN  HGNC:10083     NaN
112802  GENE ID:124901565   TRNAA-AGC          NaN         NaN     NaN
112801  GENE ID:124901564   TRNAA-AGC          NaN         NaN     NaN
112800  GENE ID:124901563   TRNAA-AGC          NaN         NaN     NaN
112799  GENE ID:124901562   TRNAA-AGC          NaN         NaN     NaN
117694  GENE ID:124906586   TRNAA-AGC          NaN         NaN     NaN
112798  GENE ID:124901561   TRNAA-AGC          NaN         NaN     NaN
117026  GENE ID:124905878   TRNAD-GUC          NaN         NaN     NaN
117014  GENE ID:124905866   TRNAD-GUC          NaN         NaN     NaN
117011  GENE ID:124905863   TRNAD-GUC          NaN         NaN     NaN
117020  GENE ID:124905872   TRNAD-GUC          NaN         NaN     NaN
117008  GENE ID:124905860   TRNAD-GUC          NaN         NaN     NaN
117005  GENE ID:124905857   TRNAD-GUC          NaN         NaN     NaN
117023  GENE ID:124905875   TRNAD-GUC          NaN         NaN     NaN
117002  GENE ID:124905854   TRNAD-GUC          NaN         NaN     NaN
117029  GENE ID:124905881   TRNAD-GUC          NaN         NaN     NaN
117032  GENE ID:124905884   TRNAD-GUC          NaN         NaN     NaN
117035  GENE ID:124905887   TRNAD-GUC          NaN         NaN     NaN
117017  GENE ID:124905869   TRNAD-GUC          NaN         NaN     NaN
117038  GENE ID:124905890   TRNAD-GUC          NaN         NaN     NaN
117050  GENE ID:124905902   TRNAD-GUC          NaN         NaN     NaN
117044  GENE ID:124905896   TRNAD-GUC          NaN         NaN     NaN
117047  GENE ID:124905899   TRNAD-GUC          NaN         NaN     NaN
117041  GENE ID:124905893   TRNAD-GUC          NaN         NaN     NaN
117015  GENE ID:124905867   TRNAE-CUC          NaN         NaN     NaN
117018  GENE ID:124905870   TRNAE-CUC          NaN         NaN     NaN
117012  GENE ID:124905864   TRNAE-CUC          NaN         NaN     NaN
117051  GENE ID:124905903   TRNAE-CUC          NaN         NaN     NaN
117033  GENE ID:124905885   TRNAE-CUC          NaN         NaN     NaN
117009  GENE ID:124905861   TRNAE-CUC          NaN         NaN     NaN
117048  GENE ID:124905900   TRNAE-CUC          NaN         NaN     NaN
117021  GENE ID:124905873   TRNAE-CUC          NaN         NaN     NaN
117036  GENE ID:124905888   TRNAE-CUC          NaN         NaN     NaN
117045  GENE ID:124905897   TRNAE-CUC          NaN         NaN     NaN
117003  GENE ID:124905855   TRNAE-CUC          NaN         NaN     NaN
117039  GENE ID:124905891   TRNAE-CUC          NaN         NaN     NaN
117024  GENE ID:124905876   TRNAE-CUC          NaN         NaN     NaN
117027  GENE ID:124905879   TRNAE-CUC          NaN         NaN     NaN
117042  GENE ID:124905894   TRNAE-CUC          NaN         NaN     NaN
117006  GENE ID:124905858   TRNAE-CUC          NaN         NaN     NaN
117030  GENE ID:124905882   TRNAE-CUC          NaN         NaN     NaN
117056  GENE ID:124905908   TRNAE-UUC          NaN         NaN     NaN
101121  GENE ID:107987368   TRNAE-UUC          NaN         NaN     NaN
116769  GENE ID:124905580   TRNAE-UUC          NaN         NaN     NaN
116772  GENE ID:124905583   TRNAE-UUC          NaN         NaN     NaN
116773  GENE ID:124905584   TRNAE-UUC          NaN         NaN     NaN
116775  GENE ID:124905586   TRNAE-UUC          NaN         NaN     NaN
116770  GENE ID:124905581   TRNAG-CCC          NaN         NaN     NaN
116767  GENE ID:124905578   TRNAG-CCC          NaN         NaN     NaN
116777  GENE ID:124905588   TRNAG-CCC          NaN         NaN     NaN
117055  GENE ID:124905907   TRNAG-GCC          NaN         NaN     NaN
117058  GENE ID:124905910   TRNAG-GCC          NaN         NaN     NaN
116995  GENE ID:124905847   TRNAG-GCC          NaN         NaN     NaN
117060  GENE ID:124905912   TRNAG-GCC          NaN         NaN     NaN
117062  GENE ID:124905914   TRNAG-GCC          NaN         NaN     NaN
116997  GENE ID:124905849   TRNAG-GCC          NaN         NaN     NaN
117064  GENE ID:124905916   TRNAG-GCC          NaN         NaN     NaN

In [217]:
multi_record_same_symbol_df.iloc[60:110]

                  NCBI_ID gene_symbol alias_symbol HGNC_ID ENSG_ID
117066  GENE ID:124905918   TRNAG-GCC          NaN     NaN     NaN
117069  GENE ID:124905921   TRNAG-GCC          NaN     NaN     NaN
117071  GENE ID:124905923   TRNAG-GCC          NaN     NaN     NaN
117001  GENE ID:124905853   TRNAG-GCC          NaN     NaN     NaN
117073  GENE ID:124905925   TRNAG-GCC          NaN     NaN     NaN
117075  GENE ID:124905927   TRNAG-GCC          NaN     NaN     NaN
117077  GENE ID:124905929   TRNAG-GCC          NaN     NaN     NaN
117079  GENE ID:124905931   TRNAG-GCC          NaN     NaN     NaN
117081  GENE ID:124905933   TRNAG-GCC          NaN     NaN     NaN
116999  GENE ID:124905851   TRNAG-GCC          NaN     NaN     NaN
117046  GENE ID:124905898   TRNAG-UCC          NaN     NaN     NaN
117052  GENE ID:124905904   TRNAG-UCC          NaN     NaN     NaN
117016  GENE ID:124905868   TRNAG-UCC          NaN     NaN     NaN
117013  GENE ID:124905865   TRNAG-UCC          NaN     NaN     NaN
117049  GENE ID:124905901   TRNAG-UCC          NaN     NaN     NaN
117043  GENE ID:124905895   TRNAG-UCC          NaN     NaN     NaN
117019  GENE ID:124905871   TRNAG-UCC          NaN     NaN     NaN
117010  GENE ID:124905862   TRNAG-UCC          NaN     NaN     NaN
117007  GENE ID:124905859   TRNAG-UCC          NaN     NaN     NaN
117022  GENE ID:124905874   TRNAG-UCC          NaN     NaN     NaN
117004  GENE ID:124905856   TRNAG-UCC          NaN     NaN     NaN
117025  GENE ID:124905877   TRNAG-UCC          NaN     NaN     NaN
117028  GENE ID:124905880   TRNAG-UCC          NaN     NaN     NaN
117034  GENE ID:124905886   TRNAG-UCC          NaN     NaN     NaN
117031  GENE ID:124905883   TRNAG-UCC          NaN     NaN     NaN
117040  GENE ID:124905892   TRNAG-UCC          NaN     NaN     NaN
117037  GENE ID:124905889   TRNAG-UCC          NaN     NaN     NaN
117054  GENE ID:124905906   TRNAL-CAG          NaN     NaN     NaN
117080  GENE ID:124905932   TRNAL-CAG          NaN     NaN     NaN
117078  GENE ID:124905930   TRNAL-CAG          NaN     NaN     NaN
117076  GENE ID:124905928   TRNAL-CAG          NaN     NaN     NaN
117074  GENE ID:124905926   TRNAL-CAG          NaN     NaN     NaN
117072  GENE ID:124905924   TRNAL-CAG          NaN     NaN     NaN
117057  GENE ID:124905909   TRNAL-CAG          NaN     NaN     NaN
117070  GENE ID:124905922   TRNAL-CAG          NaN     NaN     NaN
117065  GENE ID:124905917   TRNAL-CAG          NaN     NaN     NaN
117068  GENE ID:124905920   TRNAL-CAG          NaN     NaN     NaN
117000  GENE ID:124905852   TRNAL-CAG          NaN     NaN     NaN
117063  GENE ID:124905915   TRNAL-CAG          NaN     NaN     NaN
116998  GENE ID:124905850   TRNAL-CAG          NaN     NaN     NaN
117061  GENE ID:124905913   TRNAL-CAG          NaN     NaN     NaN
116996  GENE ID:124905848   TRNAL-CAG          NaN     NaN     NaN
117059  GENE ID:124905911   TRNAL-CAG          NaN     NaN     NaN
117082  GENE ID:124905934   TRNAL-CAG          NaN     NaN     NaN
116771  GENE ID:124905582   TRNAN-GUU          NaN     NaN     NaN
116776  GENE ID:124905587   TRNAN-GUU          NaN     NaN     NaN
116774  GENE ID:124905585   TRNAN-GUU          NaN     NaN     NaN
116768  GENE ID:124905579   TRNAN-GUU          NaN     NaN     NaN
100045  GENE ID:107985614   TRNAV-CAC          NaN     NaN     NaN
100046  GENE ID:107985615   TRNAV-CAC          NaN     NaN     NaN

How many ambiguous symbols result from alias-primary collisions?

In [218]:
ap_collision_ambiguous_symbol_set_ncbi = set(
    merged_alias_ap_collision_ncbi_df["collision"]
)
ap_collision_ambiguous_symbol_count_ncbi = len(ap_collision_ambiguous_symbol_set_ncbi)
ap_collision_ambiguous_symbol_count_ncbi

1394

How many records have at least one alias-primary collision (alias that matches another record's primary gene symbol)?

In [219]:
ap_record_set_ncbi = set(merged_alias_ap_collision_ncbi_df["NCBI_ID"])
ap_record_count_ncbi = len(ap_record_set_ncbi)
ap_record_count_ncbi

1613

# Merge 3 sets together

In [220]:
merged_alias_primary_collisions_df = pd.concat(
    [
        merged_alias_ap_collision_hgnc_df[
            ["gene_symbol", "alias_symbol", "collision", "source", "ENSG_ID", "HGNC_ID", "NCBI_ID"]
        ],
        merged_alias_ap_collision_ncbi_df[
            ["gene_symbol", "alias_symbol", "collision", "source", "ENSG_ID", "HGNC_ID", "NCBI_ID"]
        ],
        merged_alias_ap_collision_ensg_df[
            ["gene_symbol", "alias_symbol", "collision", "source", "ENSG_ID", "HGNC_ID", "NCBI_ID"]
        ],
    ]
)
merged_alias_primary_collisions_df

,gene_symbol,alias_symbol,collision,source,ENSG_ID,HGNC_ID,NCBI_ID
0,PPP1R12C,"AAVS1,DKFZP434D0412,MBS85,p84,p85",AAVS1,HGNC,ENSG00000125503,HGNC:14947,GENE ID:54776
1,SOAT1,"ACAT,ACAT1",ACAT1,HGNC,ENSG00000057252,HGNC:11177,GENE ID:6646
2,SOAT2,ACAT2,ACAT2,HGNC,ENSG00000167780,HGNC:11178,GENE ID:8435
3,CCRL2,"ACKR5,CKRX,CRAM-A,CRAM-B,HCR",ACKR5,HGNC,ENSG00000121797,HGNC:1612,GENE ID:9034
4,NDUFAB1,"ACP,ACP1,FASN2A,SDAP",ACP1,HGNC,ENSG00000004779,HGNC:7694,GENE ID:4706
...,...,...,...,...,...,...,...
806,ZNF121,"D19S204,ZHC32,ZNF20",ZNF20,ENSG,ENSG00000197961,HGNC:12904,GENE ID:7675
807,RNF141,"ZFP26,ZNF230",ZNF230,ENSG,ENSG00000110315,HGNC:21159,GENE ID:50862
808,ZNF322P1,"ZNF322,ZNF322B",ZNF322,ENSG,ENSG00000188801,HGNC:14003,NaN
809,ZNF106,"SH3BP3,ZFP106,ZNF474",ZNF474,ENSG,ENSG00000103994,HGNC:12886,GENE ID:64397
810,ZFP1,"FLJ34243,ZNF475",ZNF475,ENSG,ENSG00000184517,HGNC:23328,GENE ID:162239

In [221]:
merged_alias_primary_collisions_df.loc[
    merged_alias_primary_collisions_df["collision"] == "KRAS"
]

,gene_symbol,alias_symbol,collision,source,ENSG_ID,HGNC_ID,NCBI_ID
963,NRAS,"ALPS4,CMNS,KRAS,N-ras,NCMS,NRAS1,NS6",KRAS,NCBI,ENSG00000213281,HGNC:7989,GENE ID:4893

# Convert to csv

In [222]:
merged_alias_primary_collisions_df.to_csv(
    "../output/merged_alias_primary_collisions_df.csv", index=False
)

In [223]:
common_ap_collision_ambiguous_symbol_set = (
    ap_collision_ambiguous_symbol_set_ncbi
    & ap_collision_ambiguous_symbol_set_hgnc
    & ap_collision_ambiguous_symbol_set_ensg
)
common_ap_collision_ambiguous_symbol_set

{'ACAT1',
 'ACAT2',
 'ACP1',
 'ACTBP2',
 'ADA2',
 'ADRA1A',
 'AGT',
 'AIP',
 'ALB',
 'AMN',
 'APC2',
 'AR',
 'ARC',
 'ARG1',
 'ARHGAP10',
 'ARL1',
 'ARSB',
 'ASIP',
 'ATF1',
 'ATR',
 'AVP',
 'B3GNT8',
 'BACH1',
 'BAP1',
 'BCAM',
 'BCRP1',
 'BCRP2',
 'BDP1',
 'BNC1',
 'BRAP',
 'BRCC3',
 'BRI3',
 'BST1',
 'BTF3',
 'C6',
 'C7',
 'CA11',
 'CABP1',
 'CAD',
 'CAMP',
 'CAP1',
 'CAP2',
 'CAPS',
 'CAPS2',
 'CARF',
 'CAST',
 'CBLC',
 'CCR10',
 'CCR4',
 'CDH1',
 'CDH20',
 'CDH7',
 'CDKN1A',
 'CDS1',
 'CES2',
 'CHD5',
 'CHL1',
 'CHP1',
 'CIC',
 'CKLF',
 'CLC',
 'CLCP1',
 'CLIP4',
 'CNP',
 'CNR1',
 'CNR2',
 'COP1',
 'CPA3',
 'CPA6',
 'CPD',
 'CPN1',
 'CPN2',
 'CPS1',
 'CREB3',
 'CRIP1',
 'CRP',
 'CSN2',
 'CSN3',
 'CSNK2A1',
 'CST6',
 'CSTP1',
 'CTAGE4',
 'CTH',
 'DAO',
 'DAP',
 'DAP3',
 'DBI',
 'DBP',
 'DEF6',
 'DIO1',
 'DLC1',
 'DMC1',
 'DMP1',
 'DOK1',
 'DRC3',
 'DRG1',
 'DRP2',
 'DSC1',
 'DUSP1',
 'DUSP23',
 'DUSP26',
 'EAF2',
 'EBP',
 'ECD',
 'EIF2A',
 'ELF1',
 'ELK1',
 'ELN',
 'EMB',
 'EPO',
 'F11',
 'F3',
 'FAAH',
 'FABP5',
 'FADS6',
 'FAH',
 'FAS',
 'FBP2',
 'FBXO31',
 'FCRL2',
 'FEM1A',
 'FEZ1',
 'FGF2',
 'FLG',
 'FLI1',
 'FZD3',
 'GAB1',
 'GAL',
 'GAL3ST2',
 'GALNT15',
 'GALNT17',
 'GAR1',
 'GCK',
 'GCKR',
 'GCOM1',
 'GDA',
 'GEM',
 'GIP',
 'GK2',
 'GLA',
 'GLS',
 'GLUD1',
 'GLUD2',
 'GOT1',
 'GPI',
 'GPT',
 'GPX6',
 'GRIN1',
 'GRIP1',
 'GRP',
 'GSG1',
 'HAP1',
 'HAS1',
 'HBM',
 'HCP5',
 'HCRTR2',
 'HCST',
 'HDC',
 'HES1',
 'HGF',
 'HK1',
 'HK2',
 'HK3',
 'HLA-H',
 'HLF',
 'HP',
 'HPCA',
 'HPF1',
 'HRG',
 'HRH1',
 'HSD17B7',
 'HTRA3',
 'IFNA13',
 'IK',
 'IL25',
 'IMP3',
 'IMP4',
 'IQCH',
 'ISY1',
 'KLF14',
 'KLHL6',
 'KLK7',
 'KRTAP5-1',
 'KRTAP5-11',
 'KRTAP5-2',
 'KRTAP5-3',
 'KRTAP5-8',
 'KRTAP5-9',
 'KSR2',
 'LAMA3',
 'LAT',
 'LAT2',
 'LBH',
 'LCP1',
 'LDB1',
 'LIG1',
 'LIPA',
 'LNP1',
 'LRP1',
 'LRP2BP',
 'LRP4',
 'MADD',
 'MAFA',
 'MAK',
 'MAL',
 'MAP1A',
 'MAP2',
 'MAS1',
 'MAST1',
 'MBP',
 'ME1',
 'ME2',
 'ME3',
 'MED1',
 'MED24',
 'MED25',
 'MET',
 'MGA',
 'MGAT1',
 'MGAT2',
 'MGAT3',
 'MIA2',
 'MIF',
 'MIP',
 'MLC1',
 'MLN',
 'MOS',
 'MPDZ',
 'MPP1',
 'MPP2',
 'MPP4',
 'MPP7',
 'MRPL27',
 'MRPS28',
 'MRPS35',
 'MS4A10',
 'MS4A7',
 'MS4A8',
 'MSL1',
 'MST1',
 'MTCP1',
 'MTF1',
 'MYH14',
 'MYNN',
 'MYO1C',
 'MYT1',
 'NAF1',
 'NANOGP2',
 'NANOGP3',
 'NANOGP4',
 'NAPA',
 'NAPB',
 'NARF',
 'NAT1',
 'NAT2',
 'NBN',
 'NET1',
 'NGB',
 'NLK',
 'NMB',
 'NME1',
 'NMI',
 'NOP9',
 'NOS1',
 'NOS2',
 'NOS3',
 'NPR2',
 'NPR3',
 'NRAP',
 'NRF1',
 'NRP2',
 'NSL1',
 'NTN4',
 'ODC1',
 'OPA1',
 'ORC1',
 'OSM',
 'OSR1',
 'OXR1',
 'PAK1',
 'PAK3',
 'PAK5',
 'PAM',
 'PAN2',
 'PAN3',
 'PC',
 'PCM1',
 'PDF',
 'PDK1',
 'PDP1',
 'PDX1',
 'PGAM1',
 'PGP',
 'PGS1',
 'PIGF',
 'PIM1',
 'PISD',
 'PKD2',
 'PLAC8',
 'PMP22',
 'PMS2P13',
 'PNP',
 'POLK',
 'POLQ',
 'POMP',
 'POP1',
 'POP4',
 'POR',
 'PPAT',
 'PPOX',
 'PRB1',
 'PRDX6',
 'PREP',
 'PRG2',
 'PRG3',
 'PRR4',
 'PRX',
 'PSAP',
 'PSG1',
 'PTH2',
 'PTPRO',
 'PVALB',
 'RAC1',
 'RAC3',
 'RAD1',
 'RAE1',
 'RAF1',
 'RAI1',
 'RASSF4',
 'RAX',
 'RBM5-AS1',
 'RBP1',
 'RBP2',
 'RBP3',
 'REN',
 'RFC1',
 'RGP1',
 'RGR',
 'RGS13',
 'RHEB',
 'RHO',
 'RIF1',
 'RILP',
 'RLF',
 'RNASE9',
 'ROR1',
 'RP1',
 'RP2',
 'RPA1',
 'RPA2',
 'RPF1',
 'RPL10',
 'RPL13',
 'RPL17',
 'RPL23',
 'RPL24',
 'RPN1',
 'RPN2',
 'RPS12',
 'RRP1',
 'RS1',
 'S100A16',
 'SAG',
 'SAP130',
 'SAT2',
 'SCAF1',
 'SCP2',
 'SCYL1',
 'SCYL2',
 'SCYL3',
 'SDS',
 'SELP',
 'SF1',
 'SF3B1',
 'SFN',
 'SI',
 'SIT1',
 'SKP2',
 'SLA',
 'SLIT1',
 'SLIT3',
 'SLK',
 'SMAD1',
 'SMAP2',
 'SMO',
 'SMS',
 'SNORA58B',
 'SNORD115-48',
 'SNURF',
 'SNX30',
 'SP110',
 'SPATA8',
 'SPN',
 'SPP1',
 'SPP2',
 'SPR',
 'SRA1',
 'SRM',
 'ST7',
 'STAG1',
 'STAR',
 'STK3',
 'STRAP',
 'TAF4B',
 'TAP1',
 'TAP2',
 'TEN1',
 'TEP1',
 'TF',
 'THY1-AS1',
 'TIFA',
 'TKT',
 'TNFRSF11B',
 'TNNC1',
 'TPH2',
 'TPO',
 'TPP1',
 'TPRKB',
 'TRAP1',
 'TRAV11',
 'TSN',
 'TTF1',
 'UCN2',
 'UGT2B11',
 'USE1',
 'USP10',
 'USP16',
 'USP21',
 'VIP',
 'WBP1',
 'ZNF20',
 'ZNF230',
 'ZNF474',
 'ZNF475'}

In [224]:
len(common_ap_collision_ambiguous_symbol_set)

434