# <a id='toc1_'></a>[Alias-Primary Collision Analysis](#toc0_)

In this notebook, we identify alias-primary collisions within the Ensembl, HGNC, and NCBI Gene databases

**Table of contents**<a id='toc0_'></a>    
- [Alias-Primary Collision Analysis](#toc1_)    
  - [Define Functions](#toc1_1_)    
  - [Ensembl](#toc1_2_)    
- [HGNC](#toc2_)    
- [NCBI Gene](#toc3_)    
- [Merge 3 sets together](#toc4_)    
- [Convert to csv](#toc5_)    

<!-- vscode-jupyter-toc-config
	numbering=false
	anchor=true
	flat=false
	minLevel=1
	maxLevel=6
	/vscode-jupyter-toc-config -->
<!-- THIS CELL WILL BE REPLACED ON TOC UPDATE. DO NOT WRITE YOUR TEXT IN THIS CELL -->

In [1]:
import pandas as pd
import numpy as np
import json

## <a id='toc1_1_'></a>[Define Functions](#toc0_)

In [2]:
def create_ap_collision_df(mini_xxxx_df: pd.DataFrame, source: str, case_sensitive: bool = False) -> pd.DataFrame:
    """
    Create a DataFrame of alias-primary collision symbols.
    :param mini_xxxx_df: Processed df of gene records (blank values converted to nans)
    :param source: Representation of the gene source ('HGNC', 'NCBI', 'ENSG')
    :param case_sensitive: Whether symbol matching is case-sensitive
    :return: A df of genes that share an alias with another gene's primary gene symbol
    """
    # Remove placeholder gene records
    mini_xxxx_df = mini_xxxx_df.dropna(subset=["primary_gene_symbol"])
    mini_xxxx_df.to_csv(f'../output/mini_{source.lower()}_df.csv', index=False)

    # Create merged alias df (for later verification)
    merged_alias_xxxx_df = (
        mini_xxxx_df
        .copy()
        .fillna("")
        .groupby(f"{source}_ID", dropna=False)
        .agg(lambda col: ",".join(sorted(set(map(str, col)))))
        .reset_index()
    )
    merged_alias_xxxx_df.to_csv(f'../output/merged_alias_{source}_df.csv', index=False)

    # Case normalization logic
    def normalize(val):
        return val if case_sensitive or pd.isna(val) else str(val).upper()

    # Normalize primary gene symbols
    mini_xxxx_df["normalized_primary"] = mini_xxxx_df["primary_gene_symbol"].map(normalize)
    xxxx_gene_symbol_set = set(mini_xxxx_df["normalized_primary"])

    subset_genes_xxxx_df = mini_xxxx_df.copy()

    # Normalize alias and remove if alias matches primary
    subset_genes_xxxx_df["normalized_alias"] = subset_genes_xxxx_df["alias_symbol"].map(normalize)
    subset_genes_xxxx_df['alias_symbol'] = subset_genes_xxxx_df.apply(
        lambda row: np.nan if row["normalized_alias"] == row["normalized_primary"] else row['alias_symbol'], axis=1
    )
    subset_genes_xxxx_df = subset_genes_xxxx_df.drop(columns=["normalized_alias", "normalized_primary"])
    subset_genes_xxxx_df.to_csv(f'../output/subset_genes_{source}_df.csv', index=False)

    # Create alias-primary collision DataFrame
    ap_collision_xxxx_df = subset_genes_xxxx_df.dropna(subset=["alias_symbol"]).copy()
    ap_collision_xxxx_df["normalized_alias"] = ap_collision_xxxx_df["alias_symbol"].map(normalize)
    ap_collision_xxxx_df["alias_symbol_set"] = ap_collision_xxxx_df["normalized_alias"].apply(lambda x: {x})

    ap_collision_xxxx_df["collision"] = ap_collision_xxxx_df["alias_symbol_set"].apply(
        lambda x: x & xxxx_gene_symbol_set
    )
    ap_collision_xxxx_df = ap_collision_xxxx_df[ap_collision_xxxx_df["collision"].apply(lambda x: len(x) > 0)]
    ap_collision_xxxx_df["collision"] = ap_collision_xxxx_df["collision"].apply(lambda x: ', '.join(x))
    ap_collision_xxxx_df = ap_collision_xxxx_df.sort_values("collision")
    ap_collision_xxxx_df["source"] = str(source.upper())
    ap_collision_xxxx_df.drop(columns=["normalized_alias", "alias_symbol_set"], inplace=True)
    ap_collision_xxxx_df.to_csv(f'../output/single_alias_ap_collision_{source.lower()}_df.csv', index=False)

    # Merge alias list back for verification
    columns_map = {
        'ENSG': ['NCBI_ID', 'HGNC_ID'],
        'HGNC': ['NCBI_ID', 'ENSG_ID'],
        'NCBI': ['HGNC_ID', 'ENSG_ID']
    }
    cols_of_interest = columns_map.get(source, [])

    merged_alias_ap_collision_xxxx_df = ap_collision_xxxx_df.drop(columns=cols_of_interest + ['alias_symbol'], errors='ignore')

    merged_alias_ap_collision_xxxx_df = pd.merge(
        merged_alias_ap_collision_xxxx_df,
        merged_alias_xxxx_df[[f"{source}_ID"] + cols_of_interest + ['alias_symbol']],
        on=f"{source}_ID",
        how="left"
    ).drop_duplicates(subset=[f"{source}_ID"])

    # Test if all collisions are present in alias list
    test_df = merged_alias_ap_collision_xxxx_df.copy()
    test_df["alias_symbol_list"] = test_df["alias_symbol"].str.split(',')
    test_df["alias_symbol_list"] = test_df["alias_symbol_list"].apply(lambda x: [normalize(i.strip()) for i in x] if isinstance(x, list) else [])

    test_df["collision_list"] = test_df["collision"].str.split(', ')
    test_df["collision_in_alias"] = test_df.apply(
        lambda row: all(c in row["alias_symbol_list"] for c in row["collision_list"]),
        axis=1
    )

    if test_df["collision_in_alias"].all():
        merged_alias_ap_collision_xxxx_df.to_csv(f'../output/merged_alias_ap_collision_{source.lower()}_df.csv', index=False)
        print("All collisions are present in gene alias lists.")
    else:
        print("Some collisions are not present in gene alias lists.")

    return mini_xxxx_df.head()

## <a id='toc1_2_'></a>[Ensembl](#toc0_)

In [3]:
raw_ensg_df = pd.read_csv("../output/raw_ensg_df.csv")

how many gene records for the Ensembl data set before any kind of cleaning?

In [4]:
total_raw_gene_record_set_ensg = set(raw_ensg_df['ENSG_ID'])
total_raw_gene_record_count_ensg = len(total_raw_gene_record_set_ensg)
total_raw_gene_record_count_ensg

86364

how many gene records have no primary gene symbol?

In [5]:
raw_no_primary_symbol_record_count_ensg = (
    raw_ensg_df[raw_ensg_df["primary_gene_symbol"].isna()]
    .dropna(subset=["ENSG_ID"])
    ["ENSG_ID"]
    .nunique()
)
raw_no_primary_symbol_record_count_ensg

37963

how many gene records that have a primary gene symbol that is a LOC placeholder?

In [6]:
raw_loc_record_count_ensg = (
    raw_ensg_df[raw_ensg_df["primary_gene_symbol"].str.match(r'^LOC\d+$', na=False)]
    .dropna(subset=["ENSG_ID"])
    ["ENSG_ID"]
    .nunique()
)
raw_loc_record_count_ensg

0

how many records with an @ symbol in the primary gene symbol?

In [7]:
at_symbol_records_ensg_df = raw_ensg_df[raw_ensg_df['primary_gene_symbol'].str.contains('@', na=False)]
len(set(at_symbol_records_ensg_df["ENSG_ID"]))

0

In [8]:
create_ap_collision_df(raw_ensg_df, "ENSG")

/var/folders/vt/znzp_c6s02q6kjcmqfk0cb500000gq/T/ipykernel_39967/559501425.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mini_xxxx_df["normalized_primary"] = mini_xxxx_df["primary_gene_symbol"].map(normalize)

All collisions are present in gene alias lists.

,ENSG_ID,NCBI_ID,HGNC_ID,alias_symbol,primary_gene_symbol,normalized_primary
0,ENSG00000210049,NaN,HGNC:7481,MTTF,MT-TF,MT-TF
1,ENSG00000210049,NaN,HGNC:7481,TRNF,MT-TF,MT-TF
2,ENSG00000211459,NaN,HGNC:7470,12S,MT-RNR1,MT-RNR1
3,ENSG00000211459,NaN,HGNC:7470,MOTS-C,MT-RNR1,MT-RNR1
4,ENSG00000211459,NaN,HGNC:7470,MTRNR1,MT-RNR1,MT-RNR1

In [9]:
mini_ensg_df = pd.read_csv(
    "../output/mini_ensg_df.csv")

In [10]:
subset_genes_ensg_df = pd.read_csv(
    "../output/subset_genes_ensg_df.csv")

In [11]:
ap_collision_ensg_df = pd.read_csv(
    "../output/single_alias_ap_collision_ensg_df.csv")

In [12]:
merged_alias_ap_collision_ensg_df = pd.read_csv(
    "../output/merged_alias_ap_collision_ensg_df.csv")

how many gene records are in the Ensembl database?

In [13]:
gene_record_set_ensg = set(mini_ensg_df['ENSG_ID'])
gene_record_count_ensg = len(gene_record_set_ensg)
gene_record_count_ensg

48401

how many unique primary gene symbols are in the Ensembl data set?

In [14]:
primary_symbol_set_ensg = set(mini_ensg_df['primary_gene_symbol'])
primary_symbol_count_ensg = len(primary_symbol_set_ensg)
primary_symbol_count_ensg

41164

how many unique alias gene symbols are in the Ensembl data set?

In [15]:
alias_symbol_set_ensg = set(mini_ensg_df['alias_symbol'])
alias_symbol_count_ensg = len(alias_symbol_set_ensg)
alias_symbol_count_ensg

55413

how many unique gene symbols in total are there in the Ensembl data set??

In [16]:
total_symbol_count_ensg = pd.concat([mini_ensg_df["primary_gene_symbol"], mini_ensg_df["alias_symbol"]]).dropna().nunique()
total_symbol_count_ensg

95941

how many gene records have no alias symbols?

In [17]:
no_alias_symbol_record_count_ensg = (
    mini_ensg_df[mini_ensg_df["alias_symbol"].isna()]
    .dropna(subset=["ENSG_ID"])
    ["ENSG_ID"]
    .nunique()
)
no_alias_symbol_record_count_ensg

19363

In [18]:
(no_alias_symbol_record_count_ensg/gene_record_count_ensg)*100

40.00537178983905

how many gene records have a primary gene symbol that is a C#orf?

In [19]:
orf_record_set_ensg = set(
    mini_ensg_df[
        mini_ensg_df["primary_gene_symbol"].str.contains(r'^C.*ORF', case=False, na=False) &
        ~mini_ensg_df["primary_gene_symbol"].str.contains("-", na=False)
    ]
    .dropna(subset=["ENSG_ID"])["ENSG_ID"]
)

orf_record_count_ensg = len(orf_record_set_ensg)
orf_record_count_ensg

288

In [20]:
(orf_record_count_ensg/gene_record_count_ensg)*100

0.595029028325861

how many gene records that have a primary gene symbol that is a FAM placeholder?

In [21]:
fam_record_set_ensg = set(
    mini_ensg_df[
        mini_ensg_df["primary_gene_symbol"].str.match(r'^FAM\d[A-Z0-9]*$', na=False) &
        ~mini_ensg_df["primary_gene_symbol"].str.contains("-", na=False)
    ]
    .dropna(subset=["ENSG_ID"])["ENSG_ID"]
)

fam_record_count_ensg = len(fam_record_set_ensg)
fam_record_count_ensg

430

In [22]:
(fam_record_count_ensg/gene_record_count_ensg)*100

0.8884113964587508

In [23]:
fam_record_set_ensg_df = mini_ensg_df[mini_ensg_df['ENSG_ID'].isin(fam_record_set_ensg)].copy()
fam_record_set_ensg_df['fam_family'] = fam_record_set_ensg_df['primary_gene_symbol'].str.extract(r'^FAM(\d+)')
unique_families_count_ensg = fam_record_set_ensg_df['fam_family'].unique()
print("Number of unique FAM families in ENSG:", len(unique_families_count_ensg))

Number of unique FAM families in ENSG: 106

how many gene records that have a primary gene symbol that is a KIAA placeholder?

In [24]:
kiaa_record_set_ensg = set(
    mini_ensg_df[
        mini_ensg_df["primary_gene_symbol"].str.startswith("KIAA", na=False) &
        ~mini_ensg_df["primary_gene_symbol"].str.contains("-", na=False)
    ]
    .dropna(subset=["ENSG_ID"])["ENSG_ID"]
)

kiaa_record_count_ensg = len(kiaa_record_set_ensg)
kiaa_record_count_ensg

33

In [25]:
(kiaa_record_count_ensg/gene_record_count_ensg)*100

0.06818040949567158

which gene records share a primary symbol with other gene records?

In [26]:
# groupby name and return a boolean of whether each has more than 1 unique ENSG ID
multi_primary = mini_ensg_df.groupby(["primary_gene_symbol"]).ENSG_ID.nunique().gt(1)

num_rows = mini_ensg_df[mini_ensg_df.primary_gene_symbol.isin(multi_primary[multi_primary].index)].shape[0]
print(num_rows)

# use loc to only see those values that have `True` in `multi_primary`:
mini_ensg_df.loc[mini_ensg_df.primary_gene_symbol.isin(multi_primary[multi_primary].index)].sort_values(by='primary_gene_symbol').iloc[6000:6060]

25007

,ENSG_ID,NCBI_ID,HGNC_ID,alias_symbol,primary_gene_symbol
74237,ENSG00000138641,GENE ID:8916,HGNC:4876,KIAA0032,HERC3
74229,ENSG00000287542,GENE ID:8916,NaN,NaN,HERC3
42473,ENSG00000273529,GENE ID:388585,HGNC:19764,BHLHB38,HES5
11951,ENSG00000197921,GENE ID:388585,HGNC:19764,BHLHB38,HES5
3740,ENSG00000280680,GENE ID:55733,HGNC:18270,MART-2,HHAT
3745,ENSG00000280680,GENE ID:55733,HGNC:18270,SKN,HHAT
3742,ENSG00000280680,GENE ID:55733,HGNC:18270,RASP,HHAT
3741,ENSG00000280680,GENE ID:55733,HGNC:18270,MART2,HHAT
34929,ENSG00000054392,GENE ID:55733,HGNC:18270,MART2,HHAT
34932,ENSG00000054392,GENE ID:55733,HGNC:18270,SKI,HHAT
3739,ENSG00000280680,GENE ID:55733,HGNC:18270,GUP2,HHAT
3738,ENSG00000280680,GENE ID:55733,HGNC:18270,FLJ10724,HHAT
3743,ENSG00000280680,GENE ID:55733,HGNC:18270,SIT,HHAT
34931,ENSG00000054392,GENE ID:55733,HGNC:18270,SIT,HHAT
34930,ENSG00000054392,GENE ID:55733,HGNC:18270,RASP,HHAT
34928,ENSG00000054392,GENE ID:55733,HGNC:18270,MART-2,HHAT
34927,ENSG00000054392,GENE ID:55733,HGNC:18270,GUP2,HHAT
34926,ENSG00000054392,GENE ID:55733,HGNC:18270,FLJ10724,HHAT
34933,ENSG00000054392,GENE ID:55733,HGNC:18270,SKN,HHAT
3744,ENSG00000280680,GENE ID:55733,HGNC:18270,SKI,HHAT
59475,ENSG00000235657,GENE ID:3105,HGNC:4931,NaN,HLA-A
55935,ENSG00000224320,GENE ID:3105,HGNC:4931,NaN,HLA-A
54253,ENSG00000227715,GENE ID:3105,HGNC:4931,NaN,HLA-A
62674,ENSG00000231834,GENE ID:3105,HGNC:4931,NaN,HLA-A
79090,ENSG00000206503,GENE ID:3105,HGNC:4931,NaN,HLA-A
54862,ENSG00000206505,GENE ID:3105,HGNC:4931,NaN,HLA-A
65424,ENSG00000223980,GENE ID:3105,HGNC:4931,NaN,HLA-A
54016,ENSG00000229215,GENE ID:3105,HGNC:4931,NaN,HLA-A
65438,ENSG00000224608,GENE ID:3106,HGNC:4932,AS,HLA-B
57978,ENSG00000234745,GENE ID:3106,HGNC:4932,AS,HLA-B
53673,ENSG00000206450,GENE ID:3106,HGNC:4932,AS,HLA-B
57406,ENSG00000232126,GENE ID:3106,HGNC:4932,AS,HLA-B
64859,ENSG00000223532,GENE ID:3106,HGNC:4932,AS,HLA-B
66693,ENSG00000228964,GENE ID:3106,HGNC:4932,AS,HLA-B
50556,ENSG00000204525,GENE ID:3107,HGNC:4933,D6S204,HLA-C
64252,ENSG00000228299,GENE ID:3107,HGNC:4933,PSORS1,HLA-C
64251,ENSG00000228299,GENE ID:3107,HGNC:4933,HLA-JY3,HLA-C
64555,ENSG00000233841,GENE ID:3107,HGNC:4933,PSORS1,HLA-C
62812,ENSG00000206452,GENE ID:3107,HGNC:4933,HLA-JY3,HLA-C
64250,ENSG00000228299,GENE ID:3107,HGNC:4933,D6S204,HLA-C
64554,ENSG00000233841,GENE ID:3107,HGNC:4933,HLA-JY3,HLA-C
57177,ENSG00000225691,GENE ID:3107,HGNC:4933,PSORS1,HLA-C
66230,ENSG00000206435,GENE ID:3107,HGNC:4933,PSORS1,HLA-C
62811,ENSG00000206452,GENE ID:3107,HGNC:4933,D6S204,HLA-C
66229,ENSG00000206435,GENE ID:3107,HGNC:4933,HLA-JY3,HLA-C
66572,ENSG00000237022,GENE ID:3107,HGNC:4933,PSORS1,HLA-C
66571,ENSG00000237022,GENE ID:3107,HGNC:4933,HLA-JY3,HLA-C
57175,ENSG00000225691,GENE ID:3107,HGNC:4933,D6S204,HLA-C
62813,ENSG00000206452,GENE ID:3107,HGNC:4933,PSORS1,HLA-C
66228,ENSG00000206435,GENE ID:3107,HGNC:4933,D6S204,HLA-C
50558,ENSG00000204525,GENE ID:3107,HGNC:4933,PSORS1,HLA-C
57176,ENSG00000225691,GENE ID:3107,HGNC:4933,HLA-JY3,HLA-C
50557,ENSG00000204525,GENE ID:3107,HGNC:4933,HLA-JY3,HLA-C
66570,ENSG00000237022,GENE ID:3107,HGNC:4933,D6S204,HLA-C
64553,ENSG00000233841,GENE ID:3107,HGNC:4933,D6S204,HLA-C
62488,ENSG00000242685,GENE ID:3108,HGNC:4934,D6S222E,HLA-DMA
61743,ENSG00000243189,GENE ID:3108,HGNC:4934,D6S222E,HLA-DMA
68484,ENSG00000243215,GENE ID:3108,HGNC:4934,D6S222E,HLA-DMA
61373,ENSG00000243719,GENE ID:3108,HGNC:4934,D6S222E,HLA-DMA
61744,ENSG00000243189,GENE ID:3108,HGNC:4934,RING6,HLA-DMA

How many ambiguous symbols result from alias-primary collisions?

In [27]:
ap_collision_ambiguous_symbol_set_ensg = set(merged_alias_ap_collision_ensg_df["collision"])
ap_collision_ambiguous_symbol_count_ensg = len(ap_collision_ambiguous_symbol_set_ensg)
ap_collision_ambiguous_symbol_count_ensg

606

How many records have at least one alias-primary collision (alias that matches another record's primary gene symbol)?

In [28]:
ap_record_set_ensg = set(merged_alias_ap_collision_ensg_df["ENSG_ID"])
ap_record_count_ensg = len(ap_record_set_ensg)
ap_record_count_ensg

767

1. Why is the alias-gene collision set not the same length as the set of primary symbols with collisions ?
2. Why is the length of the alias-gene collison set shorter?
 - A gene record with an alias-primary collision has an alias that matches a different gene's primary gene symbol.
 - Multiple gene records can share a single alias (alias-alias collision)
 - If that shared alias is an alias-primary collision, then there will be more unique gene symbols in the set of primary symbols with collisions than the set of alias-primary collisions.

# <a id='toc2_'></a>[HGNC](#toc0_)

In [29]:
raw_hgnc_df = pd.read_csv("../output/raw_hgnc_df.csv")

how many gene records for the HGNC data set before any kind of cleaning?

In [30]:
total_raw_gene_record_set_hgnc = set(raw_hgnc_df['HGNC_ID'])
total_raw_gene_record_count_hgnc = len(total_raw_gene_record_set_hgnc)
total_raw_gene_record_count_hgnc

44235

how many gene records have no primary gene symbol?

In [31]:
raw_no_primary_symbol_record_count_hgnc = (
    raw_hgnc_df[raw_hgnc_df["primary_gene_symbol"].isna()]
    .dropna(subset=["HGNC_ID"])
    ["HGNC_ID"]
    .nunique()
)
raw_no_primary_symbol_record_count_hgnc

0

how many gene records that have a primary gene symbol that is a LOC placeholder?

In [32]:
raw_loc_record_count_hgnc = (
    raw_hgnc_df[raw_hgnc_df["primary_gene_symbol"].str.match(r'^LOC\d+$', na=False)]
    .dropna(subset=["HGNC_ID"])
    ["HGNC_ID"]
    .nunique()
)
raw_loc_record_count_hgnc

0

how many records with an @ symbol in the primary gene symbol?

In [33]:
at_symbol_records_hgnc_df = raw_hgnc_df[raw_hgnc_df['primary_gene_symbol'].str.contains('@', na=False)]
len(set(at_symbol_records_hgnc_df["HGNC_ID"]))

7

In [34]:
no_at_hgnc_df = raw_hgnc_df[~raw_hgnc_df['HGNC_ID'].isin(at_symbol_records_hgnc_df['HGNC_ID'])]

In [35]:
create_ap_collision_df(no_at_hgnc_df, "HGNC")

All collisions are present in gene alias lists.

,HGNC_ID,primary_gene_symbol,alias_symbol,NCBI_ID,ENSG_ID,normalized_primary
0,HGNC:100,ASIC1,BNaC2,GENE ID:41,ENSG00000110881,ASIC1
1,HGNC:100,ASIC1,hBNaC2,GENE ID:41,ENSG00000110881,ASIC1
2,HGNC:10000,RGS4,NaN,GENE ID:5999,ENSG00000117152,RGS4
3,HGNC:10001,RGS5,NaN,GENE ID:8490,ENSG00000143248,RGS5
4,HGNC:10002,RGS6,NaN,GENE ID:9628,ENSG00000182732,RGS6

In [36]:
mini_hgnc_df = pd.read_csv(
    "../output/mini_hgnc_df.csv")

In [37]:
subset_genes_hgnc_df = pd.read_csv(
    "../output/subset_genes_hgnc_df.csv")

In [38]:
merged_alias_ap_collision_hgnc_df = pd.read_csv(
    "../output/merged_alias_ap_collision_hgnc_df.csv")

how many gene records are in the HGNC database?

In [39]:
gene_record_set_hgnc = set(mini_hgnc_df['HGNC_ID'])
gene_record_count_hgnc = len(gene_record_set_hgnc)
gene_record_count_hgnc

44228

how many unique primary gene symbols are in the HGNC data set?

In [40]:
primary_symbol_set_hgnc = set(mini_hgnc_df['primary_gene_symbol'])
primary_symbol_count_hgnc = len(primary_symbol_set_hgnc)
primary_symbol_count_hgnc

44228

how many unique alias gene symbols are in the HGNC data set?

In [41]:
alias_symbol_set_hgnc = set(mini_hgnc_df['alias_symbol'])
alias_symbol_count_hgnc = len(alias_symbol_set_hgnc)
alias_symbol_count_hgnc

43072

how many unique gene symbols in total are there in the HGNC data set??

In [42]:
total_symbol_count_hgnc = len(set(mini_hgnc_df['primary_gene_symbol']) | set(mini_hgnc_df['alias_symbol']))
total_symbol_count_hgnc

86832

how many gene records have no alias symbols?

In [43]:
no_alias_symbol_record_count_hgnc = (
    mini_hgnc_df[mini_hgnc_df["alias_symbol"].isna()]
    .dropna(subset=["HGNC_ID"])
    ["HGNC_ID"]
    .nunique()
)
no_alias_symbol_record_count_hgnc

21764

In [44]:
(no_alias_symbol_record_count_hgnc/gene_record_count_ensg)*100

44.96601309890291

how many gene records have a primary gene symbol that is a C#orf?

In [45]:
orf_record_set_hgnc = set(
    mini_hgnc_df[
        mini_hgnc_df["primary_gene_symbol"].str.contains(r'^C.*ORF', case=False, na=False) &
        ~mini_hgnc_df["primary_gene_symbol"].str.contains("-", na=False)
    ]
    .dropna(subset=["HGNC_ID"])["HGNC_ID"]
)

orf_record_count_hgnc = len(orf_record_set_hgnc)
orf_record_count_hgnc

246

In [46]:
(orf_record_count_hgnc/gene_record_count_ensg)*100

0.5082539616950063

how many gene records that have a primary gene symbol that is a FAM placeholder?

In [47]:
fam_record_set_hgnc = set(
    mini_hgnc_df[mini_hgnc_df["primary_gene_symbol"].str.match(r'^FAM\d[A-Z0-9]*$', na=False)&
    ~mini_hgnc_df['primary_gene_symbol']
    .str.contains('-', na=False)]
    .dropna(subset=["HGNC_ID"])
    ["HGNC_ID"]
)
fam_record_count_hgnc = len(fam_record_set_hgnc)
fam_record_count_hgnc

371

In [48]:
(fam_record_count_hgnc/gene_record_count_ensg)*100

0.7665130885725502

In [49]:
fam_record_set_hgnc_df = mini_hgnc_df[mini_hgnc_df['HGNC_ID'].isin(fam_record_set_hgnc)].copy()
fam_record_set_hgnc_df['fam_family'] = fam_record_set_hgnc_df['primary_gene_symbol'].str.extract(r'^FAM(\d+)')
unique_families_count_hgnc = fam_record_set_hgnc_df['fam_family'].unique()
print("Number of unique FAM families in HGNC:", len(unique_families_count_hgnc))

Number of unique FAM families in HGNC: 107

how many gene records that have a primary gene symbol that is a KIAA placeholder?

In [50]:
kiaa_record_set_hgnc = set(
    mini_hgnc_df[mini_hgnc_df["primary_gene_symbol"].str.startswith('KIAA', na=False)&
    ~mini_hgnc_df['primary_gene_symbol']
    .str.contains('-', na=False)]
    .dropna(subset=["HGNC_ID"])
    ["HGNC_ID"]
)
kiaa_record_count_hgnc = len(kiaa_record_set_hgnc)
kiaa_record_count_hgnc

32

In [51]:
(kiaa_record_count_hgnc/gene_record_count_ensg)*100

0.06611433648065122

which gene records share a primary symbol with other gene records?

In [52]:
# groupby name and return a boolean of whether each has more than 1 unique Country
multi_primary = mini_hgnc_df.groupby(["primary_gene_symbol"]).HGNC_ID.nunique().gt(1)

num_rows = mini_hgnc_df[mini_hgnc_df.primary_gene_symbol.isin(multi_primary[multi_primary].index)].shape[0]
print(num_rows)

# use loc to only see those values that have `True` in `multi_country`:
multi_record_same_symbol_df = mini_hgnc_df.loc[mini_hgnc_df.primary_gene_symbol.isin(multi_primary[multi_primary].index)].sort_values(by='primary_gene_symbol')
multi_record_same_symbol_df.head(60)

0

Empty DataFrame
Columns: [HGNC_ID, primary_gene_symbol, alias_symbol, NCBI_ID, ENSG_ID]
Index: []

How many ambiguous symbols result from alias-primary collisions?

In [53]:
ap_collision_ambiguous_symbol_set_hgnc = set(
    merged_alias_ap_collision_hgnc_df["collision"]
)
ap_collision_ambiguous_symbol_count_hgnc = len(ap_collision_ambiguous_symbol_set_hgnc)
ap_collision_ambiguous_symbol_count_hgnc

492

How many records have at least one alias-primary collision (alias that matches another record's primary gene symbol)?

In [54]:
ap_record_set_hgnc = set(merged_alias_ap_collision_hgnc_df["HGNC_ID"])
ap_record_count_hgnc = len(ap_record_set_hgnc)
ap_record_count_hgnc

546

# <a id='toc3_'></a>[NCBI Gene](#toc0_)

In [55]:
raw_ncbi_df = pd.read_csv("../output/raw_ncbi_df.csv")
raw_ncbi_df

,NCBI_ID,primary_gene_symbol,alias_symbol,gene_type,HGNC_ID,ENSG_ID
0,GENE ID:1,A1BG,A1B,protein-coding,HGNC:5,ENSG00000121410
1,GENE ID:1,A1BG,ABG,protein-coding,HGNC:5,ENSG00000121410
2,GENE ID:1,A1BG,GAB,protein-coding,HGNC:5,ENSG00000121410
3,GENE ID:1,A1BG,HYST2477,protein-coding,HGNC:5,ENSG00000121410
4,GENE ID:2,A2M,A2MD,protein-coding,HGNC:7,ENSG00000175899
...,...,...,...,...,...,...
240503,GENE ID:8923215,trnD,NaN,tRNA,NaN,NaN
240504,GENE ID:8923216,trnP,NaN,tRNA,NaN,NaN
240505,GENE ID:8923217,trnA,NaN,tRNA,NaN,NaN
240506,GENE ID:8923218,COX1,NaN,protein-coding,NaN,NaN
240507,GENE ID:8923219,16S rRNA,NaN,rRNA,NaN,NaN

how many gene records for the NCBI data set before any kind of cleaning?

In [56]:
total_raw_gene_record_set_ncbi = set(raw_ncbi_df['NCBI_ID'])
total_raw_gene_record_count_ncbi = len(total_raw_gene_record_set_ncbi)
total_raw_gene_record_count_ncbi

193580

how many gene records have the "phenotype only" property?

In [57]:
# This file (ncbi_records_w_property_pheno_only_20250630.txt) was generated through the NCBI Gene web page by 
# searching for these parameters "phenotype only [Properties] AND "Homo sapiens"[porgn:__txid9606]"
ncbi_pheno_records_df = pd.read_csv("../input/ncbi_records_w_property_pheno_only_20250630.txt", sep="\t")

ncbi_pheno_records_df = ncbi_pheno_records_df.rename(
    columns={"GeneID": "NCBI_ID", "Symbol": "primary_gene_symbol", "Aliases": "alias_symbol"})

#Converts the Gene IDs to whole numbers with a "GENE ID" prefix
ncbi_pheno_records_df["NCBI_ID"] = ncbi_pheno_records_df["NCBI_ID"].apply(
lambda x: f"GENE ID:{int(x)}" if pd.notna(x) and x == int(x) else f"GENE ID:{x}" if pd.notna(x) else x
)

In [58]:
ncbi_pheno_records_list = ncbi_pheno_records_df["NCBI_ID"].tolist()
with open('../output/pheno_records_in_ncbi_set.json', 'w') as f:
    json.dump(ncbi_pheno_records_list, f)

In [59]:
ncbi_pheno_records_df.loc[ncbi_pheno_records_df["primary_gene_symbol"].str.match(r'^LOC\d+$', na=False)]

,tax_id,Org_name,NCBI_ID,CurrentID,Status,primary_gene_symbol,alias_symbol,description,other_designations,map_location,chromosome,genomic_nucleotide_accession.version,start_position_on_the_genomic_accession,end_position_on_the_genomic_accession,orientation,exon_count,OMIM,Unnamed: 17
170,9606,Homo sapiens,GENE ID:7795,0,live,LOC7795,MEMO1,Methylation modifier for class I HLA,NaN,1p36.1-p35,1,NaN,NaN,NaN,NaN,NaN,601201.0,NaN
1096,9606,Homo sapiens,GENE ID:619539,0,live,LOC619539,NaN,"lentiginosis, inherited patterned",familial generalized lentiginosis,4q21.1-q22.3,4,NaN,NaN,NaN,NaN,NaN,151001.0,NaN

Which phenotype records are in the ncbi gene records?

In [60]:
# need to drop them
no_pheno_ncbi_df = raw_ncbi_df[~raw_ncbi_df['NCBI_ID'].isin(ncbi_pheno_records_df['NCBI_ID'])]

how many gene records have no primary gene symbol?

In [61]:
raw_no_primary_symbol_record_count_ncbi = (
    raw_ncbi_df[raw_ncbi_df["primary_gene_symbol"].isna()]
    .dropna(subset=["NCBI_ID"])
    ["NCBI_ID"]
    .nunique()
)
raw_no_primary_symbol_record_count_ncbi

0

In [62]:
(raw_no_primary_symbol_record_count_ncbi/total_raw_gene_record_count_ncbi)*100

0.0

how many gene records that have a primary gene symbol that is a LOC placeholder?

In [63]:
raw_loc_record_count_ncbi = (
    raw_ncbi_df[raw_ncbi_df["primary_gene_symbol"].str.match(r'^LOC\d+$', na=False)]
    .dropna(subset=["NCBI_ID"])
    ["NCBI_ID"]
    .nunique()
)
raw_loc_record_count_ncbi

147700

In [64]:
no_pheno_loc_ncbi_df = no_pheno_ncbi_df[~no_pheno_ncbi_df['primary_gene_symbol'].str.match(r'^LOC\d+$', na=False)]

In [65]:
len(set(no_pheno_loc_ncbi_df["NCBI_ID"]))

44712

"Homo sapiens subsp. 'Denisova'"[Organism] AND alive[prop]

how many gene records are sub species records: "homo sapiens ssp denisova"[Organism]

In [ ]:
# This file (ncbi_denisova_20250630.txt) was generated through the NCBI Gene web page by 
# searching for this parameter "Homo sapiens subsp. 'Denisova'[Organism]"
ncbi_denisova_records_df = pd.read_csv("../input/ncbi_denisova_20250630.txt", sep="\t")

ncbi_denisova_records_df = ncbi_denisova_records_df.rename(
    columns={"GeneID": "NCBI_ID", "Symbol": "primary_gene_symbol", "Aliases": "alias_symbol"})

ncbi_denisova_records_df["NCBI_ID"] = ncbi_denisova_records_df["NCBI_ID"].apply(
lambda x: f"GENE ID:{int(x)}" if pd.notna(x) and x == int(x) else f"GENE ID:{x}" if pd.notna(x) else x
)

In [67]:
len(set(ncbi_denisova_records_df["NCBI_ID"]))

36

Which denisova records are in the ncbi gene records?

In [68]:
no_pheno_loc_denisova_ncbi_df = no_pheno_loc_ncbi_df[~no_pheno_loc_ncbi_df['NCBI_ID'].isin(ncbi_denisova_records_df['NCBI_ID'])]

In [69]:
len(set(no_pheno_loc_denisova_ncbi_df["NCBI_ID"]))

44676

Drop sub species records: "homo sapiens neanderthalensis"[Organism]

In [ ]:
# This file (ncbi_neanderthalensis_20250630.txt) was generated through the NCBI Gene web page by 
# searching for this parameter "Homo sapiens Neanderthalensis [Organism]"
ncbi_neanderthalensis_records_df = pd.read_csv("../input/ncbi_neanderthalensis_20250630.txt", sep="\t")

ncbi_neanderthalensis_records_df = ncbi_neanderthalensis_records_df.rename(
    columns={"GeneID": "NCBI_ID", "Symbol": "primary_gene_symbol", "Aliases": "alias_symbol"})

ncbi_neanderthalensis_records_df["NCBI_ID"] = ncbi_neanderthalensis_records_df["NCBI_ID"].apply(
lambda x: f"GENE ID:{int(x)}" if pd.notna(x) and x == int(x) else f"GENE ID:{x}" if pd.notna(x) else x
)

In [71]:
len(set(ncbi_neanderthalensis_records_df["NCBI_ID"]))

37

Which neanderthalis records are in the ncbi gene records?

In [72]:
no_pheno_loc_denisova_neanderthalis_ncbi_df = no_pheno_loc_denisova_ncbi_df[~no_pheno_loc_denisova_ncbi_df['NCBI_ID'].isin(ncbi_neanderthalensis_records_df['NCBI_ID'])]

In [73]:
len(set(no_pheno_loc_denisova_neanderthalis_ncbi_df["NCBI_ID"]))

44639

In [74]:
combined = set(ncbi_denisova_records_df["NCBI_ID"]) | set(ncbi_neanderthalensis_records_df["NCBI_ID"])
hum_subspec_records_in_ncbi_set = list(combined)
with open('../output/hum_subspec_records_in_ncbi_set.json', 'w') as f:
    json.dump(hum_subspec_records_in_ncbi_set, f)

how many records with an @ symbol in the primary gene symbol?

In [76]:
at_symbol_records_ncbi_df = no_pheno_loc_denisova_neanderthalis_ncbi_df[no_pheno_loc_denisova_neanderthalis_ncbi_df['primary_gene_symbol'].str.contains('@', na=False)]
len(set(at_symbol_records_ncbi_df["NCBI_ID"]))

11

In [77]:
len(set(no_pheno_loc_denisova_neanderthalis_ncbi_df["NCBI_ID"]))

44639

In [78]:
no_pheno_loc_denisova_neanderthalis_at_ncbi_df = no_pheno_loc_denisova_neanderthalis_ncbi_df[~no_pheno_loc_denisova_neanderthalis_ncbi_df['NCBI_ID'].isin(at_symbol_records_ncbi_df['NCBI_ID'])]

In [79]:
len(set(no_pheno_loc_denisova_neanderthalis_at_ncbi_df["NCBI_ID"]))

44628

In [80]:
create_ap_collision_df(no_pheno_loc_denisova_neanderthalis_at_ncbi_df, "NCBI")

All collisions are present in gene alias lists.

,NCBI_ID,primary_gene_symbol,alias_symbol,gene_type,HGNC_ID,ENSG_ID,normalized_primary
0,GENE ID:1,A1BG,A1B,protein-coding,HGNC:5,ENSG00000121410,A1BG
1,GENE ID:1,A1BG,ABG,protein-coding,HGNC:5,ENSG00000121410,A1BG
2,GENE ID:1,A1BG,GAB,protein-coding,HGNC:5,ENSG00000121410,A1BG
3,GENE ID:1,A1BG,HYST2477,protein-coding,HGNC:5,ENSG00000121410,A1BG
4,GENE ID:2,A2M,A2MD,protein-coding,HGNC:7,ENSG00000175899,A2M

In [81]:
mini_ncbi_df = pd.read_csv(
    "../output/mini_ncbi_df.csv")

In [82]:
subset_genes_ncbi_df = pd.read_csv(
    "../output/subset_genes_ncbi_df.csv")

In [ ]:
merged_alias_ap_collision_ncbi_df = pd.read_csv(
    "../output/merged_alias_ap_collision_ncbi_df.csv")

how many gene records are in the NCBI database?

In [84]:
gene_record_set_ncbi = set(mini_ncbi_df['NCBI_ID'])
gene_record_count_ncbi = len(gene_record_set_ncbi)
gene_record_count_ncbi

44628

how many unique primary gene symbols are in the NCBI data set?

In [85]:
primary_symbol_set_ncbi = set(mini_ncbi_df['primary_gene_symbol'])
primary_symbol_count_ncbi = len(primary_symbol_set_ncbi)
primary_symbol_count_ncbi

44530

how many unique alias gene symbols are in the NCBI data set?

In [86]:
alias_symbol_set_ncbi = set(mini_ncbi_df['alias_symbol'])
alias_symbol_count_ncbi = len(alias_symbol_set_ncbi)
alias_symbol_count_ncbi

69210

how many unique gene symbols in total are there in the NCBI data set??

In [87]:
total_symbol_count_ncbi = pd.concat([mini_ncbi_df["primary_gene_symbol"], mini_ncbi_df["alias_symbol"]]).dropna().nunique()
total_symbol_count_ncbi

112266

how many gene records have no alias symbols?

In [88]:
no_alias_symbol_record_count_ncbi = (
    mini_ncbi_df[mini_ncbi_df["alias_symbol"].isna()]
    .dropna(subset=["NCBI_ID"])
    ["NCBI_ID"]
    .nunique()
)
no_alias_symbol_record_count_ncbi

17380

In [89]:
(no_alias_symbol_record_count_ncbi/gene_record_count_ncbi)*100

38.94416061665322

how many gene records have a primary gene symbol that is a C#orf?

In [90]:
orf_record_set_ncbi = set(mini_ncbi_df[
    mini_ncbi_df['primary_gene_symbol']
    .str.contains(r'^C.*ORF', case=False, na=False) &
    ~mini_ncbi_df['primary_gene_symbol']
    .str.contains('-', na=False)
])
orf_record_count_ncbi = len(orf_record_set_ncbi)
orf_record_count_ncbi

6

In [91]:
(orf_record_count_ncbi/gene_record_count_ncbi)*100

0.013444474321054048

how many gene records that have a primary gene symbol that is a FAM placeholder?

In [92]:
fam_record_set_ncbi = set(
    mini_ncbi_df[mini_ncbi_df["primary_gene_symbol"].str.match(r'^FAM\d[A-Z0-9]*$', na=False)&
    ~mini_ncbi_df['primary_gene_symbol']
    .str.contains('-', na=False)]
    .dropna(subset=["NCBI_ID"])
    ["NCBI_ID"]
)
fam_record_count_ncbi = len(fam_record_set_ncbi)
fam_record_count_ncbi

371

In [93]:
(fam_record_count_ncbi/gene_record_count_ncbi)*100

0.8313166621851753

In [94]:
fam_record_set_ncbi_df = mini_ncbi_df[mini_ncbi_df['NCBI_ID'].isin(fam_record_set_ncbi)].copy()
fam_record_set_ncbi_df['fam_family'] = fam_record_set_ncbi_df['primary_gene_symbol'].str.extract(r'^FAM(\d+)')
unique_families_count_ncbi = fam_record_set_ncbi_df['fam_family'].unique()
print("Number of unique FAM families in NCBI:", len(unique_families_count_ncbi))

Number of unique FAM families in NCBI: 107

how many gene records that have a primary gene symbol that is a KIAA placeholder?

In [95]:
kiaa_record_set_ncbi = set(
    mini_ncbi_df[mini_ncbi_df["primary_gene_symbol"].str.startswith('KIAA', na=False)&
    ~mini_ncbi_df['primary_gene_symbol']
    .str.contains('-', na=False)]
    .dropna(subset=["NCBI_ID"])
    ["NCBI_ID"]
)
kiaa_record_count_ncbi = len(kiaa_record_set_ncbi)
kiaa_record_count_ncbi

33

In [96]:
(kiaa_record_count_ncbi/gene_record_count_ncbi)*100

0.07394460876579727

which gene records share a primary symbol with other gene records?

In [97]:
# groupby name and return a boolean of whether each has more than 1 unique Country
multi_primary = mini_ncbi_df.groupby(["primary_gene_symbol"]).NCBI_ID.nunique().gt(1)

num_rows = mini_ncbi_df[mini_ncbi_df.primary_gene_symbol.isin(multi_primary[multi_primary].index)].shape[0]
print(num_rows)

# use loc to only see those values that have `True` in `multi_country`:
multi_record_same_symbol_df = mini_ncbi_df.loc[mini_ncbi_df.primary_gene_symbol.isin(multi_primary[multi_primary].index)].sort_values(by='primary_gene_symbol')
multi_record_same_symbol_df.head(60)

110

,NCBI_ID,primary_gene_symbol,alias_symbol,gene_type,HGNC_ID,ENSG_ID
12882,GENE ID:4549,RNR1,MTRNR1,rRNA,HGNC:7470,NaN
17323,GENE ID:6052,RNR1,NaN,other,HGNC:10082,NaN
12883,GENE ID:4550,RNR2,MTRNR2,rRNA,HGNC:7471,NaN
17324,GENE ID:6053,RNR2,NaN,other,HGNC:10083,NaN
90611,GENE ID:124901565,TRNAA-AGC,NaN,tRNA,NaN,NaN
90610,GENE ID:124901564,TRNAA-AGC,NaN,tRNA,NaN,NaN
90609,GENE ID:124901563,TRNAA-AGC,NaN,tRNA,NaN,NaN
90608,GENE ID:124901562,TRNAA-AGC,NaN,tRNA,NaN,NaN
90789,GENE ID:124906586,TRNAA-AGC,NaN,tRNA,NaN,NaN
90607,GENE ID:124901561,TRNAA-AGC,NaN,tRNA,NaN,NaN
90727,GENE ID:124905878,TRNAD-GUC,NaN,tRNA,NaN,NaN
90715,GENE ID:124905866,TRNAD-GUC,NaN,tRNA,NaN,NaN
90712,GENE ID:124905863,TRNAD-GUC,NaN,tRNA,NaN,NaN
90721,GENE ID:124905872,TRNAD-GUC,NaN,tRNA,NaN,NaN
90709,GENE ID:124905860,TRNAD-GUC,NaN,tRNA,NaN,NaN
90706,GENE ID:124905857,TRNAD-GUC,NaN,tRNA,NaN,NaN
90724,GENE ID:124905875,TRNAD-GUC,NaN,tRNA,NaN,NaN
90703,GENE ID:124905854,TRNAD-GUC,NaN,tRNA,NaN,NaN
90730,GENE ID:124905881,TRNAD-GUC,NaN,tRNA,NaN,NaN
90733,GENE ID:124905884,TRNAD-GUC,NaN,tRNA,NaN,NaN
90736,GENE ID:124905887,TRNAD-GUC,NaN,tRNA,NaN,NaN
90718,GENE ID:124905869,TRNAD-GUC,NaN,tRNA,NaN,NaN
90739,GENE ID:124905890,TRNAD-GUC,NaN,tRNA,NaN,NaN
90751,GENE ID:124905902,TRNAD-GUC,NaN,tRNA,NaN,NaN
90745,GENE ID:124905896,TRNAD-GUC,NaN,tRNA,NaN,NaN
90748,GENE ID:124905899,TRNAD-GUC,NaN,tRNA,NaN,NaN
90742,GENE ID:124905893,TRNAD-GUC,NaN,tRNA,NaN,NaN
90716,GENE ID:124905867,TRNAE-CUC,NaN,tRNA,NaN,NaN
90719,GENE ID:124905870,TRNAE-CUC,NaN,tRNA,NaN,NaN
90713,GENE ID:124905864,TRNAE-CUC,NaN,tRNA,NaN,NaN
90752,GENE ID:124905903,TRNAE-CUC,NaN,tRNA,NaN,NaN
90734,GENE ID:124905885,TRNAE-CUC,NaN,tRNA,NaN,NaN
90710,GENE ID:124905861,TRNAE-CUC,NaN,tRNA,NaN,NaN
90749,GENE ID:124905900,TRNAE-CUC,NaN,tRNA,NaN,NaN
90722,GENE ID:124905873,TRNAE-CUC,NaN,tRNA,NaN,NaN
90737,GENE ID:124905888,TRNAE-CUC,NaN,tRNA,NaN,NaN
90746,GENE ID:124905897,TRNAE-CUC,NaN,tRNA,NaN,NaN
90704,GENE ID:124905855,TRNAE-CUC,NaN,tRNA,NaN,NaN
90740,GENE ID:124905891,TRNAE-CUC,NaN,tRNA,NaN,NaN
90725,GENE ID:124905876,TRNAE-CUC,NaN,tRNA,NaN,NaN
90728,GENE ID:124905879,TRNAE-CUC,NaN,tRNA,NaN,NaN
90743,GENE ID:124905894,TRNAE-CUC,NaN,tRNA,NaN,NaN
90707,GENE ID:124905858,TRNAE-CUC,NaN,tRNA,NaN,NaN
90731,GENE ID:124905882,TRNAE-CUC,NaN,tRNA,NaN,NaN
90757,GENE ID:124905908,TRNAE-UUC,NaN,tRNA,NaN,NaN
89496,GENE ID:107987368,TRNAE-UUC,NaN,tRNA,NaN,NaN
90687,GENE ID:124905580,TRNAE-UUC,NaN,tRNA,NaN,NaN
90690,GENE ID:124905583,TRNAE-UUC,NaN,tRNA,NaN,NaN
90691,GENE ID:124905584,TRNAE-UUC,NaN,tRNA,NaN,NaN
90693,GENE ID:124905586,TRNAE-UUC,NaN,tRNA,NaN,NaN
90688,GENE ID:124905581,TRNAG-CCC,NaN,tRNA,NaN,NaN
90685,GENE ID:124905578,TRNAG-CCC,NaN,tRNA,NaN,NaN
90695,GENE ID:124905588,TRNAG-CCC,NaN,tRNA,NaN,NaN
90756,GENE ID:124905907,TRNAG-GCC,NaN,tRNA,NaN,NaN
90759,GENE ID:124905910,TRNAG-GCC,NaN,tRNA,NaN,NaN
90696,GENE ID:124905847,TRNAG-GCC,NaN,tRNA,NaN,NaN
90761,GENE ID:124905912,TRNAG-GCC,NaN,tRNA,NaN,NaN
90763,GENE ID:124905914,TRNAG-GCC,NaN,tRNA,NaN,NaN
90698,GENE ID:124905849,TRNAG-GCC,NaN,tRNA,NaN,NaN
90765,GENE ID:124905916,TRNAG-GCC,NaN,tRNA,NaN,NaN

In [98]:
multi_record_same_symbol_df.iloc[60:110]

,NCBI_ID,primary_gene_symbol,alias_symbol,gene_type,HGNC_ID,ENSG_ID
90767,GENE ID:124905918,TRNAG-GCC,NaN,tRNA,NaN,NaN
90770,GENE ID:124905921,TRNAG-GCC,NaN,tRNA,NaN,NaN
90772,GENE ID:124905923,TRNAG-GCC,NaN,tRNA,NaN,NaN
90702,GENE ID:124905853,TRNAG-GCC,NaN,tRNA,NaN,NaN
90774,GENE ID:124905925,TRNAG-GCC,NaN,tRNA,NaN,NaN
90776,GENE ID:124905927,TRNAG-GCC,NaN,tRNA,NaN,NaN
90778,GENE ID:124905929,TRNAG-GCC,NaN,tRNA,NaN,NaN
90780,GENE ID:124905931,TRNAG-GCC,NaN,tRNA,NaN,NaN
90782,GENE ID:124905933,TRNAG-GCC,NaN,tRNA,NaN,NaN
90700,GENE ID:124905851,TRNAG-GCC,NaN,tRNA,NaN,NaN
90747,GENE ID:124905898,TRNAG-UCC,NaN,tRNA,NaN,NaN
90753,GENE ID:124905904,TRNAG-UCC,NaN,tRNA,NaN,NaN
90717,GENE ID:124905868,TRNAG-UCC,NaN,tRNA,NaN,NaN
90714,GENE ID:124905865,TRNAG-UCC,NaN,tRNA,NaN,NaN
90750,GENE ID:124905901,TRNAG-UCC,NaN,tRNA,NaN,NaN
90744,GENE ID:124905895,TRNAG-UCC,NaN,tRNA,NaN,NaN
90720,GENE ID:124905871,TRNAG-UCC,NaN,tRNA,NaN,NaN
90711,GENE ID:124905862,TRNAG-UCC,NaN,tRNA,NaN,NaN
90708,GENE ID:124905859,TRNAG-UCC,NaN,tRNA,NaN,NaN
90723,GENE ID:124905874,TRNAG-UCC,NaN,tRNA,NaN,NaN
90705,GENE ID:124905856,TRNAG-UCC,NaN,tRNA,NaN,NaN
90726,GENE ID:124905877,TRNAG-UCC,NaN,tRNA,NaN,NaN
90729,GENE ID:124905880,TRNAG-UCC,NaN,tRNA,NaN,NaN
90735,GENE ID:124905886,TRNAG-UCC,NaN,tRNA,NaN,NaN
90732,GENE ID:124905883,TRNAG-UCC,NaN,tRNA,NaN,NaN
90741,GENE ID:124905892,TRNAG-UCC,NaN,tRNA,NaN,NaN
90738,GENE ID:124905889,TRNAG-UCC,NaN,tRNA,NaN,NaN
90755,GENE ID:124905906,TRNAL-CAG,NaN,tRNA,NaN,NaN
90781,GENE ID:124905932,TRNAL-CAG,NaN,tRNA,NaN,NaN
90779,GENE ID:124905930,TRNAL-CAG,NaN,tRNA,NaN,NaN
90777,GENE ID:124905928,TRNAL-CAG,NaN,tRNA,NaN,NaN
90775,GENE ID:124905926,TRNAL-CAG,NaN,tRNA,NaN,NaN
90773,GENE ID:124905924,TRNAL-CAG,NaN,tRNA,NaN,NaN
90758,GENE ID:124905909,TRNAL-CAG,NaN,tRNA,NaN,NaN
90771,GENE ID:124905922,TRNAL-CAG,NaN,tRNA,NaN,NaN
90766,GENE ID:124905917,TRNAL-CAG,NaN,tRNA,NaN,NaN
90769,GENE ID:124905920,TRNAL-CAG,NaN,tRNA,NaN,NaN
90701,GENE ID:124905852,TRNAL-CAG,NaN,tRNA,NaN,NaN
90764,GENE ID:124905915,TRNAL-CAG,NaN,tRNA,NaN,NaN
90699,GENE ID:124905850,TRNAL-CAG,NaN,tRNA,NaN,NaN
90762,GENE ID:124905913,TRNAL-CAG,NaN,tRNA,NaN,NaN
90697,GENE ID:124905848,TRNAL-CAG,NaN,tRNA,NaN,NaN
90760,GENE ID:124905911,TRNAL-CAG,NaN,tRNA,NaN,NaN
90783,GENE ID:124905934,TRNAL-CAG,NaN,tRNA,NaN,NaN
90689,GENE ID:124905582,TRNAN-GUU,NaN,tRNA,NaN,NaN
90694,GENE ID:124905587,TRNAN-GUU,NaN,tRNA,NaN,NaN
90692,GENE ID:124905585,TRNAN-GUU,NaN,tRNA,NaN,NaN
90686,GENE ID:124905579,TRNAN-GUU,NaN,tRNA,NaN,NaN
89322,GENE ID:107985614,TRNAV-CAC,NaN,tRNA,NaN,NaN
89323,GENE ID:107985615,TRNAV-CAC,NaN,tRNA,NaN,NaN

How many ambiguous symbols result from alias-primary collisions?

In [99]:
ap_collision_ambiguous_symbol_set_ncbi = set(
    merged_alias_ap_collision_ncbi_df["collision"]
)
ap_collision_ambiguous_symbol_count_ncbi = len(ap_collision_ambiguous_symbol_set_ncbi)
ap_collision_ambiguous_symbol_count_ncbi

1394

How many records have at least one alias-primary collision (alias that matches another record's primary gene symbol)?

In [100]:
ap_record_set_ncbi = set(merged_alias_ap_collision_ncbi_df["NCBI_ID"])
ap_record_count_ncbi = len(ap_record_set_ncbi)
ap_record_count_ncbi

1613

# <a id='toc4_'></a>[Merge 3 sets together](#toc0_)

In [101]:
merged_alias_primary_collisions_df = pd.concat(
    [
        merged_alias_ap_collision_hgnc_df[
            ["primary_gene_symbol", "alias_symbol", "collision", "source", "ENSG_ID", "HGNC_ID", "NCBI_ID"]
        ],
        merged_alias_ap_collision_ncbi_df[
            ["primary_gene_symbol", "alias_symbol", "collision", "source", "ENSG_ID", "HGNC_ID", "NCBI_ID"]
        ],
        merged_alias_ap_collision_ensg_df[
            ["primary_gene_symbol", "alias_symbol", "collision", "source", "ENSG_ID", "HGNC_ID", "NCBI_ID"]
        ],
    ]
)
merged_alias_primary_collisions_df

,primary_gene_symbol,alias_symbol,collision,source,ENSG_ID,HGNC_ID,NCBI_ID
0,PPP1R12C,"AAVS1,DKFZP434D0412,MBS85,p84,p85",AAVS1,HGNC,ENSG00000125503,HGNC:14947,GENE ID:54776
1,SOAT1,"ACAT,ACAT1",ACAT1,HGNC,ENSG00000057252,HGNC:11177,GENE ID:6646
2,SOAT2,ACAT2,ACAT2,HGNC,ENSG00000167780,HGNC:11178,GENE ID:8435
3,CCRL2,"ACKR5,CKRX,CRAM-A,CRAM-B,HCR",ACKR5,HGNC,ENSG00000121797,HGNC:1612,GENE ID:9034
4,NDUFAB1,"ACP,ACP1,FASN2A,SDAP",ACP1,HGNC,ENSG00000004779,HGNC:7694,GENE ID:4706
...,...,...,...,...,...,...,...
762,ZNF121,"D19S204,ZHC32,ZNF20",ZNF20,ENSG,ENSG00000197961,HGNC:12904,GENE ID:7675
763,RNF141,"ZFP26,ZNF230",ZNF230,ENSG,ENSG00000110315,HGNC:21159,GENE ID:50862
764,ZNF322P1,"ZNF322,ZNF322B",ZNF322,ENSG,ENSG00000188801,HGNC:14003,NaN
765,ZNF106,"SH3BP3,ZFP106,ZNF474",ZNF474,ENSG,ENSG00000103994,HGNC:12886,GENE ID:64397
766,ZFP1,"FLJ34243,ZNF475",ZNF475,ENSG,ENSG00000184517,HGNC:23328,GENE ID:162239

In [102]:
merged_alias_primary_collisions_df.loc[
    merged_alias_primary_collisions_df["collision"] == "KRAS"
]

,primary_gene_symbol,alias_symbol,collision,source,ENSG_ID,HGNC_ID,NCBI_ID
647,NRAS,"ALPS4,CMNS,KRAS,N-ras,NCMS,NRAS1,NS6",KRAS,NCBI,ENSG00000213281,HGNC:7989,GENE ID:4893

# <a id='toc5_'></a>[Convert to csv](#toc0_)

In [103]:
merged_alias_primary_collisions_df.to_csv(
    "../output/merged_alias_primary_collisions_df.csv", index=False
)

In [104]:
common_ap_collision_ambiguous_symbol_set = (
    ap_collision_ambiguous_symbol_set_ncbi
    & ap_collision_ambiguous_symbol_set_hgnc
    & ap_collision_ambiguous_symbol_set_ensg
)
common_ap_collision_ambiguous_symbol_set

{'ACAT1',
 'ACAT2',
 'ACP1',
 'ACTBP2',
 'ADA2',
 'ADRA1A',
 'AGT',
 'AIP',
 'ALB',
 'AMN',
 'APC2',
 'AR',
 'ARC',
 'ARG1',
 'ARHGAP10',
 'ARL1',
 'ARSB',
 'ASIP',
 'ATF1',
 'ATR',
 'AVP',
 'B3GNT8',
 'BACH1',
 'BAP1',
 'BCAM',
 'BCRP1',
 'BCRP2',
 'BDP1',
 'BNC1',
 'BRAP',
 'BRCC3',
 'BRI3',
 'BST1',
 'BTF3',
 'C6',
 'C7',
 'CA11',
 'CABP1',
 'CAD',
 'CAMP',
 'CAP1',
 'CAP2',
 'CAPS',
 'CAPS2',
 'CARF',
 'CAST',
 'CBLC',
 'CCR10',
 'CCR4',
 'CDH1',
 'CDH20',
 'CDH7',
 'CDKN1A',
 'CDS1',
 'CES2',
 'CHD5',
 'CHL1',
 'CHP1',
 'CIC',
 'CKLF',
 'CLC',
 'CLCP1',
 'CLIP4',
 'CNP',
 'CNR1',
 'CNR2',
 'COP1',
 'CPA3',
 'CPA6',
 'CPD',
 'CPN1',
 'CPN2',
 'CPS1',
 'CREB3',
 'CRIP1',
 'CRP',
 'CSN2',
 'CSN3',
 'CSNK2A1',
 'CST6',
 'CSTP1',
 'CTAGE4',
 'CTH',
 'DAO',
 'DAP',
 'DAP3',
 'DBI',
 'DBP',
 'DEF6',
 'DIO1',
 'DLC1',
 'DMC1',
 'DMP1',
 'DOK1',
 'DRC3',
 'DRG1',
 'DRP2',
 'DSC1',
 'DUSP1',
 'DUSP23',
 'DUSP26',
 'EAF2',
 'EBP',
 'ECD',
 'EIF2A',
 'ELF1',
 'ELK1',
 'ELN',
 'EMB',
 'EPO',
 'F11',
 'F3',
 'FAAH',
 'FABP5',
 'FADS6',
 'FAH',
 'FAS',
 'FBP2',
 'FBXO31',
 'FCRL2',
 'FEM1A',
 'FEZ1',
 'FGF2',
 'FLG',
 'FLI1',
 'FZD3',
 'GAB1',
 'GAL',
 'GAL3ST2',
 'GALNT15',
 'GALNT17',
 'GAR1',
 'GCK',
 'GCKR',
 'GCOM1',
 'GDA',
 'GEM',
 'GIP',
 'GK2',
 'GLA',
 'GLS',
 'GLUD1',
 'GLUD2',
 'GOT1',
 'GPI',
 'GPT',
 'GPX6',
 'GRIN1',
 'GRIP1',
 'GRP',
 'GSG1',
 'HAP1',
 'HAS1',
 'HBM',
 'HCP5',
 'HCRTR2',
 'HCST',
 'HDC',
 'HES1',
 'HGF',
 'HK1',
 'HK2',
 'HK3',
 'HLA-H',
 'HLF',
 'HP',
 'HPCA',
 'HPF1',
 'HRG',
 'HRH1',
 'HSD17B7',
 'HTRA3',
 'IFNA13',
 'IK',
 'IL25',
 'IMP3',
 'IMP4',
 'IQCH',
 'ISY1',
 'KLF14',
 'KLHL6',
 'KLK7',
 'KRTAP5-1',
 'KRTAP5-11',
 'KRTAP5-2',
 'KRTAP5-3',
 'KRTAP5-8',
 'KRTAP5-9',
 'KSR2',
 'LAMA3',
 'LAT',
 'LAT2',
 'LBH',
 'LCP1',
 'LDB1',
 'LIG1',
 'LIPA',
 'LNP1',
 'LRP1',
 'LRP2BP',
 'LRP4',
 'MADD',
 'MAFA',
 'MAK',
 'MAL',
 'MAP1A',
 'MAP2',
 'MAS1',
 'MAST1',
 'MBP',
 'ME1',
 'ME2',
 'ME3',
 'MED1',
 'MED24',
 'MED25',
 'MET',
 'MGA',
 'MGAT1',
 'MGAT2',
 'MGAT3',
 'MIA2',
 'MIF',
 'MIP',
 'MLC1',
 'MLN',
 'MOS',
 'MPDZ',
 'MPP1',
 'MPP2',
 'MPP4',
 'MPP7',
 'MRPL27',
 'MRPS28',
 'MRPS35',
 'MS4A10',
 'MS4A7',
 'MS4A8',
 'MSL1',
 'MST1',
 'MTCP1',
 'MTF1',
 'MYH14',
 'MYNN',
 'MYO1C',
 'MYT1',
 'NAF1',
 'NANOGP2',
 'NANOGP3',
 'NANOGP4',
 'NAPA',
 'NAPB',
 'NARF',
 'NAT1',
 'NAT2',
 'NBN',
 'NET1',
 'NGB',
 'NLK',
 'NMB',
 'NME1',
 'NMI',
 'NOP9',
 'NOS1',
 'NOS2',
 'NOS3',
 'NPR2',
 'NPR3',
 'NRAP',
 'NRF1',
 'NRP2',
 'NSL1',
 'NTN4',
 'ODC1',
 'OPA1',
 'ORC1',
 'OSM',
 'OSR1',
 'OXR1',
 'PAK1',
 'PAK3',
 'PAK5',
 'PAM',
 'PAN2',
 'PAN3',
 'PC',
 'PCM1',
 'PDF',
 'PDK1',
 'PDP1',
 'PDX1',
 'PGAM1',
 'PGP',
 'PGS1',
 'PIGF',
 'PIM1',
 'PISD',
 'PKD2',
 'PLAC8',
 'PMP22',
 'PMS2P13',
 'PNP',
 'POLK',
 'POLQ',
 'POMP',
 'POP1',
 'POP4',
 'POR',
 'PPAT',
 'PPOX',
 'PRB1',
 'PRDX6',
 'PREP',
 'PRG2',
 'PRG3',
 'PRR4',
 'PRX',
 'PSAP',
 'PSG1',
 'PTH2',
 'PTPRO',
 'PVALB',
 'RAC1',
 'RAC3',
 'RAD1',
 'RAE1',
 'RAF1',
 'RAI1',
 'RASSF4',
 'RAX',
 'RBM5-AS1',
 'RBP1',
 'RBP2',
 'RBP3',
 'REN',
 'RFC1',
 'RGP1',
 'RGR',
 'RGS13',
 'RHEB',
 'RHO',
 'RIF1',
 'RILP',
 'RLF',
 'RNASE9',
 'ROR1',
 'RP1',
 'RP2',
 'RPA1',
 'RPA2',
 'RPF1',
 'RPL10',
 'RPL13',
 'RPL17',
 'RPL23',
 'RPL24',
 'RPN1',
 'RPN2',
 'RPS12',
 'RRP1',
 'RS1',
 'S100A16',
 'SAG',
 'SAP130',
 'SAT2',
 'SCAF1',
 'SCP2',
 'SCYL1',
 'SCYL2',
 'SCYL3',
 'SDS',
 'SELP',
 'SF1',
 'SF3B1',
 'SFN',
 'SI',
 'SIT1',
 'SKP2',
 'SLA',
 'SLIT1',
 'SLIT3',
 'SLK',
 'SMAD1',
 'SMAP2',
 'SMO',
 'SMS',
 'SNORA58B',
 'SNORD115-48',
 'SNURF',
 'SNX30',
 'SP110',
 'SPATA8',
 'SPN',
 'SPP1',
 'SPP2',
 'SPR',
 'SRA1',
 'SRM',
 'ST7',
 'STAG1',
 'STAR',
 'STK3',
 'STRAP',
 'TAF4B',
 'TAP1',
 'TAP2',
 'TEN1',
 'TEP1',
 'TF',
 'THY1-AS1',
 'TIFA',
 'TKT',
 'TNFRSF11B',
 'TNNC1',
 'TPH2',
 'TPO',
 'TPP1',
 'TPRKB',
 'TRAP1',
 'TRAV11',
 'TSN',
 'TTF1',
 'UCN2',
 'UGT2B11',
 'USE1',
 'USP10',
 'USP16',
 'USP21',
 'VIP',
 'WBP1',
 'ZNF20',
 'ZNF230',
 'ZNF474',
 'ZNF475'}

In [105]:
len(common_ap_collision_ambiguous_symbol_set)

434