**Table of contents**<a id='toc0_'></a>    
- [Gene Symbol Capture Transformation](#toc1_)    
    - [Transforming symbol capture data into a table to be used as a sqlite file for a gene symbol relationship look up tool](#toc1_1_1_)    
  - [Set Up](#toc1_2_)    
    - [Import packages](#toc1_2_1_)    
    - [Define Functions](#toc1_2_2_)    
  - [Download gene records](#toc1_3_)    
    - [Ensembl gene records](#toc1_3_1_)    
      - [Combine symbols (primary and aliases) into one column](#toc1_3_1_1_)    
      - [Combine concept ids( HGNC_ID, ENSG_ID, NCBI_ID) into one column](#toc1_3_1_2_)    
    - [HGNC gene records](#toc1_3_2_)    
      - [Combine symbols (primary and aliases) into one column](#toc1_3_2_1_)    
      - [Combine concept ids( HGNC_ID, ENSG_ID, NCBI_ID) into one column](#toc1_3_2_2_)    
    - [NCBI gene records](#toc1_3_3_)    
      - [Combine symbols (primary and aliases) into one column](#toc1_3_3_1_)    
      - [Combine concept ids( HGNC_ID, ENSG_ID, NCBI_ID) into one column](#toc1_3_3_2_)    
      - [Remove records with no associated gene symbols](#toc1_3_3_3_)    
  - [Combine gene records from Ensembl, HGNC, and NCBI](#toc1_4_)    
      - [Dropped duplicate rows and rows with no gene symbols.](#toc1_4_1_1_)    
  - [Add Ortholog relationship label](#toc1_5_)    
    - [Import ortholog sets](#toc1_5_1_)    
    - [Combine all species orthologs into one table](#toc1_5_2_)    
    - [Add Ortholog label to the table of gene records](#toc1_5_3_)    
  - [Add HGNC Previous Symbol relationship label](#toc1_6_)    
    - [Import the expired HGNC symbols](#toc1_6_1_)    
    - [Add HGNC Previous Symbol label to the table of gene records](#toc1_6_2_)    
  - [Add FLJ Clone Symbol label](#toc1_7_)    
    - [Import the FLJ Clone symbols](#toc1_7_1_)    
    - [Add FLJ Clone Symbol label to the table of gene records](#toc1_7_2_)    
  - [Add Gene Family Symbol label](#toc1_8_)    
    - [Import the Gene Family Root symbols](#toc1_8_1_)    
  - [Add Phenotype Symbol label](#toc1_9_)    
    - [Import the Phenotype root symbols](#toc1_9_1_)    

<!-- vscode-jupyter-toc-config
	numbering=false
	anchor=true
	flat=false
	minLevel=1
	maxLevel=6
	/vscode-jupyter-toc-config -->
<!-- THIS CELL WILL BE REPLACED ON TOC UPDATE. DO NOT WRITE YOUR TEXT IN THIS CELL -->

# <a id='toc1_'></a>[Gene Symbol Capture Transformation](#toc0_)

### <a id='toc1_1_1_'></a>[Transforming symbol capture data into a table to be used as a sqlite file for a gene symbol relationship look up tool](#toc0_)

this table is denormalized compared to the table in symbol_capture_generation.ipynb

## <a id='toc1_2_'></a>[Set Up](#toc0_)

### <a id='toc1_2_1_'></a>[Import packages](#toc0_)

In [1]:
import pandas as pd
import numpy as np
from tqdm import tqdm
import glob
import os
import plotly.express as px

### <a id='toc1_2_2_'></a>[Define Functions](#toc0_)

In [2]:
def combine_columns(df, columns_to_combine, columns_to_keep, new_name, columns_to_drop):
    """Combine multiple columns into one while keeping associated data attached.
    Use this function when the columns to combine are easier to list 
    than the columns not to combine.
    
    :param df: The DataFrame containing the columns to be combined
    :param columns_to_combine: List of column names to combine into one
    :param columns_to_keep: List of columns to keep in the final DataFrame
    :param new_name: The name of the new combined column
    :param columns_to_drop: List of columns to drop from the final DataFrame
    :return: A new DataFrame with combined columns and selected columns retained
    """
    og_df = df.copy()

    combined_dfs = []

    # Loop through each column in columns_to_combine and create a new DataFrame
    for col in columns_to_combine:
        temp_df = og_df[list(set([col] + columns_to_keep))].copy()
        temp_df[new_name] = temp_df[col]
        combined_dfs.append(temp_df)

    df_combined = pd.concat(combined_dfs, ignore_index=True)
    df_combined.drop(columns_to_drop, axis=1, inplace=True)
    df_combined.drop_duplicates(inplace=True)
    
    return df_combined

In [3]:
def combine_columns_except(df, new_name, cols_not_combine):
    """Combine multiple columns into one while keeping associated data attached.
    Use this function when the columns not to combine are easier to list 
    than the columns to combine.

    :param df: The DataFrame containing the columns to be combined
    :param new_name: The name of the new combined column
    :param cols_not_combine: List of columns TO NOT combine from the original DataFrame
    :return: A new DataFrame with combined columns and selected columns retained    
    """

    og_df = df.copy()
    
    columns_to_keep = [col for col in df.columns if col in cols_not_combine]
    columns_to_combine = [col for col in df.columns if col not in columns_to_keep]

    # Loop through each column in columns_to_combine and create a new DataFrame
    combined_df = []
    for col in columns_to_combine:
        temp_df = og_df[list(set([col] + columns_to_keep))].copy()
        temp_df[new_name] = temp_df[col]
        combined_df.append(temp_df)

    df_combined = pd.concat(combined_df, ignore_index=True)
    df_combined.drop(columns=columns_to_combine, axis=1, inplace=True)
    df_combined.drop_duplicates(inplace=True)
    
    return df_combined

In [4]:
def combine_columns_except_multiple(dfs, new_name,cols_not_combine):
    """Apply the combine_columns_except function to several DataFrames and then combine all of those dfs into one.

    :param dfs: The df(s) with the columns to combine (list or dictionary of DataFrames)
    :param new_name: The name of the new combined column
    :param cols_not_combine: List of columns TO NOT combine from the original DataFrame
    :return: A new DataFrame with combined dfs that had combined columns and selected columns retained
    """

    # Convert to list if the input is a dictionary
    if isinstance(dfs, dict):
        dfs = list(dfs.values())
    combined_dfs = []

    # Combine multiple columns into one while keeping associated data attached
    for df in dfs:
        combined_df = combine_columns_except(df, new_name, cols_not_combine)
        combined_dfs.append(combined_df)
    
    # Combine multiple dfs into one
    final_combined_df = pd.concat(combined_dfs, ignore_index=True)

    final_combined_df.drop_duplicates(inplace=True)
    final_combined_df = final_combined_df.dropna(subset=[new_name])

    
    return final_combined_df

In [5]:
def add_relationship_and_source_if_symbol(
    destination_df, relationship_df, destination_df_cols, relationship_df_cols, relationship_val, source_val, combine_with=None
):
    """To add a relationship and source description for gene symbols based on a dataset.
    
    :param destination_df: The DataFrame that is getting the relationships added to it
    :param relationship_df: The DataFrame that is the source of the relationships
    :param destination_df_cols: The columns used to match gene symbols to the relationship_df
    (usually primary gene concept symbol, an identfier, and alternate gene symbol)
    :param relationship_df_cols: The columns used to match gene symbols to the destination_df
    (usually primary gene concept symbol, an identfier, and alternate gene symbol)
    :param relationship_val: Based on the relationship_df, the relationship that a precense of 
    the alternate symbol in the dataset would indicate
    :param source_val: The label to indicate wehre the dataset in relationship_df came from
    :param combine_with: A DataFrame that was a result of this function with a different relationship category(s)
    :return: A new DataFrame with descriptive relationship and source labels

    Notes: 
    - The cols variables need to be in the correct order. The columns to be compared need 
    to be in the same positions in the lists. 
    - There cannot be any shared column names bw relationship_df and destination_df.

    """
    # Create uppercase columns for merging
    for df, cols, suffix in [(destination_df, destination_df_cols, "_upper"), (relationship_df, relationship_df_cols, "_upper")]:
        df[[col + suffix for col in cols]] = df[cols].apply(lambda x: x.str.upper())
    
    # Perform the merge
    merged_df = destination_df.merge(
        relationship_df,
        left_on=[col + "_upper" for col in destination_df_cols],
        right_on=[col + "_upper" for col in relationship_df_cols],
        how="left",
        indicator=True,
    )

    # Assign relationships and sources
    merged_df["relationship"] = merged_df["_merge"].map(lambda x: relationship_val if x == "both" else "")
    merged_df["source"] = merged_df["_merge"].map(lambda x: source_val if x == "both" else "")
    
    # Drop extra columns and remove duplicates
    merged_df.drop(
        columns=[col + "_upper" for col in (destination_df_cols + relationship_df_cols)] + ["_merge"] + relationship_df.columns.tolist(),
        inplace=True
    )
    merged_df.drop_duplicates(inplace=True)

    destination_df.drop(
        columns= [col + "_upper" for col in (destination_df_cols)],
        inplace=True
    )
    relationship_df.drop(
    columns= [col + "_upper" for col in (relationship_df_cols)],
    inplace=True
    )
    # Optionally combine with an existing DataFrame
    if combine_with is not None:
        combined_df = pd.concat([combine_with, merged_df], ignore_index=True).drop_duplicates()
        return combined_df
    
    return merged_df

In [6]:
def add_relationship_and_source_if_prefix(
    destination_df, relationship_df, exact_cols_df1, exact_cols_df2,
    prefix_col_df1, prefix_col_df2, relationship_val, source_val,
    combine_with=None, suffix="_upper"
):
    """
    Compare two DataFrames to find matching rows based on:
    1. Exact matches for specified columns (which can differ between DataFrames).
    2. A single prefix match for a specific column.
    Add relationship and source descriptions for gene symbols.

    :param destination_df: The DataFrame getting relationships added.
    :param relationship_df: The DataFrame as the source of the relationships.
    :param exact_cols_df1: Columns in destination_df requiring exact matches.
    :param exact_cols_df2: Columns in relationship_df requiring exact matches.
    :param prefix_col_df1: Column in destination_df for prefix matching.
    :param prefix_col_df2: Column in relationship_df for prefix matching.
    :param relationship_val: The relationship to assign if a match is found.
    :param source_val: The source label to assign if a match is found.
    :param combine_with: Optionally combine with an existing DataFrame.
    :param suffix: Suffix for new uppercase columns.
    :return: DataFrame with descriptive relationship and source labels.
    """
    # Create uppercase columns for merging
    for df, cols, suffix in [(destination_df, exact_cols_df1 + [prefix_col_df1], "_upper"), (relationship_df, exact_cols_df2 + [prefix_col_df2], "_upper")]:
        df[[col + suffix for col in cols]] = df[cols].apply(lambda x: x.str.upper())
    
    # Merge DataFrames on exact columns
    merged_df = destination_df.merge(
        relationship_df,
        left_on=[col + suffix for col in exact_cols_df1],
        right_on=[col + suffix for col in exact_cols_df2],
        how="left",
        indicator=True,
    )

    # Identify prefix matches and assign relationships
    merged_df["Prefix Match"] = merged_df.apply(
        lambda row: row[prefix_col_df1 + suffix].startswith(
            row[prefix_col_df2 + suffix]
        ) if pd.notna(row[prefix_col_df2 + suffix]) else False,
        axis=1
    )

    # Assign relationships and sources
    merged_df["relationship"] = merged_df.apply(
        lambda row: relationship_val if row["_merge"] == "both" and row["Prefix Match"] else "", axis=1
    )
    merged_df["source"] = merged_df.apply(
        lambda row: source_val if row["_merge"] == "both" and row["Prefix Match"] else "", axis=1
    )

    # Drop extra columns and remove duplicates
    merged_df.drop(
        columns=[col + suffix for col in exact_cols_df1 + exact_cols_df2 + [prefix_col_df1, prefix_col_df2]] 
                + ["_merge", "Prefix Match"] 
                + relationship_df.columns.tolist(),
        inplace=True, errors='ignore'
    )
    merged_df.drop_duplicates(inplace=True)

    destination_df.drop(
        columns=[col + suffix for col in exact_cols_df1 + [prefix_col_df1]], 
        inplace=True, 
        errors='ignore')
    
    relationship_df.drop(
    columns=[col + suffix for col in exact_cols_df2 + [prefix_col_df2]], 
    inplace=True, 
    errors='ignore')

    # Optionally combine with an existing DataFrame
    if combine_with is not None:
        combined_df = pd.concat([combine_with, merged_df], ignore_index=True).drop_duplicates()
        return combined_df

    return merged_df

## <a id='toc1_3_'></a>[Download gene records](#toc0_)

### <a id='toc1_3_1_'></a>[Ensembl gene records](#toc0_)

In [7]:
mini_ensg_df = pd.read_csv(
    "../output/mini_ensg_df.csv", sep=","
)
mini_ensg_df

,ENSG_ID,NCBI_ID,HGNC_ID,alias_symbol,primary_gene_symbol
0,ENSG00000210049,NaN,HGNC:7481,MTTF,MT-TF
1,ENSG00000210049,NaN,HGNC:7481,TRNF,MT-TF
2,ENSG00000211459,NaN,HGNC:7470,12S,MT-RNR1
3,ENSG00000211459,NaN,HGNC:7470,MOTS-C,MT-RNR1
4,ENSG00000211459,NaN,HGNC:7470,MTRNR1,MT-RNR1
...,...,...,...,...,...
95019,ENSG00000197989,GENE ID:85028,HGNC:30062,LINC00100,SNHG12
95020,ENSG00000197989,GENE ID:85028,HGNC:30062,PNAS-123,SNHG12
95021,ENSG00000229388,NaN,HGNC:52502,LINC01715,TAF12-DT
95022,ENSG00000274978,GENE ID:26824,HGNC:10108,RNU11-1,RNU11
95023,ENSG00000274978,GENE ID:26824,HGNC:10108,U11,RNU11

#### <a id='toc1_3_1_1_'></a>[Combine symbols (primary and aliases) into one column](#toc0_)

so that there is a generic symbol column representing all symbols associate with a gene concept.

In [8]:
ensg_combined_symbols_df = combine_columns(mini_ensg_df, ['primary_gene_symbol','alias_symbol'], ['primary_gene_symbol', 'HGNC_ID', 'ENSG_ID', 'NCBI_ID'], "gene_symbol", "alias_symbol")
ensg_combined_symbols_df.head()

   primary_gene_symbol    HGNC_ID          ENSG_ID NCBI_ID gene_symbol
0                MT-TF  HGNC:7481  ENSG00000210049     NaN       MT-TF
2              MT-RNR1  HGNC:7470  ENSG00000211459     NaN     MT-RNR1
5                MT-TV  HGNC:7500  ENSG00000210077     NaN       MT-TV
7              MT-RNR2  HGNC:7471  ENSG00000210082     NaN     MT-RNR2
10              MT-TL1  HGNC:7490  ENSG00000209082     NaN      MT-TL1

In [9]:
ensg_combined_symbols_df.loc[ensg_combined_symbols_df["primary_gene_symbol"]== "C3"]

,primary_gene_symbol,HGNC_ID,ENSG_ID,NCBI_ID,gene_symbol
66246,C3,HGNC:1318,ENSG00000125730,GENE ID:718,C3
161270,C3,HGNC:1318,ENSG00000125730,GENE ID:718,ARMD9
161271,C3,HGNC:1318,ENSG00000125730,GENE ID:718,C3A
161272,C3,HGNC:1318,ENSG00000125730,GENE ID:718,C3B
161273,C3,HGNC:1318,ENSG00000125730,GENE ID:718,CPAMD1

Make a table for concordance analysis

In [10]:
ensg_combined_symbols_df.to_csv(
    "../output/ensg_combined_symbols_df.csv", index=False)

#### <a id='toc1_3_1_2_'></a>[Combine concept ids( HGNC_ID, ENSG_ID, NCBI_ID) into one column](#toc0_)

In [11]:
ensg_combined_concept_ids_df = combine_columns(ensg_combined_symbols_df, ["HGNC_ID", "ENSG_ID", "NCBI_ID"], ['primary_gene_symbol',"gene_symbol"], "concept_id", ["HGNC_ID", "ENSG_ID", "NCBI_ID"])
ensg_combined_concept_ids_df.head()

  primary_gene_symbol gene_symbol concept_id
0               MT-TF       MT-TF  HGNC:7481
1             MT-RNR1     MT-RNR1  HGNC:7470
2               MT-TV       MT-TV  HGNC:7500
3             MT-RNR2     MT-RNR2  HGNC:7471
4              MT-TL1      MT-TL1  HGNC:7490

In [12]:
ensg_combined_concept_ids_df.to_csv(
    "../output/ensg_combined_concept_ids_df.csv", index=False)

Creating table for cytoscape

In [13]:
ensg_combined_hgnc_ncbi_concept_ids_df = combine_columns(ensg_combined_symbols_df, ["HGNC_ID", "NCBI_ID"], ["gene_symbol","ENSG_ID"], "xref_concept_id", ["HGNC_ID", "NCBI_ID"])
ensg_combined_symbol_xref_concept_ids_df = combine_columns(ensg_combined_hgnc_ncbi_concept_ids_df, ["gene_symbol", "xref_concept_id"], ["ENSG_ID"], "target", ["gene_symbol", "xref_concept_id"])
ensg_combined_symbol_xref_concept_ids_df["source"] = ensg_combined_symbol_xref_concept_ids_df["ENSG_ID"]
ensg_combined_symbol_xref_concept_ids_df = ensg_combined_symbol_xref_concept_ids_df.drop(columns =["ENSG_ID"])
ensg_combined_symbol_xref_concept_ids_df.loc[ensg_combined_symbol_xref_concept_ids_df["source"]== "ENSG00000125730"]

             target           source
32889            C3  ENSG00000125730
109956        ARMD9  ENSG00000125730
109957          C3A  ENSG00000125730
109958          C3B  ENSG00000125730
109959       CPAMD1  ENSG00000125730
315553    HGNC:1318  ENSG00000125730
454621  GENE ID:718  ENSG00000125730

### <a id='toc1_3_2_'></a>[HGNC gene records](#toc0_)

In [14]:
mini_hgnc_df = pd.read_csv(
    "../output/mini_hgnc_df.csv", sep=","
)
mini_hgnc_df

,HGNC_ID,primary_gene_symbol,alias_symbol,NCBI_ID,ENSG_ID
0,HGNC:100,ASIC1,BNaC2,GENE ID:41,ENSG00000110881
1,HGNC:100,ASIC1,hBNaC2,GENE ID:41,ENSG00000110881
2,HGNC:10000,RGS4,NaN,GENE ID:5999,ENSG00000117152
3,HGNC:10001,RGS5,NaN,GENE ID:8490,ENSG00000143248
4,HGNC:10002,RGS6,NaN,GENE ID:9628,ENSG00000182732
...,...,...,...,...,...
66194,HGNC:9997,RGS16,RGS-r,GENE ID:6004,ENSG00000143333
66195,HGNC:9998,RGS2,NaN,GENE ID:5997,ENSG00000116741
66196,HGNC:9999,RGS3,C2PA,GENE ID:5998,ENSG00000138835
66197,HGNC:9999,RGS3,FLJ20370,GENE ID:5998,ENSG00000138835
66198,HGNC:9999,RGS3,PDZ-RGS3,GENE ID:5998,ENSG00000138835

#### <a id='toc1_3_2_1_'></a>[Combine symbols (primary and aliases) into one column](#toc0_)

so that there is a generic symbol column representing all symbols associate with a gene concept.

In [15]:
hgnc_combined_symbols_df = combine_columns(mini_hgnc_df, ['primary_gene_symbol','alias_symbol'], ['primary_gene_symbol', 'HGNC_ID', 'ENSG_ID', 'NCBI_ID'], "gene_symbol", "alias_symbol")
hgnc_combined_symbols_df.head()

  primary_gene_symbol     HGNC_ID          ENSG_ID       NCBI_ID gene_symbol
0               ASIC1    HGNC:100  ENSG00000110881    GENE ID:41       ASIC1
2                RGS4  HGNC:10000  ENSG00000117152  GENE ID:5999        RGS4
3                RGS5  HGNC:10001  ENSG00000143248  GENE ID:8490        RGS5
4                RGS6  HGNC:10002  ENSG00000182732  GENE ID:9628        RGS6
5                RGS7  HGNC:10003  ENSG00000182901  GENE ID:6000        RGS7

In [16]:
hgnc_combined_symbols_df.loc[hgnc_combined_symbols_df["primary_gene_symbol"] == "C3"]

      primary_gene_symbol    HGNC_ID          ENSG_ID      NCBI_ID gene_symbol
5726                   C3  HGNC:1318  ENSG00000125730  GENE ID:718          C3
71925                  C3  HGNC:1318  ENSG00000125730  GENE ID:718      CPAMD1
71926                  C3  HGNC:1318  ENSG00000125730  GENE ID:718       ARMD9
71927                  C3  HGNC:1318  ENSG00000125730  GENE ID:718         C3a
71928                  C3  HGNC:1318  ENSG00000125730  GENE ID:718         C3b

Make a table for concordance analysis

In [17]:
hgnc_combined_symbols_df.to_csv(
    "../output/hgnc_combined_symbols_df.csv"
)

#### <a id='toc1_3_2_2_'></a>[Combine concept ids( HGNC_ID, ENSG_ID, NCBI_ID) into one column](#toc0_)

In [18]:
hgnc_combined_concept_ids_df = combine_columns(hgnc_combined_symbols_df, ["HGNC_ID", "ENSG_ID", "NCBI_ID"], ['primary_gene_symbol',"gene_symbol"], "concept_id", ["HGNC_ID", "ENSG_ID", "NCBI_ID"])
hgnc_combined_concept_ids_df.head()

  primary_gene_symbol gene_symbol  concept_id
0               ASIC1       ASIC1    HGNC:100
1                RGS4        RGS4  HGNC:10000
2                RGS5        RGS5  HGNC:10001
3                RGS6        RGS6  HGNC:10002
4                RGS7        RGS7  HGNC:10003

In [19]:
hgnc_combined_concept_ids_df.to_csv(
    "../output/hgnc_combined_concept_ids_df.csv", index=False)

Creating table for cytoscape

In [20]:
hgnc_combined_hgnc_ncbi_concept_ids_df = combine_columns(hgnc_combined_symbols_df, ["ENSG_ID", "NCBI_ID"], ["gene_symbol","HGNC_ID"], "xref_concept_id", ["ENSG_ID", "NCBI_ID"])
hgnc_combined_hgnc_ncbi_concept_ids_df.head()
hgnc_combined_symbol_xref_concept_ids_df = combine_columns(hgnc_combined_hgnc_ncbi_concept_ids_df, ["gene_symbol", "xref_concept_id"], ["HGNC_ID"], "target", ["gene_symbol", "xref_concept_id"])
hgnc_combined_symbol_xref_concept_ids_df["source"] = hgnc_combined_symbol_xref_concept_ids_df["HGNC_ID"]
hgnc_combined_symbol_xref_concept_ids_df = hgnc_combined_symbol_xref_concept_ids_df.drop(columns =["HGNC_ID"])
hgnc_combined_symbol_xref_concept_ids_df.loc[hgnc_combined_symbol_xref_concept_ids_df["source"]== "HGNC:1318"]

                 target     source
2727                 C3  HGNC:1318
49954            CPAMD1  HGNC:1318
49955             ARMD9  HGNC:1318
49956               C3a  HGNC:1318
49957               C3b  HGNC:1318
222975  ENSG00000125730  HGNC:1318
333393      GENE ID:718  HGNC:1318

### <a id='toc1_3_3_'></a>[NCBI gene records](#toc0_)

In [21]:
mini_ncbi_df = pd.read_csv(
    "../output/mini_ncbi_df.csv", sep=","
)
mini_ncbi_df

,NCBI_ID,primary_gene_symbol,alias_symbol,gene_type,HGNC_ID,ENSG_ID
0,GENE ID:1,A1BG,A1B,protein-coding,HGNC:5,ENSG00000121410
1,GENE ID:1,A1BG,ABG,protein-coding,HGNC:5,ENSG00000121410
2,GENE ID:1,A1BG,GAB,protein-coding,HGNC:5,ENSG00000121410
3,GENE ID:1,A1BG,HYST2477,protein-coding,HGNC:5,ENSG00000121410
4,GENE ID:2,A2M,A2MD,protein-coding,HGNC:7,ENSG00000175899
...,...,...,...,...,...,...
91350,GENE ID:141732005,ADCY2-AS1,NaN,ncRNA,HGNC:40064,NaN
91351,GENE ID:141732006,NSG2-AS1,NaN,ncRNA,HGNC:41074,NaN
91352,GENE ID:141732007,ST18-AS1,NaN,ncRNA,HGNC:58430,NaN
91353,GENE ID:141732008,MICAL2-AS1,NaN,ncRNA,HGNC:58437,NaN
91354,GENE ID:141732009,TRIM41-AS1,NaN,ncRNA,HGNC:40863,NaN

#### <a id='toc1_3_3_1_'></a>[Combine symbols (primary and aliases) into one column](#toc0_)

so that there is a generic symbol column representing all symbols associate with a gene concept.

In [22]:
ncbi_combined_symbols_df = combine_columns(mini_ncbi_df, ['primary_gene_symbol','alias_symbol'], ['primary_gene_symbol', 'HGNC_ID', 'ENSG_ID', 'NCBI_ID'], "gene_symbol", "alias_symbol")
ncbi_combined_symbols_df.head()

   primary_gene_symbol    HGNC_ID          ENSG_ID     NCBI_ID gene_symbol
0                 A1BG     HGNC:5  ENSG00000121410   GENE ID:1        A1BG
4                  A2M     HGNC:7  ENSG00000175899   GENE ID:2         A2M
8                 NAT1  HGNC:7645  ENSG00000171428   GENE ID:9        NAT1
12                NAT2  HGNC:7646  ENSG00000156006  GENE ID:10        NAT2
15                NATP    HGNC:15              NaN  GENE ID:11        NATP

In [23]:
ncbi_combined_symbols_df.loc[ncbi_combined_symbols_df["primary_gene_symbol"]== "C3"]

      primary_gene_symbol    HGNC_ID          ENSG_ID      NCBI_ID gene_symbol
2032                   C3  HGNC:1318  ENSG00000125730  GENE ID:718          C3
93387                  C3  HGNC:1318  ENSG00000125730  GENE ID:718       AHUS5
93388                  C3  HGNC:1318  ENSG00000125730  GENE ID:718       ARMD9
93389                  C3  HGNC:1318  ENSG00000125730  GENE ID:718         ASP
93390                  C3  HGNC:1318  ENSG00000125730  GENE ID:718         C3a
93391                  C3  HGNC:1318  ENSG00000125730  GENE ID:718         C3b
93392                  C3  HGNC:1318  ENSG00000125730  GENE ID:718      CPAMD1
93393                  C3  HGNC:1318  ENSG00000125730  GENE ID:718   HEL-S-62p

In [24]:
ncbi_combined_symbols_df.to_csv(
    "../output/ncbi_combined_symbols_df.csv", index=False)

#### <a id='toc1_3_3_2_'></a>[Combine concept ids( HGNC_ID, ENSG_ID, NCBI_ID) into one column](#toc0_)

In [25]:
ncbi_combined_concept_ids_df = combine_columns(ncbi_combined_symbols_df, ["HGNC_ID", "ENSG_ID", "NCBI_ID"], ['primary_gene_symbol',"gene_symbol"], "concept_id", ["HGNC_ID", "ENSG_ID", "NCBI_ID"])
ncbi_combined_concept_ids_df.head()

  primary_gene_symbol gene_symbol concept_id
0                A1BG        A1BG     HGNC:5
1                 A2M         A2M     HGNC:7
2                NAT1        NAT1  HGNC:7645
3                NAT2        NAT2  HGNC:7646
4                NATP        NATP    HGNC:15

#### <a id='toc1_3_3_3_'></a>[Remove records with no associated gene symbols](#toc0_)

In [26]:
ncbi_combined_concept_ids_df.loc[ncbi_combined_concept_ids_df["gene_symbol"] == "-"]

Empty DataFrame
Columns: [primary_gene_symbol, gene_symbol, concept_id]
Index: []

In [27]:
ncbi_combined_concept_ids_df.to_csv(
    "../output/ncbi_combined_concept_ids_df.csv", index=False)

Creating table for cytoscape

In [28]:
ncbi_combined_hgnc_ncbi_concept_ids_df = combine_columns(ncbi_combined_symbols_df, ["ENSG_ID", "HGNC_ID"], ["gene_symbol","NCBI_ID"], "xref_concept_id", ["ENSG_ID", "HGNC_ID"])
ncbi_combined_hgnc_ncbi_concept_ids_df.head()
ncbi_combined_symbol_xref_concept_ids_df = combine_columns(ncbi_combined_hgnc_ncbi_concept_ids_df, ["gene_symbol", "xref_concept_id"], ["NCBI_ID"], "target", ["gene_symbol", "xref_concept_id"])
ncbi_combined_symbol_xref_concept_ids_df["source"] = ncbi_combined_symbol_xref_concept_ids_df["NCBI_ID"]
ncbi_combined_symbol_xref_concept_ids_df = ncbi_combined_symbol_xref_concept_ids_df.drop(columns =["NCBI_ID"])
ncbi_combined_symbol_xref_concept_ids_df.loc[ncbi_combined_symbol_xref_concept_ids_df["source"]== "GENE ID:718"]

                 target       source
566                  C3  GENE ID:718
46660             AHUS5  GENE ID:718
46661             ARMD9  GENE ID:718
46662               ASP  GENE ID:718
46663               C3a  GENE ID:718
46664               C3b  GENE ID:718
46665            CPAMD1  GENE ID:718
46666         HEL-S-62p  GENE ID:718
271798  ENSG00000125730  GENE ID:718
407781        HGNC:1318  GENE ID:718

## <a id='toc1_4_'></a>[Combine gene records from Ensembl, HGNC, and NCBI](#toc0_)

#### <a id='toc1_4_1_1_'></a>[Dropped duplicate rows and rows with no gene symbols.](#toc0_)

In [29]:
genes_df = pd.concat([ensg_combined_concept_ids_df, hgnc_combined_concept_ids_df, ncbi_combined_concept_ids_df], ignore_index=True)
genes_df.drop_duplicates(inplace=True)
genes_df = genes_df.dropna(subset=["gene_symbol","primary_gene_symbol"])
genes_df = genes_df[~genes_df['gene_symbol'].isin(["-", "", " "])].copy()
genes_df

        primary_gene_symbol gene_symbol         concept_id
0                     MT-TF       MT-TF          HGNC:7481
1                   MT-RNR1     MT-RNR1          HGNC:7470
2                     MT-TV       MT-TV          HGNC:7500
3                   MT-RNR2     MT-RNR2          HGNC:7471
4                    MT-TL1      MT-TL1          HGNC:7490
...                     ...         ...                ...
1113158          IFT70A-AS1        AGPS  GENE ID:139281660
1113159          IFT70A-AS1      PDE11A  GENE ID:139281660
1113166            BCAT1-DT   lnc-BCAT1  GENE ID:139281667
1113239              LNCOB1     lnc-OB1  GENE ID:139440214
1113285           LINC03145     CRART16  GENE ID:141445969

[481068 rows x 3 columns]

In [30]:
genes_df.loc[genes_df["primary_gene_symbol"] == "C3"]

        primary_gene_symbol gene_symbol       concept_id
27731                    C3          C3        HGNC:1318
92145                    C3       ARMD9        HGNC:1318
92146                    C3         C3A        HGNC:1318
92147                    C3         C3B        HGNC:1318
92148                    C3      CPAMD1        HGNC:1318
148511                   C3          C3  ENSG00000125730
225574                   C3       ARMD9  ENSG00000125730
225575                   C3         C3A  ENSG00000125730
225576                   C3         C3B  ENSG00000125730
225577                   C3      CPAMD1  ENSG00000125730
282285                   C3          C3      GENE ID:718
350755                   C3       ARMD9      GENE ID:718
350756                   C3         C3A      GENE ID:718
350757                   C3         C3B      GENE ID:718
350758                   C3      CPAMD1      GENE ID:718
425611                   C3         C3a        HGNC:1318
425612                   C3         C3b        HGNC:1318
536031                   C3         C3a  ENSG00000125730
536032                   C3         C3b  ENSG00000125730
646161                   C3         C3a      GENE ID:718
646162                   C3         C3b      GENE ID:718
752887                   C3       AHUS5        HGNC:1318
752889                   C3         ASP        HGNC:1318
752893                   C3   HEL-S-62p        HGNC:1318
888431                   C3       AHUS5  ENSG00000125730
888433                   C3         ASP  ENSG00000125730
888437                   C3   HEL-S-62p  ENSG00000125730
1024021                  C3       AHUS5      GENE ID:718
1024023                  C3         ASP      GENE ID:718
1024027                  C3   HEL-S-62p      GENE ID:718

Creating table for cytoscape

In [31]:
cytoscape_genes_df = pd.concat([ensg_combined_symbol_xref_concept_ids_df, hgnc_combined_symbol_xref_concept_ids_df, ncbi_combined_symbol_xref_concept_ids_df], ignore_index=True)
cytoscape_genes_df.drop_duplicates(inplace=True)
cytoscape_genes_df = cytoscape_genes_df.dropna(subset=["source","target"])
cytoscape_genes_df = cytoscape_genes_df[~cytoscape_genes_df['target'].isin(["-", "", " "])].copy()
cytoscape_genes_df.loc[cytoscape_genes_df["source"].isin(["ENSG00000125730","HGNC:1318","GENE ID:718"])]

                 target           source
32889                C3  ENSG00000125730
109952            ARMD9  ENSG00000125730
109953              C3A  ENSG00000125730
109954              C3B  ENSG00000125730
109955           CPAMD1  ENSG00000125730
168375        HGNC:1318  ENSG00000125730
210289      GENE ID:718  ENSG00000125730
225945               C3        HGNC:1318
273172           CPAMD1        HGNC:1318
273173            ARMD9        HGNC:1318
273174              C3a        HGNC:1318
273175              C3b        HGNC:1318
336334  ENSG00000125730        HGNC:1318
378913      GENE ID:718        HGNC:1318
418853               C3      GENE ID:718
464947            AHUS5      GENE ID:718
464948            ARMD9      GENE ID:718
464949              ASP      GENE ID:718
464950              C3a      GENE ID:718
464951              C3b      GENE ID:718
464952           CPAMD1      GENE ID:718
464953        HEL-S-62p      GENE ID:718
554825  ENSG00000125730      GENE ID:718
593353        HGNC:1318      GENE ID:718

In [32]:
cytoscape_genes_df.to_csv('../output/cytoscape_genes_df.csv', index=False)

## <a id='toc1_5_'></a>[Add Ortholog relationship label](#toc0_)

### <a id='toc1_5_1_'></a>[Import ortholog sets](#toc0_)

created in symbol_capture_generation_df.ipynb

In [33]:
folder_path = "../input/"  
num_files = 10

file_names = [os.path.join(folder_path, f'ortholog_set_{i}_df.txt') for i in range(1, num_files + 1)]

ortholog_set_dfs = {}

for i, file_name in enumerate(file_names, start=1):
    df = pd.read_csv(file_name, index_col=None)  

    ortholog_set_dfs[f'ortholog_set_{i}_df'] = df
    
    globals()[f'ortholog_set_{i}_df'] = df

### <a id='toc1_5_2_'></a>[Combine all species orthologs into one table](#toc0_)

combine all species in table in to one column then combine all tables into one table

TODO: add qualifier and qualifier value columns to indicate species. can also use to indicate phenotype later

In [34]:
combined_ortholog_set_df = combine_columns_except_multiple(ortholog_set_dfs, 'Ortholog', ["Gene name","Gene stable ID"])
combined_ortholog_set_df

        Gene name   Gene stable ID  Ortholog
769       SNORA70  ENSG00000251925   SNORA70
815       SNORA70  ENSG00000251796   SNORA70
1281        MIPEP  ENSG00000027001     MIPEP
1297        KPNA3  ENSG00000102753     KPNA3
1303        CRYL1  ENSG00000165475     CRYL1
...           ...              ...       ...
1174150    CYP4F2  ENSG00000186115  CYP4F162
1174151    CYP4F2  ENSG00000186115  CYP4F155
1174152    CYP4F2  ENSG00000186115  CYP4F163
1174219    CYP2J2  ENSG00000134716   CYP2J89
1174270  LORICRIN  ENSG00000203782  LORICRIN

[97825 rows x 3 columns]

### <a id='toc1_5_3_'></a>[Add Ortholog label to the table of gene records](#toc0_)

a match of an identifier, primary gene symbol, and alternate symbol between the gene records table and the relationship table (ortholog in this case) indicate that the alternate symol is an ortholog.

In [35]:
ortholog_capture_df = add_relationship_and_source_if_symbol(
    genes_df,
    combined_ortholog_set_df,
    ["concept_id", "primary_gene_symbol", "gene_symbol"],
    ["Gene stable ID", "Gene name", "Ortholog"],
    "Ortholog Symbol",
    "Ensembl",
    combine_with=None
)
ortholog_capture_df

       primary_gene_symbol gene_symbol         concept_id relationship source
0                    MT-TF       MT-TF          HGNC:7481
1                  MT-RNR1     MT-RNR1          HGNC:7470
2                    MT-TV       MT-TV          HGNC:7500
3                  MT-RNR2     MT-RNR2          HGNC:7471
4                   MT-TL1      MT-TL1          HGNC:7490
...                    ...         ...                ...          ...    ...
507214          IFT70A-AS1        AGPS  GENE ID:139281660
507215          IFT70A-AS1      PDE11A  GENE ID:139281660
507216            BCAT1-DT   lnc-BCAT1  GENE ID:139281667
507217              LNCOB1     lnc-OB1  GENE ID:139440214
507218           LINC03145     CRART16  GENE ID:141445969

[481068 rows x 5 columns]

## <a id='toc1_6_'></a>[Add HGNC Previous Symbol relationship label](#toc0_)

### <a id='toc1_6_1_'></a>[Import the expired HGNC symbols](#toc0_)

used the table generated in the symbol_capture_generation.ipynb

In [36]:
hgnc_previous_symbols_df = pd.read_hdf(
    "../output/hgnc_previous_symbols_df.h5", key='df'
    )
hgnc_previous_symbols_df

          HGNC ID Approved symbol previous_symbol
1      HGNC:37133        A1BG-AS1      NCRNA00181
1      HGNC:37133        A1BG-AS1          A1BGAS
1      HGNC:37133        A1BG-AS1         A1BG-AS
6      HGNC:23336           A2ML1          CPAMD9
9          HGNC:8           A2MP1            A2MP
...           ...             ...             ...
49065  HGNC:34495          ZSWIM9        C19orf68
49066  HGNC:21224            ZUP1        C6orf113
49066  HGNC:21224            ZUP1           ZUFSP
49071  HGNC:13197            ZWS1             ZWS
49077  HGNC:25820          ZYG11B           ZYG11

[16274 rows x 3 columns]

### <a id='toc1_6_2_'></a>[Add HGNC Previous Symbol label to the table of gene records](#toc0_)

a match of an identifier, primary gene symbol, and alternate symbol between the gene records table and the relationship table (HGNC previous symbol in this case) indicate that the alternate symbol is an expired symbol.

using the ortholog_capture_df to add expired labels to ortholog labels for a complete table

In [37]:
expired_capture_df = add_relationship_and_source_if_symbol(
    ortholog_capture_df,
    hgnc_previous_symbols_df,
    ["concept_id", "primary_gene_symbol", "gene_symbol"],
    ["HGNC ID", "Approved symbol", "previous_symbol"],
    "HGNC Previous Symbol",
    "HGNC",
    ortholog_capture_df
)
expired_capture_df

       primary_gene_symbol gene_symbol       concept_id relationship source
0                    MT-TF       MT-TF        HGNC:7481
1                  MT-RNR1     MT-RNR1        HGNC:7470
2                    MT-TV       MT-TV        HGNC:7500
3                  MT-RNR2     MT-RNR2        HGNC:7471
4                   MT-TL1      MT-TL1        HGNC:7490
...                    ...         ...              ...          ...    ...
925182      ARMCX5-GPRASP2      bHLHb9  ENSG00000286237
925506              NPY4R2       NPY4R  ENSG00000264717
925525             OPN1MW3      OPN1MW  ENSG00000269433
926346             TMSB15C     TMSB15B  ENSG00000269226
926363             DUSP13A      DUSP13  ENSG00000293543

[520632 rows x 5 columns]

example of a gene concept that has alternate symbols representing orthologs and expired symbols

In [38]:
expired_capture_df.loc[expired_capture_df["primary_gene_symbol"] == "ABITRAM"]

,primary_gene_symbol,gene_symbol,concept_id,relationship,source
9609,ABITRAM,ABITRAM,HGNC:1364,,
54076,ABITRAM,C9ORF6,HGNC:1364,,
54077,ABITRAM,CG-8,HGNC:1364,,
54078,ABITRAM,FAM206A,HGNC:1364,,
54079,ABITRAM,FLJ20457,HGNC:1364,,
54080,ABITRAM,SIMIATE,HGNC:1364,,
109097,ABITRAM,ABITRAM,ENSG00000119328,Ortholog Symbol,Ensembl
160346,ABITRAM,C9ORF6,ENSG00000119328,,
160347,ABITRAM,CG-8,ENSG00000119328,,
160348,ABITRAM,FAM206A,ENSG00000119328,Ortholog Symbol,Ensembl
160349,ABITRAM,FLJ20457,ENSG00000119328,,
160350,ABITRAM,SIMIATE,ENSG00000119328,,
227850,ABITRAM,ABITRAM,GENE ID:54942,,
274971,ABITRAM,C9ORF6,GENE ID:54942,,
274972,ABITRAM,CG-8,GENE ID:54942,,
274973,ABITRAM,FAM206A,GENE ID:54942,,
274974,ABITRAM,FLJ20457,GENE ID:54942,,
274975,ABITRAM,SIMIATE,GENE ID:54942,,
326069,ABITRAM,Simiate,HGNC:1364,,
341862,ABITRAM,Simiate,ENSG00000119328,,
371434,ABITRAM,Simiate,GENE ID:54942,,
400363,ABITRAM,C9orf6,HGNC:1364,,
431279,ABITRAM,C9orf6,ENSG00000119328,,
465209,ABITRAM,C9orf6,GENE ID:54942,,
535144,ABITRAM,C9ORF6,HGNC:1364,HGNC Previous Symbol,HGNC
535146,ABITRAM,FAM206A,HGNC:1364,HGNC Previous Symbol,HGNC
590165,ABITRAM,ABITRAM,ENSG00000119328,,
641416,ABITRAM,FAM206A,ENSG00000119328,,
881431,ABITRAM,C9orf6,HGNC:1364,HGNC Previous Symbol,HGNC

## <a id='toc1_7_'></a>[Add FLJ Clone Symbol label](#toc0_)

### <a id='toc1_7_1_'></a>[Import the FLJ Clone symbols](#toc0_)

used the table generated in the symbol_capture_generation.ipynb

In [39]:
flj_clone_symbols_df = pd.read_hdf(
    "../output/flj_clone_symbols_df.h5", key='df'
    )
flj_clone_symbols_df

      Accesion No        ID
0        AK075326  PSEC0001
1        AK075326  FLJ91001
2        AK172724  PSEC0002
3        AK172724  FLJ91002
4        AK075327  PSEC0003
...           ...       ...
30581    AK057825  FLJ25096
30582    AK000479  FLJ20472
30583    AK125921  FLJ43933
30584    AK125959  FLJ43971
30585    AK000594  FLJ20587

[30586 rows x 2 columns]

### <a id='toc1_7_2_'></a>[Add FLJ Clone Symbol label to the table of gene records](#toc0_)

In [40]:
flj_clone_capture_df = add_relationship_and_source_if_symbol(
    expired_capture_df,
    flj_clone_symbols_df,
    ["gene_symbol"],
    ["ID"],
    "FLJ Clone Symbol",
    "FLJ Human cDNA Database",
    expired_capture_df
)
flj_clone_capture_df

,primary_gene_symbol,gene_symbol,concept_id,relationship,source
0,MT-TF,MT-TF,HGNC:7481,,
1,MT-RNR1,MT-RNR1,HGNC:7470,,
2,MT-TV,MT-TV,HGNC:7500,,
3,MT-RNR2,MT-RNR2,HGNC:7471,,
4,MT-TL1,MT-TL1,HGNC:7490,,
...,...,...,...,...,...
966183,FLJ45513,FLJ45513,GENE ID:729220,FLJ Clone Symbol,FLJ Human cDNA Database
984877,GOLM1,PSEC0257,GENE ID:51280,FLJ Clone Symbol,FLJ Human cDNA Database
986875,CYSLTR2,PSEC0146,GENE ID:57105,FLJ Clone Symbol,FLJ Human cDNA Database
988986,ARMC10,PSEC0198,GENE ID:83787,FLJ Clone Symbol,FLJ Human cDNA Database
992121,CCDC107,PSEC0222,GENE ID:203260,FLJ Clone Symbol,FLJ Human cDNA Database

In [41]:
flj_clone_capture_df.loc[flj_clone_capture_df["primary_gene_symbol"] == "MIR99AHG"]

,primary_gene_symbol,gene_symbol,concept_id,relationship,source
6762,MIR99AHG,MIR99AHG,HGNC:1274,,
50375,MIR99AHG,C21ORF34,HGNC:1274,,
50376,MIR99AHG,C21ORF35,HGNC:1274,,
50377,MIR99AHG,DILA1,HGNC:1274,,
50378,MIR99AHG,FLJ38295,HGNC:1274,,
50379,MIR99AHG,LINC00478,HGNC:1274,,
50380,MIR99AHG,MONC,HGNC:1274,,
106056,MIR99AHG,MIR99AHG,ENSG00000215386,,
156548,MIR99AHG,C21ORF34,ENSG00000215386,,
156549,MIR99AHG,C21ORF35,ENSG00000215386,,
156550,MIR99AHG,DILA1,ENSG00000215386,,
156551,MIR99AHG,FLJ38295,ENSG00000215386,,
156552,MIR99AHG,LINC00478,ENSG00000215386,,
156553,MIR99AHG,MONC,ENSG00000215386,,
224977,MIR99AHG,MIR99AHG,GENE ID:388815,,
271248,MIR99AHG,C21ORF34,GENE ID:388815,,
271249,MIR99AHG,C21ORF35,GENE ID:388815,,
271250,MIR99AHG,DILA1,GENE ID:388815,,
271251,MIR99AHG,FLJ38295,GENE ID:388815,,
271252,MIR99AHG,LINC00478,GENE ID:388815,,
271253,MIR99AHG,MONC,GENE ID:388815,,
408002,MIR99AHG,C21orf34,HGNC:1274,,
408003,MIR99AHG,C21orf35,HGNC:1274,,
439138,MIR99AHG,C21orf34,ENSG00000215386,,
439139,MIR99AHG,C21orf35,ENSG00000215386,,
473515,MIR99AHG,C21orf34,GENE ID:388815,,
473516,MIR99AHG,C21orf35,GENE ID:388815,,
483671,MIR99AHG,C21ORF34,HGNC:1274,HGNC Previous Symbol,HGNC
483672,MIR99AHG,C21ORF35,HGNC:1274,HGNC Previous Symbol,HGNC
483673,MIR99AHG,FLJ38295,HGNC:1274,HGNC Previous Symbol,HGNC
483674,MIR99AHG,LINC00478,HGNC:1274,HGNC Previous Symbol,HGNC
519220,MIR99AHG,C21orf34,HGNC:1274,HGNC Previous Symbol,HGNC
519221,MIR99AHG,C21orf35,HGNC:1274,HGNC Previous Symbol,HGNC
571010,MIR99AHG,FLJ38295,HGNC:1274,FLJ Clone Symbol,FLJ Human cDNA Database
677183,MIR99AHG,FLJ38295,ENSG00000215386,FLJ Clone Symbol,FLJ Human cDNA Database
791883,MIR99AHG,FLJ38295,GENE ID:388815,FLJ Clone Symbol,FLJ Human cDNA Database

In [42]:
flj_clone_symbols_df

      Accesion No        ID
0        AK075326  PSEC0001
1        AK075326  FLJ91001
2        AK172724  PSEC0002
3        AK172724  FLJ91002
4        AK075327  PSEC0003
...           ...       ...
30581    AK057825  FLJ25096
30582    AK000479  FLJ20472
30583    AK125921  FLJ43933
30584    AK125959  FLJ43971
30585    AK000594  FLJ20587

[30586 rows x 2 columns]

## <a id='toc1_8_'></a>[Add Gene Family Symbol label](#toc0_)

### <a id='toc1_8_1_'></a>[Import the Gene Family Root symbols](#toc0_)

used the table generated in the symbol_capture_generation.ipynb

In [43]:
hgnc_gene_group_root_df = pd.read_hdf(
    "../output/hgnc_gene_group_root_df.h5", key='df'
    )
hgnc_gene_group_root_df

          HGNC ID Approved symbol  Gene group ID abbreviation
2      HGNC:24086            A1CF            725          RBM
12     HGNC:13666            AAAS           1051          NUP
13     HGNC:13666            AAAS            362          WDR
14     HGNC:21298            AACS             40          ACS
15        HGNC:17           AADAC            464          LIP
...           ...             ...            ...          ...
64109  HGNC:34749      TRX-CAT3-1            478           TR
64110  HGNC:34816      TRY-ATA1-1            478           TR
64124  HGNC:34842     TRY-GTA10-1            478           TR
64125  HGNC:35082     TRY-GTA11-1            478           TR
64126  HGNC:35071     TRY-GTA12-1            478           TR

[25386 rows x 4 columns]

In [44]:
hgnc_gene_group_root_df.loc[hgnc_gene_group_root_df["abbreviation"]== "PCDH"]

          HGNC ID Approved symbol  Gene group ID abbreviation
45540   HGNC:8655           PCDH1             19         PCDH
45541   HGNC:8659           PCDH7             19         PCDH
45542   HGNC:8660           PCDH8             19         PCDH
45543   HGNC:8661           PCDH9             19         PCDH
45548  HGNC:13404          PCDH10             19         PCDH
...           ...             ...            ...          ...
45619  HGNC:15688        PCDHGB9P             19         PCDH
45620   HGNC:8716         PCDHGC3             19         PCDH
45621   HGNC:8717         PCDHGC4             19         PCDH
45622   HGNC:8718         PCDHGC5             19         PCDH
45623   HGNC:8719         PCDHGCT             19         PCDH

[76 rows x 4 columns]

In [45]:
gene_group_capture_df = add_relationship_and_source_if_prefix(
    flj_clone_capture_df,
    hgnc_gene_group_root_df,
    ["primary_gene_symbol","concept_id"],
    ["Approved symbol","HGNC ID"],
    "gene_symbol",
    "abbreviation",
    "Prefix Gene Group Symbol",
    "HGNC",
    flj_clone_capture_df,
    "_upper"
)
gene_group_capture_df

,primary_gene_symbol,gene_symbol,concept_id,relationship,source
0,MT-TF,MT-TF,HGNC:7481,,
1,MT-RNR1,MT-RNR1,HGNC:7470,,
2,MT-TV,MT-TV,HGNC:7500,,
3,MT-RNR2,MT-RNR2,HGNC:7471,,
4,MT-TL1,MT-TL1,HGNC:7490,,
...,...,...,...,...,...
949763,SNORD3F,SNORD3P2,HGNC:52239,Prefix Gene Group Symbol,HGNC
949797,SCGB1B3P,SCGB1B3,HGNC:20943,Prefix Gene Group Symbol,HGNC
949810,OR4M2B,OR4M2,HGNC:55109,Prefix Gene Group Symbol,HGNC
949826,H2BN1,H2B.N,HGNC:56200,Prefix Gene Group Symbol,HGNC
949834,DUSP13A,DUSP13,HGNC:56772,Prefix Gene Group Symbol,HGNC

In [46]:
gene_group_capture_df.loc[gene_group_capture_df["primary_gene_symbol"] == "ABTB3"]

,primary_gene_symbol,gene_symbol,concept_id,relationship,source
12848,ABTB3,ABTB3,HGNC:23844,,
58080,ABTB3,ABTB2B,HGNC:23844,,
58081,ABTB3,BTBD11,HGNC:23844,,
58082,ABTB3,FLJ33957,HGNC:23844,,
112704,ABTB3,ABTB3,ENSG00000151136,Ortholog Symbol,Ensembl
164674,ABTB3,ABTB2B,ENSG00000151136,,
164675,ABTB3,BTBD11,ENSG00000151136,Ortholog Symbol,Ensembl
164676,ABTB3,FLJ33957,ENSG00000151136,,
231270,ABTB3,ABTB3,GENE ID:121551,,
279107,ABTB3,ABTB2B,GENE ID:121551,,
279108,ABTB3,BTBD11,GENE ID:121551,,
279109,ABTB3,FLJ33957,GENE ID:121551,,
485656,ABTB3,BTBD11,HGNC:23844,HGNC Previous Symbol,HGNC
501129,ABTB3,ABTB3,ENSG00000151136,,
516437,ABTB3,BTBD11,ENSG00000151136,,
521672,ABTB3,FLJ33957,HGNC:23844,FLJ Clone Symbol,FLJ Human cDNA Database
525243,ABTB3,FLJ33957,ENSG00000151136,FLJ Clone Symbol,FLJ Human cDNA Database
529049,ABTB3,FLJ33957,GENE ID:121551,FLJ Clone Symbol,FLJ Human cDNA Database
591849,ABTB3,BTBD11,HGNC:23844,Prefix Gene Group Symbol,HGNC

In [47]:
hgnc_gene_group_root_df.loc[hgnc_gene_group_root_df["Approved symbol"] == "ABTB3"]

        HGNC ID Approved symbol  Gene group ID abbreviation
144  HGNC:23844           ABTB3            861         BTBD
145  HGNC:23844           ABTB3            403        ANKRD

## <a id='toc1_9_'></a>[Add Phenotype Symbol label](#toc0_)

### <a id='toc1_9_1_'></a>[Import the Phenotype root symbols](#toc0_)

used the table generated in the symbol_capture_generation.ipynb

In [48]:
gene2phenotype_df = pd.read_hdf(
    "../output/gene2phenotype_df.h5", key='df'
    )
gene2phenotype_df

,gene_MIM_number,phenotype_MIM_number,Prefix,pheno_title,pheno_symbol,Entrez Gene ID (NCBI),Approved Gene Symbol (HGNC),Ensembl Gene ID (Ensembl)
2,614984,204750,Number Sign,2-AMINOADIPIC 2-OXOADIPIC ACIDURIA,AMOXAD,GENE ID:55526,DHTKD1,ENSG00000181192
3,614984,204750,Number Sign,ALPHA-AMINOADIPIC AND ALPHA-KETOADIPIC ACIDURIA,AAKAD,GENE ID:55526,DHTKD1,ENSG00000181192
4,614984,204750,Number Sign,2-AMINOADIPIC 2-OXOADIPIC ACIDURIA,AMOXAD,GENE ID:55526,DHTKD1,ENSG00000181192
5,600301,610006,Number Sign,SHORT/BRANCHED-CHAIN ACYL-CoA DEHYDROGENASE DE...,SBCADD,GENE ID:36,ACADSB,ENSG00000196177
6,609577,273750,Number Sign,THREE M SYNDROME 1,3M1,GENE ID:9820,CUL7,ENSG00000044090
...,...,...,...,...,...,...,...,...
17642,606636,606579,Number Sign,VITILIGO-ASSOCIATED MULTIPLE AUTOIMMUNE DISEAS...,VAMAS1,GENE ID:22861,NLRP1,ENSG00000091592
17643,606636,606579,Number Sign,VITILIGO,VTLG,GENE ID:22861,NLRP1,ENSG00000091592
17644,606636,606579,Number Sign,"SYSTEMIC LUPUS ERYTHEMATOSUS, VITILIGO-RELATED",SLEV1,GENE ID:22861,NLRP1,ENSG00000091592
17646,600571,616806,Number Sign,WILMS TUMOR 6,WT6,GENE ID:5978,REST,ENSG00000084093
17647,600571,616806,Number Sign,WILMS TUMOR 6,WT6,GENE ID:5978,REST,ENSG00000084093

using ENSG ID

In [49]:
phenotype_capture_ensg_df = add_relationship_and_source_if_prefix(
    gene_group_capture_df,
    gene2phenotype_df,
    ["primary_gene_symbol","concept_id"],
    ["Approved Gene Symbol (HGNC)","Ensembl Gene ID (Ensembl)"],
    "gene_symbol",
    "pheno_symbol",
    "Phenotype Symbol",
    "OMIM",
    gene_group_capture_df,
    "_upper"
)
phenotype_capture_ensg_df

,primary_gene_symbol,gene_symbol,concept_id,relationship,source
0,MT-TF,MT-TF,HGNC:7481,,
1,MT-RNR1,MT-RNR1,HGNC:7470,,
2,MT-TV,MT-TV,HGNC:7500,,
3,MT-RNR2,MT-RNR2,HGNC:7471,,
4,MT-TL1,MT-TL1,HGNC:7490,,
...,...,...,...,...,...
1009933,NOTCH2NLC,NIID,ENSG00000286219,Phenotype Symbol,OMIM
1009938,NOTCH2NLC,OPDM3,ENSG00000286219,Phenotype Symbol,OMIM
1009973,NUTM2B-AS1,OPML1,ENSG00000225484,Phenotype Symbol,OMIM
1010053,MYMX,CFZS2,ENSG00000262179,Phenotype Symbol,OMIM
1010555,PERCC1,DIAR11,ENSG00000284395,Phenotype Symbol,OMIM

using NCBI ID

In [50]:
phenotype_capture_ncbi_df = add_relationship_and_source_if_prefix(
    phenotype_capture_ensg_df,
    gene2phenotype_df,
    ["primary_gene_symbol","concept_id"],
    ["Approved Gene Symbol (HGNC)","Entrez Gene ID (NCBI)"],
    "gene_symbol",
    "pheno_symbol",
    "Phenotype Symbol",
    "OMIM",
    phenotype_capture_ensg_df,
    "_upper"
)
phenotype_capture_ncbi_df

,primary_gene_symbol,gene_symbol,concept_id,relationship,source
0,MT-TF,MT-TF,HGNC:7481,,
1,MT-RNR1,MT-RNR1,HGNC:7470,,
2,MT-TV,MT-TV,HGNC:7500,,
3,MT-RNR2,MT-RNR2,HGNC:7471,,
4,MT-TL1,MT-TL1,HGNC:7490,,
...,...,...,...,...,...
1052641,NOTCH2NLC,NIID,GENE ID:100996717,Phenotype Symbol,OMIM
1052646,NOTCH2NLC,OPDM3,GENE ID:100996717,Phenotype Symbol,OMIM
1052683,NUTM2B-AS1,OPML1,GENE ID:101060691,Phenotype Symbol,OMIM
1052789,MYMX,CFZS2,GENE ID:101929726,Phenotype Symbol,OMIM
1052997,PERCC1,DIAR11,GENE ID:105371045,Phenotype Symbol,OMIM

In [51]:
phenotype_capture_ncbi_df.loc[phenotype_capture_ncbi_df["gene_symbol"] == "ASP"]

       primary_gene_symbol gene_symbol       concept_id relationship source
51016                 ATG5         ASP         HGNC:589
62839                 ASIP         ASP         HGNC:745
73662                 ASPA         ASP         HGNC:756
78175                 A1CF         ASP       HGNC:24086
81337                 ASPM         ASP       HGNC:19048
85088            TMPRSS11D         ASP       HGNC:24059
88675               ROPN1L         ASP       HGNC:24060
157199                ATG5         ASP  ENSG00000057663
170048                ASIP         ASP  ENSG00000101440
183761                ASPA         ASP  ENSG00000108381
190552                A1CF         ASP  ENSG00000148584
196076                ASPM         ASP  ENSG00000066279
200905           TMPRSS11D         ASP  ENSG00000153802
204935              ROPN1L         ASP  ENSG00000145491
271894                ATG5         ASP     GENE ID:9474
283930                ASIP         ASP      GENE ID:434
294973                ASPA         ASP      GENE ID:443
299538                A1CF         ASP    GENE ID:29974
302734                ASPM         ASP   GENE ID:259266
307498           TMPRSS11D         ASP     GENE ID:9407
311141              ROPN1L         ASP    GENE ID:83853
384575                  C3         ASP        HGNC:1318
415384                  C3         ASP  ENSG00000125730
448715                  C3         ASP      GENE ID:718

In [52]:
phenotype_capture_ncbi_df.loc[phenotype_capture_ncbi_df["primary_gene_symbol"] == "C3"]

,primary_gene_symbol,gene_symbol,concept_id,relationship,source
27731,C3,C3,HGNC:1318,,
81662,C3,ARMD9,HGNC:1318,,
81663,C3,C3A,HGNC:1318,,
81664,C3,C3B,HGNC:1318,,
81665,C3,CPAMD1,HGNC:1318,,
131943,C3,C3,ENSG00000125730,Ortholog Symbol,Ensembl
196571,C3,ARMD9,ENSG00000125730,,
196572,C3,C3A,ENSG00000125730,,
196573,C3,C3B,ENSG00000125730,,
196574,C3,CPAMD1,ENSG00000125730,,
246354,C3,C3,GENE ID:718,,
303061,C3,ARMD9,GENE ID:718,,
303062,C3,C3A,GENE ID:718,,
303063,C3,C3B,GENE ID:718,,
303064,C3,CPAMD1,GENE ID:718,,
325966,C3,C3a,HGNC:1318,,
325967,C3,C3b,HGNC:1318,,
341759,C3,C3a,ENSG00000125730,,
341760,C3,C3b,ENSG00000125730,,
371316,C3,C3a,GENE ID:718,,
371317,C3,C3b,GENE ID:718,,
384574,C3,AHUS5,HGNC:1318,,
384575,C3,ASP,HGNC:1318,,
384576,C3,HEL-S-62p,HGNC:1318,,
415383,C3,AHUS5,ENSG00000125730,,
415384,C3,ASP,ENSG00000125730,,
415385,C3,HEL-S-62p,ENSG00000125730,,
448714,C3,AHUS5,GENE ID:718,,
448715,C3,ASP,GENE ID:718,,
448716,C3,HEL-S-62p,GENE ID:718,,
509912,C3,C3,ENSG00000125730,,
551987,C3,CPAMD1,HGNC:1318,Prefix Gene Group Symbol,HGNC
562055,C3,ARMD9,ENSG00000125730,Phenotype Symbol,OMIM
562767,C3,AHUS5,ENSG00000125730,Phenotype Symbol,OMIM
871853,C3,ARMD9,GENE ID:718,Phenotype Symbol,OMIM
1018028,C3,AHUS5,GENE ID:718,Phenotype Symbol,OMIM

In [53]:
filtered_df = phenotype_capture_ncbi_df[phenotype_capture_ncbi_df["gene_symbol"].str.startswith("FWP", na=False)]

In [54]:
filtered_df

       primary_gene_symbol gene_symbol         concept_id relationship source
61957                  A2M      FWP007             HGNC:7
168923                 A2M      FWP007    ENSG00000175899
283042                 A2M      FWP007          GENE ID:2
395651              CD2BP2      FWP010          HGNC:1656
396182             MORF4L1      FWP006         HGNC:16989
402604               OCEL1      FWP009         HGNC:26221
404497               ADAT3      FWP005         HGNC:25151
412262           RPL13AP25      FWP004         HGNC:36981
426526              CD2BP2      FWP010    ENSG00000169217
427060             MORF4L1      FWP006    ENSG00000185787
433535               OCEL1      FWP009    ENSG00000099330
435458               ADAT3      FWP005    ENSG00000213638
443592           RPL13AP25      FWP004    ENSG00000136149
460265              CD2BP2      FWP010      GENE ID:10421
460807             MORF4L1      FWP006      GENE ID:10933
467482               OCEL1      FWP009      GENE ID:79629
469456               ADAT3      FWP005     GENE ID:113179
478597           RPL13AP25      FWP004  GENE ID:100287887

In [55]:
phenotype_capture_ncbi_df.to_csv('../output/phenotype_capture_ncbi_df.csv', index=False)

In [56]:
edges_df = phenotype_capture_ncbi_df[phenotype_capture_ncbi_df["concept_id"].notna()]

In [57]:
edges_df.to_csv('../output/edges_df.csv', index=False)

In [58]:
phenotype_capture_ncbi_df = phenotype_capture_ncbi_df.sort_values(by='primary_gene_symbol')
phenotype_capture_ncbi_df.head(50)

,primary_gene_symbol,gene_symbol,concept_id,relationship,source
117096,5S_rRNA,5S_rRNA,ENSG00000278779,,
104695,5S_rRNA,5S_rRNA,ENSG00000285776,,
124249,5S_rRNA,5S_rRNA,ENSG00000277488,Ortholog Symbol,Ensembl
112706,5S_rRNA,5S_rRNA,ENSG00000273928,,
129586,5S_rRNA,5S_rRNA,ENSG00000266726,,
126907,5S_rRNA,5S_rRNA,ENSG00000266653,,
99091,5S_rRNA,5S_rRNA,ENSG00000278457,Ortholog Symbol,Ensembl
495560,5S_rRNA,5S_rRNA,ENSG00000278457,,
128459,5S_rRNA,5S_rRNA,ENSG00000275780,,
117841,5S_rRNA,5S_rRNA,ENSG00000285674,,
130132,5S_rRNA,5S_rRNA,ENSG00000285912,,
132828,5S_rRNA,5S_rRNA,ENSG00000263418,,
108720,5S_rRNA,5S_rRNA,ENSG00000277411,Ortholog Symbol,Ensembl
141743,5S_rRNA,5S_rRNA,ENSG00000285626,,
511854,5S_rRNA,5S_rRNA,ENSG00000276861,,
499529,5S_rRNA,5S_rRNA,ENSG00000277411,,
136323,5S_rRNA,5S_rRNA,ENSG00000276861,Ortholog Symbol,Ensembl
117299,5S_rRNA,5S_rRNA,ENSG00000285609,,
114810,5S_rRNA,5S_rRNA,ENSG00000283454,,
130703,5S_rRNA,5S_rRNA,ENSG00000265816,,
130676,5S_rRNA,5S_rRNA,ENSG00000288601,,
117097,5S_rRNA,5S_rRNA,ENSG00000277395,,
123395,5S_rRNA,5S_rRNA,ENSG00000275999,,
506411,5S_rRNA,5S_rRNA,ENSG00000277488,,
37,5S_rRNA,5S_rRNA,NaN,,
131263,5S_rRNA,5S_rRNA,ENSG00000266615,,
131979,5S_rRNA,5S_rRNA,ENSG00000266035,,
123397,5S_rRNA,5S_rRNA,ENSG00000277584,,
216766,5_8S_rRNA,5_8S_rRNA,GENE ID:124908376,,
216611,5_8S_rRNA,5_8S_rRNA,GENE ID:124907130,,
216674,5_8S_rRNA,5_8S_rRNA,GENE ID:124907467,,
216720,5_8S_rRNA,5_8S_rRNA,GENE ID:124907705,,
216765,5_8S_rRNA,5_8S_rRNA,GENE ID:124908375,,
216671,5_8S_rRNA,5_8S_rRNA,GENE ID:124907440,,
216673,5_8S_rRNA,5_8S_rRNA,GENE ID:124907458,,
216672,5_8S_rRNA,5_8S_rRNA,GENE ID:124907450,,
216667,5_8S_rRNA,5_8S_rRNA,GENE ID:124907341,,
216612,5_8S_rRNA,5_8S_rRNA,GENE ID:124907131,,
216763,5_8S_rRNA,5_8S_rRNA,GENE ID:124908373,,
216617,5_8S_rRNA,5_8S_rRNA,GENE ID:124907136,,
216661,5_8S_rRNA,5_8S_rRNA,GENE ID:124907335,,
216616,5_8S_rRNA,5_8S_rRNA,GENE ID:124907135,,
216764,5_8S_rRNA,5_8S_rRNA,GENE ID:124908374,,
216615,5_8S_rRNA,5_8S_rRNA,GENE ID:124907134,,
216662,5_8S_rRNA,5_8S_rRNA,GENE ID:124907336,,
216614,5_8S_rRNA,5_8S_rRNA,GENE ID:124907133,,
216663,5_8S_rRNA,5_8S_rRNA,GENE ID:124907337,,
216664,5_8S_rRNA,5_8S_rRNA,GENE ID:124907338,,
216665,5_8S_rRNA,5_8S_rRNA,GENE ID:124907339,,
216666,5_8S_rRNA,5_8S_rRNA,GENE ID:124907340,,